---
title: "ICBEdataset_paper_InterCoderByLevels"
output: html_document
---

```{r}
library(flextable)
library(tidyverse)
```

```{r, echo=FALSE}

icb_long_clean <- readRDS(file=paste0(here::here(), "/replication_paper/data/in/icb_long_clean.Rds")) #%>% 
                  #mutate(temp_row_id=paste(email_id, crisno,sentence_number_int_aligned, variable, sep="_")) %>%
                  #mutate(cleaned=temp_row_id %>% str_detect("_clean")) %>%
                  #mutate(temp_row_id= temp_row_id %>% str_replace("_clean","")) %>%
                  #arrange(desc(cleaned), temp_row_id) %>% 
                  #filter(!duplicated(temp_row_id)) %>%
                  #mutate(variable= variable %>% str_replace("_clean",""))

icb_wide_clean <- readRDS(file=paste0(here::here(), "/replication_paper/data/in/icb_wide_clean.Rds"))

```

```{r}

target_file <- paste0(here::here(),"/replication_paper/data/in/icbe_litreview,_trees_sentences.xlsx")
full_tree    <- readxl::read_excel(target_file, sheet="Codebook in Tree Form")


full_tree <- full_tree %>% filter(!is.na(Leaf) & Leaf!='')
#The leafs aren't unique here because you can get to the same branch multiple ways

#This ignores conditions FYI
#Behavior # 3 bits
#think_aggression #1 bit
#say_aggression #1 bit
#do_aggression #1 bit
#Do_Armed_Unarmed #1 bit
#do_Act_Interact #1 bit
#full_tree$Leaf_Simplified %>% unique() %>% length() #66 bits

#Only 70 bits total
  
#That's only another 29 bits
full_tree$Think_Type_L0 %>% unique() %>% length() #6
full_tree$Say_Type_L0 %>% unique() %>% length() #5
full_tree$Do_Type_L0 %>% unique() %>% length() #18

```

```{r}

library(dplyr, warn.conflicts = FALSE)
options(warn=-1)

icb_long_clean$email_id_expert <- icb_long_clean$email_id %>% str_detect("grad|postgrad")

#icb_long_clean %>% dplyr::select(variable) %>% distinct() %>% View()

paste_collapse=function(x) paste(x %>% sort(), collapse=";") %>% str_replace_all("https://en.wikipedia.org/wiki/",'') #sorting removes the order indeterminacy
actors_clean <- icb_long_clean %>%
                filter(variable %>% str_detect('actor') & variable %>% str_detect('clean')) %>%
                mutate(variable=variable %>%str_replace('other_','')) %>% #removing the text other from the variable will auto include it in our list here
                pivot_wider(names_from=variable,
                            values_from=value,
                            values_fn=paste_collapse
                            ) %>%
                 dplyr::mutate(think_actor_a_clean = strsplit(as.character(think_actor_a_clean), ";")) %>% tidyr::unnest(think_actor_a_clean) %>% dplyr::mutate(think_actor_a_clean=think_actor_a_clean %>% trimws()) %>%
                 dplyr::mutate(say_actor_a_clean = strsplit(as.character(say_actor_a_clean), ";")) %>% tidyr::unnest(say_actor_a_clean) %>% dplyr::mutate(say_actor_a_clean=say_actor_a_clean %>% trimws()) %>%
                 dplyr::mutate(say_actor_b_clean = strsplit(as.character(say_actor_b_clean), ";")) %>% tidyr::unnest(say_actor_b_clean) %>% dplyr::mutate(say_actor_b_clean=say_actor_b_clean %>% trimws()) %>%
                 dplyr::mutate(do_actor_a_clean = strsplit(as.character(do_actor_a_clean), ";")) %>% tidyr::unnest(do_actor_a_clean) %>% dplyr::mutate(do_actor_a_clean=do_actor_a_clean %>% trimws()) %>%
                 dplyr::mutate(do_actor_b_clean = strsplit(as.character(do_actor_b_clean), ";")) %>% tidyr::unnest(do_actor_b_clean) %>% dplyr::mutate(do_actor_b_clean=do_actor_b_clean %>% trimws()) 
                  #currently ignoring condition
dim(actors_clean)


#I think we convert this to actor-event, where every lhs actor mentioned gets a row and then we ask what people thought THEY did in that sentence
temp_long <- icb_long_clean %>%
             filter(!variable %>% str_detect('actor') ) %>%
            dplyr::select(email_id,  crisno, sentence_number_int_aligned,  event_number_int,  variable, value) %>%
            filter(variable %in% c('sentence_events',
                                   'act_cooperative',
                                   'act_descalate', 
                                   'act_escalate',
                                   'act_uncooperative',
                                   'interact_decreasecoop',
                                   'interact_descalate',
                                   'interact_escalate',
                                   'interact_increasecoop',
                                   'thinkkind',
                                   'sayintkind'
                                   ) 
                        ) %>% distinct() %>% 
                  mutate(value= value %>% trimws() %>% tolower()) %>%
                  #left_join(full_tree %>% dplyr::select(Behavior, value=Leaf) %>% 
                  #            mutate(value= value %>% trimws() %>% tolower())) %>%
                  left_join(full_tree %>% dplyr::rename(value=Leaf)  %>%
                              mutate(value= value %>% trimws() %>% tolower()) ) %>%
              group_by(email_id,  crisno, sentence_number_int_aligned) %>%
                mutate(event_number_int_max=max(event_number_int, na.rm=T)) %>%
              ungroup() %>%
              full_join(
                actors_clean %>% dplyr::select(email_id,  crisno, sentence_number_int_aligned,  event_number_int,  contains('actor')) %>%
                  dplyr::select(-condition_do_actor_a_clean,-condition_do_actor_b_clean) #ignoring conditions for now
              )


#temp_long %>% dplyr::select(value, Behavior) %>% distinct() %>% View()

#i_think_actor_a=, #we're going to join on these
#i_say_actor_a=,
#i_say_actor_b=,
#i_do_actor_a=,
#i_do_actor_b=,

#Starting first with the 63% of the time they saw only 1 event
events_variable_value <- temp_long %>%
                                #filter(!is.na(Behavior )) %>%
                                #filter(event_number_int_max==1) %>%
  
                                mutate(index=paste(crisno , sentence_number_int_aligned ,  think_actor_a_clean,say_actor_a_clean,say_actor_b_clean,do_actor_a_clean,do_actor_b_clean, sep="_")) %>% #add actors to this
                                filter(!index %>% str_detect('_NA_NA_NA_NA_NA')) %>% #ignore 
                                dplyr::select(email_id,
                                              index, 
                                              #contains('actor'),
                                              Event_Count,
                                              Behavior,
                                              think_aggression,
                                              say_aggression,
                                              do_aggression,
                                              Do_Armed_Unarmed,
                                              do_Act_Interact,
                                              Think_Type_L0,
                                              Say_Type_L0,
                                              Do_Type_L0,
                                              Leaf_Simplified#,
                                              #variable,
                                              #value
                                              )


                                              
#This actually takes a while now that there are dead
library(fastDummies)
#I think we do physically have to go to wide
events_wide_i <- events_variable_value %>% 
                                       rename(i_email_id=email_id,
                                              i_Event_Count=Event_Count,
                                              i_Behavior=Behavior,
                                              i_think_aggression=think_aggression,
                                              i_say_aggression=say_aggression,
                                              i_do_aggression=do_aggression,
                                              i_Do_Armed_Unarmed=Do_Armed_Unarmed,
                                              i_do_Act_Interact=do_Act_Interact,
                                              i_Think_Type_L0=Think_Type_L0,
                                              i_Say_Type_L0=Say_Type_L0,
                                              i_Do_Type_L0=Do_Type_L0,
                                              i_Leaf_Simplified=Leaf_Simplified
                                              ) %>%
                                       #fastDummies::dummy_cols(select_columns='a_Event_Count', remove_selected_columns=T) %>%
                                       fastDummies::dummy_cols(select_columns='i_Behavior', remove_selected_columns=T, ignore_na = T) %>%
                                       fastDummies::dummy_cols(select_columns='i_think_aggression', remove_selected_columns=T, ignore_na = T) %>%
                                       fastDummies::dummy_cols(select_columns='i_say_aggression', remove_selected_columns=T, ignore_na = T) %>%
                                       fastDummies::dummy_cols(select_columns='i_do_aggression', remove_selected_columns=T, ignore_na = T) %>%
  
                                       fastDummies::dummy_cols(select_columns='i_Do_Armed_Unarmed', remove_selected_columns=T, ignore_na = T) %>%
                                       fastDummies::dummy_cols(select_columns='i_do_Act_Interact', remove_selected_columns=T, ignore_na = T) %>%  
                                       fastDummies::dummy_cols(select_columns='i_Think_Type_L0', remove_selected_columns=T, ignore_na = T) %>%
                                       fastDummies::dummy_cols(select_columns='i_Say_Type_L0', remove_selected_columns=T, ignore_na = T) %>%
                                       fastDummies::dummy_cols(select_columns='i_Do_Type_L0', remove_selected_columns=T, ignore_na = T) %>%
                                       fastDummies::dummy_cols(select_columns='i_Leaf_Simplified', remove_selected_columns=T, ignore_na = T) %>%
                                       group_by(i_email_id,index) %>%
                                        summarise_all(max, na.rm=T) %>% #max not sum
                                       ungroup() %>%
                                       mutate_if(is.numeric, function(x) ifelse(is.infinite(x), 0, x))
dim(events_wide_i) #113049    116
events_wide_j <- events_wide_i
names(events_wide_j) <- events_wide_j %>% names() %>% str_replace("^i_","j_")
dim(events_wide_j) #67558   106

#This is going to be a million?
diads_wide <-  events_wide_i %>%
               
               left_join(events_wide_j, by=c('index'='index') ) %>% 
               filter(i_email_id!=j_email_id) %>% 
               #rowwise() %>%
               mutate(ij_email_id= ifelse( i_email_id>=j_email_id,paste0(i_email_id,j_email_id),paste0(j_email_id,i_email_id) ) ) %>%
               mutate(index_ij_email_id=paste0(index,ij_email_id)) %>%
               filter(!duplicated(index_ij_email_id)) %>%
               arrange(index) %>%
               ungroup() %>%
               mutate_if(is.numeric, function(x) ifelse(is.infinite(x), 0, x))
dim(diads_wide) #204,781    213


variables <- setdiff( names(diads_wide) %>% str_replace("ij_|i_|j_","") %>% unique(), c('index_ij_email_id','email_id','index',"ij_email_id","index_ij_email_id","match_i_email_id","index_email_id"  ))
diads_wide <- as.data.frame(diads_wide)
for(q in variables){
  print(q)
  newvar <- paste0("match_",q)
  a_oldvar <- paste0("i_",q)
  b_oldvar <- paste0("j_",q)
  diads_wide[,newvar] <-  0 #default 0
  diads_wide[,newvar] <-  ifelse(diads_wide[,a_oldvar] %in% 1 &  diads_wide[,b_oldvar] %in% 1, 1,  diads_wide[,newvar])  #if both 1 then 1
  diads_wide[,newvar] <-  ifelse(diads_wide[,a_oldvar] %in% 0 &  diads_wide[,b_oldvar] %in% 0, NA, diads_wide[,newvar])  #if both 0 then NA
}

diads_matches <- diads_wide %>% 
                 dplyr::select(index_ij_email_id,  starts_with("match"))  %>%
                 dplyr::select(-ends_with("_NA")) 
  
final_counts_numerator <- diads_matches %>% summarise_if(is.numeric, sum, na.rm=T)
final_counts_denominator <- diads_matches %>% summarise_if(is.numeric, ~sum(is.finite(.x)) )

final_scores <- final_counts_numerator / final_counts_denominator
#One takeaway is that because coders split on act vs interact is artificially drops the agreement

#New plan, we're going to pull out those dimensions seperately
#final_scores %>% round(2) %>% t()  %>% as.data.frame() %>%  tibble::rownames_to_column( "VALUE") %>% View()
options(warn=0)

final_scores_df <- data.frame(varname= names(final_scores),  final_scores=final_scores %>% round(2) %>% t(),final_counts_numerator=final_counts_numerator%>% t()) %>% filter(final_counts_numerator>1)
#final_scores_df %>% View() 
#cor(final_scores_df) #.64 correlation between agreement and how often its used

p_intercoder_agreement <- final_scores_df %>%
                                  mutate(grouping=NA) %>%
                                  mutate(grouping=ifelse(varname %>% str_detect('Event_Count'), 'Event_Count' ,  grouping)) %>%
                                  mutate(grouping=ifelse(varname %>% str_detect('match_Behavior_'), 'Behavior' ,  grouping)) %>%
                                  mutate(grouping=ifelse(varname %>% str_detect('think_aggression'), 'Aggression (think)' ,  grouping)) %>%
                                  mutate(grouping=ifelse(varname %>% str_detect('say_aggression_'), 'Aggression (say)' ,  grouping)) %>%
                                  mutate(grouping=ifelse(varname %>% str_detect('do_aggression_'), 'Aggression (do)' ,  grouping)) %>%
                                  mutate(grouping=ifelse(varname %>% str_detect('Do_Armed_Unarmed'), 'Armed or Unarmed Agents' ,  grouping)) %>%
                                  mutate(grouping=ifelse(varname %>% str_detect('do_Act_Interact'), 'Action or Interaction' ,  grouping)) %>%
                                  mutate(grouping=ifelse(varname %>% str_detect('Think_Type_L0'), 'Think (L0)' ,  grouping)) %>%
                                  mutate(grouping=ifelse(varname %>% str_detect('Say_Type_L0'), 'Say (L0)' ,  grouping)) %>%
                                  mutate(grouping=ifelse(varname %>% str_detect('Do_Type_L0'), 'Do (L0)' ,  grouping)) %>%
                                  mutate(grouping=ifelse(varname %>% str_detect('Leaf_Simplified'), 'Leaf Simplified' ,  grouping)) %>%
                                  mutate(grouping=grouping %>% factor(levels=c('Event_Count', 'Behavior','Aggression (think)','Aggression (say)','Aggression (do)',
                                                                               'Armed or Unarmed Agents','Action or Interaction',
                                                                               'Think (L0)','Say (L0)','Do (L0)','Leaf Simplified') %>% rev() ) ) %>%
                                  ggplot(aes(x=final_scores, y=grouping)) + 
                                  geom_boxplot() +
                                  xlab("Intercoder Agreemnt (Experts, positives only, Single Event Sentences)") +
                                  ylab("Psuedo Ontology Tree Depth")

```


```{r, eval=F}
p_intercoder_agreement
```



```{r}

library(dplyr, warn.conflicts = FALSE)
options(warn=-1)

icb_long_clean$email_id_expert <- icb_long_clean$email_id %>% str_detect("grad|postgrad")

#icb_long_clean %>% dplyr::select(variable) %>% distinct() %>% View()

temp_long <- icb_long_clean %>%
                      dplyr::select(email_id,  email_id_expert, crisno, sentence_number_int_aligned,  event_number_int,  variable, value) %>%
                      filter(variable %in% c('sentence_events',
                                             'act_cooperative',
                                             'act_descalate', 
                                             'act_escalate',
                                             'act_uncooperative',
                                             'interact_decreasecoop',
                                             'interact_descalate',
                                             'interact_escalate',
                                             'interact_increasecoop',
                                             'thinkkind',
                                             'sayintkind'
                                             ) 
                        ) %>% distinct() %>% 
                  mutate(value= value %>% trimws() %>% tolower()) %>%
                  #left_join(full_tree %>% dplyr::select(Behavior, value=Leaf) %>% 
                  #            mutate(value= value %>% trimws() %>% tolower())) %>%
                  left_join(full_tree %>% dplyr::rename(value=Leaf)  %>%
                              mutate(value= value %>% trimws() %>% tolower()) ) %>%
              group_by(email_id,  crisno, sentence_number_int_aligned) %>%
                mutate(event_number_int_max=max(event_number_int, na.rm=T)) %>%
              ungroup()


#temp_long %>% dplyr::select(value, Behavior) %>% distinct() %>% View()

#Starting first with the 63% of the time they saw only 1 event
events_variable_value <- temp_long %>%
                                #filter(!is.na(Behavior )) %>%
                                #filter(event_number_int_max==1) %>%
  
                                mutate(index=paste(crisno , sentence_number_int_aligned ,  event_number_int, sep="_")) %>%
                                dplyr::select(email_id, index, 
                                              Event_Count,
                                              Behavior,
                                              think_aggression,
                                              say_aggression,
                                              do_aggression,
                                              Do_Armed_Unarmed,
                                              do_Act_Interact,
                                              Think_Type_L0,
                                              Say_Type_L0,
                                              Do_Type_L0,
                                              Leaf_Simplified#,
                                              #variable,
                                              #value
                                              )

                                              
#This actually takes a while now that there are dead
library(fastDummies)
#I think we do physically have to go to wide
events_wide_a <- events_variable_value %>% 
                                       rename(a_email_id=email_id,
                                              a_Event_Count=Event_Count,
                                              a_Behavior=Behavior,
                                              a_think_aggression=think_aggression,
                                              a_say_aggression=say_aggression,
                                              a_do_aggression=do_aggression,
                                              a_Do_Armed_Unarmed=Do_Armed_Unarmed,
                                              a_do_Act_Interact=do_Act_Interact,
                                              a_Think_Type_L0=Think_Type_L0,
                                              a_Say_Type_L0=Say_Type_L0,
                                              a_Do_Type_L0=Do_Type_L0,
                                              a_Leaf_Simplified=Leaf_Simplified
                                              ) %>%
                                       fastDummies::dummy_cols(select_columns='a_Event_Count', remove_selected_columns=T) %>%
                                       fastDummies::dummy_cols(select_columns='a_Behavior', remove_selected_columns=T) %>%
                                       fastDummies::dummy_cols(select_columns='a_think_aggression', remove_selected_columns=T) %>%
                                       fastDummies::dummy_cols(select_columns='a_say_aggression', remove_selected_columns=T) %>%
                                       fastDummies::dummy_cols(select_columns='a_do_aggression', remove_selected_columns=T) %>%
  
                                       fastDummies::dummy_cols(select_columns='a_Do_Armed_Unarmed', remove_selected_columns=T) %>%
                                       fastDummies::dummy_cols(select_columns='a_do_Act_Interact', remove_selected_columns=T) %>%  
                                       fastDummies::dummy_cols(select_columns='a_Think_Type_L0', remove_selected_columns=T) %>%
                                       fastDummies::dummy_cols(select_columns='a_Say_Type_L0', remove_selected_columns=T) %>%
                                       fastDummies::dummy_cols(select_columns='a_Do_Type_L0', remove_selected_columns=T) %>%
                                       fastDummies::dummy_cols(select_columns='a_Leaf_Simplified', remove_selected_columns=T) %>%
                                       group_by(a_email_id,index) %>%
                                       summarise_all(max, na.rm=T) %>% #max not sum
                                       ungroup()
dim(events_wide_a) #12368   159

events_wide_b <- events_variable_value %>% 
                                       rename(b_email_id=email_id,
                                              b_Event_Count=Event_Count,
                                              b_Behavior=Behavior,
                                              b_think_aggression=think_aggression,
                                              b_say_aggression=say_aggression,
                                              b_do_aggression=do_aggression,
                                              b_Do_Armed_Unarmed=Do_Armed_Unarmed,
                                              b_do_Act_Interact=do_Act_Interact,
                                              b_Think_Type_L0=Think_Type_L0,
                                              b_Say_Type_L0=Say_Type_L0,
                                              b_Do_Type_L0=Do_Type_L0,
                                              b_Leaf_Simplified=Leaf_Simplified
                                              ) %>%
                                       fastDummies::dummy_cols(select_columns='b_Event_Count', remove_selected_columns=T) %>%
                                       fastDummies::dummy_cols(select_columns='b_Behavior', remove_selected_columns=T) %>%
                                       fastDummies::dummy_cols(select_columns='b_think_aggression', remove_selected_columns=T) %>%
                                       fastDummies::dummy_cols(select_columns='b_say_aggression', remove_selected_columns=T) %>%
                                       fastDummies::dummy_cols(select_columns='b_do_aggression', remove_selected_columns=T) %>%
  
                                       fastDummies::dummy_cols(select_columns='b_Do_Armed_Unarmed', remove_selected_columns=T) %>%
                                       fastDummies::dummy_cols(select_columns='b_do_Act_Interact', remove_selected_columns=T) %>%  
                                       fastDummies::dummy_cols(select_columns='b_Think_Type_L0', remove_selected_columns=T) %>%
                                       fastDummies::dummy_cols(select_columns='b_Say_Type_L0', remove_selected_columns=T) %>%
                                       fastDummies::dummy_cols(select_columns='b_Do_Type_L0', remove_selected_columns=T) %>%
                                       fastDummies::dummy_cols(select_columns='b_Leaf_Simplified', remove_selected_columns=T) %>%
                                       group_by(b_email_id,index) %>%
                                       summarise_all(max, na.rm=T) %>% #max not sum
                                       ungroup()
dim(events_wide_b) #12368   159

diads_wide <-  events_wide_a %>%
               left_join(events_wide_b, by=c('index'='index') ) %>% 
               filter(a_email_id!=b_email_id) %>% 
               #rowwise() %>%
               mutate(ab_email_id= ifelse( a_email_id>=b_email_id,paste0(a_email_id,b_email_id),paste0(b_email_id,a_email_id) ) ) %>%
               mutate(index_ab_email_id=paste0(index,ab_email_id)) %>%
               filter(!duplicated(index_ab_email_id)) %>%
               arrange(index) %>%
               ungroup() %>%
               mutate_if(is.numeric, function(x) ifelse(is.infinite(x), 0, x))

variables <- setdiff( names(diads_wide) %>% str_replace("a_|b_","") %>% unique(), c('index_ab_email_id','email_id','index','aemail_id','index_aemail_id'))
diads_wide <- as.data.frame(diads_wide)
for(q in variables){
  print(q)
  newvar <- paste0("match_",q)
  a_oldvar <- paste0("a_",q)
  b_oldvar <- paste0("b_",q)
  diads_wide[,newvar] <-  0 #default 0
  diads_wide[,newvar] <-  ifelse(diads_wide[,a_oldvar] %in% 1 &  diads_wide[,b_oldvar] %in% 1, 1,  diads_wide[,newvar])  #if both 1 then 1
  diads_wide[,newvar] <-  ifelse(diads_wide[,a_oldvar] %in% 0 &  diads_wide[,b_oldvar] %in% 0, NA, diads_wide[,newvar])  #if both 0 then NA
}

diads_matches <- diads_wide %>% 
                 dplyr::select(index_ab_email_id,  starts_with("match"))  %>%
                 dplyr::select(-ends_with("_NA")) 
  
final_counts_numerator <- diads_matches %>% summarise_if(is.numeric, sum, na.rm=T)
final_counts_denominator <- diads_matches %>% summarise_if(is.numeric, ~sum(is.finite(.x)) )

final_scores <- final_counts_numerator / final_counts_denominator
#One takeaway is that because coders split on act vs interact is artificially drops the agreement

#New plan, we're going to pull out those dimensions seperately
#final_scores %>% round(2) %>% t()  %>% as.data.frame() %>%  tibble::rownames_to_column( "VALUE") %>% View()
options(warn=0)

final_scores_df_novices <- data.frame(varname= names(final_scores),  final_scores=final_scores %>% round(2) %>% t(),final_counts_numerator=final_counts_numerator%>% t()) %>% filter(final_counts_numerator>1)
#final_scores_df %>% View() 
#cor(final_scores_df) #.64 correlation between agreement and how often its used

p_intercoder_agreement_novice <- final_scores_df_novices %>%
  mutate(grouping=NA) %>%
  mutate(grouping=ifelse(varname %>% str_detect('Event_Count'), 'Event_Count' ,  grouping)) %>%
  mutate(grouping=ifelse(varname %>% str_detect('match_Behavior_'), 'Behavior' ,  grouping)) %>%
  mutate(grouping=ifelse(varname %>% str_detect('think_aggression'), 'Aggression (think)' ,  grouping)) %>%
  mutate(grouping=ifelse(varname %>% str_detect('say_aggression_'), 'Aggression (say)' ,  grouping)) %>%
  mutate(grouping=ifelse(varname %>% str_detect('do_aggression_'), 'Aggression (do)' ,  grouping)) %>%
  mutate(grouping=ifelse(varname %>% str_detect('Do_Armed_Unarmed'), 'Armed or Unarmed Agents' ,  grouping)) %>%
  mutate(grouping=ifelse(varname %>% str_detect('do_Act_Interact'), 'Action or Interaction' ,  grouping)) %>%
  mutate(grouping=ifelse(varname %>% str_detect('Think_Type_L0'), 'Think (L0)' ,  grouping)) %>%
  mutate(grouping=ifelse(varname %>% str_detect('Say_Type_L0'), 'Say (L0)' ,  grouping)) %>%
  mutate(grouping=ifelse(varname %>% str_detect('Do_Type_L0'), 'Do (L0)' ,  grouping)) %>%
  mutate(grouping=ifelse(varname %>% str_detect('Leaf_Simplified'), 'Leaf Simplified' ,  grouping)) %>%
  mutate(grouping=grouping %>% factor(levels=c('Event_Count', 'Behavior','Aggression (think)','Aggression (say)','Aggression (do)',
                                               'Armed or Unarmed Agents','Action or Interaction',
                                               'Think (L0)','Say (L0)','Do (L0)','Leaf Simplified') %>% rev() ) ) %>%
  ggplot(aes(x=final_scores, y=grouping)) + 
  geom_boxplot() +
  xlab("Intercoder Agreemnt (Experts, positives only, Single Event Sentences)") +
  ylab("Psuedo Ontology Tree Depth")

```


```{r}



p_intercoder_agreement_both <- bind_rows(
  final_scores_df_novices %>% mutate(coder="novices") ,
  final_scores_df_experts %>% mutate(coder="experts") 
) %>%
  mutate(coder = coder %>% factor(levels=c('novices','experts')  )) %>%
  mutate(grouping=NA) %>%
  mutate(grouping=ifelse(varname %>% str_detect('Event_Count'), 'Event_Count' ,  grouping)) %>%
  mutate(grouping=ifelse(varname %>% str_detect('match_Behavior_'), 'Behavior' ,  grouping)) %>%
  mutate(grouping=ifelse(varname %>% str_detect('think_aggression'), 'Aggression (think)' ,  grouping)) %>%
  mutate(grouping=ifelse(varname %>% str_detect('say_aggression_'), 'Aggression (say)' ,  grouping)) %>%
  mutate(grouping=ifelse(varname %>% str_detect('do_aggression_'), 'Aggression (do)' ,  grouping)) %>%
  mutate(grouping=ifelse(varname %>% str_detect('Do_Armed_Unarmed'), 'Armed or Unarmed Agents' ,  grouping)) %>%
  mutate(grouping=ifelse(varname %>% str_detect('do_Act_Interact'), 'Action or Interaction' ,  grouping)) %>%
  mutate(grouping=ifelse(varname %>% str_detect('Think_Type_L0'), 'Think (L0)' ,  grouping)) %>%
  mutate(grouping=ifelse(varname %>% str_detect('Say_Type_L0'), 'Say (L0)' ,  grouping)) %>%
  mutate(grouping=ifelse(varname %>% str_detect('Do_Type_L0'), 'Do (L0)' ,  grouping)) %>%
  mutate(grouping=ifelse(varname %>% str_detect('Leaf_Simplified'), 'Leaf Simplified' ,  grouping)) %>%
  mutate(grouping=grouping %>% factor(levels=c('Event_Count', 'Behavior','Aggression (think)','Aggression (say)','Aggression (do)',
                                               'Armed or Unarmed Agents','Action or Interaction',
                                               'Think (L0)','Say (L0)','Do (L0)','Leaf Simplified') %>% rev() ) ) %>%
  ggplot(aes(x=final_scores, y=grouping, color=coder)) + 
  geom_boxplot() +
  ggtitle("Intercoder Agreement") +
  xlab("Probability Others Assigned Tag Given Anyone Did") +
  ylab("Psuedo Ontology Tree Depth")

p_intercoder_agreement_both

```



