---
title: 'LitReviewTable.Rmd'
site: bookdown::bookdown_site
bibliography: ../ICBintro.bib
output: 
  rticles::arxiv_article:
    keep_tex: true
header-includes:
  - \usepackage[utf8]{inputenc}
  - \usepackage{pifont}
  - \usepackage{newunicodechar}
  - \newunicodechar{✓}{\ding{51}}
  - \newunicodechar{✗}{\ding{55}}
  - \usepackage{array}
  - \usepackage{ctable} # added for demo
  - \usepackage{natbib} #added for latex citation within huxtable
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{makecell}
  - \usepackage{titlesec}
  - \usepackage[parfill]{parskip}
  - \usepackage{makecell}
  - \usepackage{graphicx}
  - \usepackage{caption}
  - \usepackage[capposition=top]{floatrow}
  - \titleformat{\subsubsection}{\normalfont\normalsize\itshape}{\thesubsubsection}{1em}{}
  - \titlespacing*{\subsubsection}{0pt}{3.25ex plus 1ex minus .2ex}{0ex plus .2ex}
  - \DeclareUnicodeCharacter{00A0}{ }
  - \usepackage{setspace}
  - \usepackage{cellspace}
  - \setlength\cellspacetoplimit{0.8ex}
  - \renewcommand{\arraystretch}{0.8}
  - \AtBeginEnvironment{tabular}{\singlespacing}
  - \AtBeginEnvironment{lltable}{\singlespacing}
---

```{r, echo=F, results='asis', message=F, warning=F, eval=T , cache=F}

library(flextable)
library(ftExtra)
library(tidyverse)

```

```{r, echo=F, results='asis', message=F, warning=F, eval=T , cache=F}

target_file <- paste0(here::here(),"/replication_paper/data/in/icbe_litreview_trees_sentences.xlsx")
lit_review_pull    <- readxl::read_excel(target_file, sheet="DatasetsComparisonLitReview")

```

## Arxiv Version


```{r, echo=FALSE, results='asis', include=T, cache=F, ft.arraystretch=0.75}

#https://davidgohel.github.io/flextable/reference/knit_print.flextable.html#chunk-options
# NOTE: If one of the citations is degenerate this will throw an error when knitting that is annoying to track down. You have to remove cite by cite to see which one it is.
set_flextable_defaults(fonts_ignore=TRUE)

lit_review_alt <- lit_review_pull %>%
                  dplyr::select(-Codebook, -`Cameo Codes`, -`ICB Codes`) #%>% 
                  #dplyr::filter(is.na(group))


n=nrow(lit_review_alt)
ft <- NULL
ft <- lit_review_alt %>%
      flextable::as_flextable() %>%
      add_header( 
                  #"ICB Corpus"="Corpus",
                  "ICBe (ours)"="Events Datasets",
                  "Cameo"="Events Datasets",
                  "MIDs Incidents"="Events Datasets",
                  "UCDP-GED"="Events Datasets",
                  "ICB"="Episodes Datasets",
                  "COW"="Episodes Datasets",
                  "MIDs"="Episodes Datasets",
                  top = TRUE ) %>%

      set_header_labels(
        values = list("...1" = "" , "...2" = "" ) 
        ) %>%
      merge_h(part = "header") %>%
  
      #bg( i=1:(n) , j = condition, part = "body", bg = "#EFEFEF") %>%
      #bg( i=2 , j = condition, part = "header", bg = "#EFEFEF") %>%
      bg( i = which( 1:nrow(lit_review_alt) %% 2 == 1)  , j=3:ncol(lit_review_alt), part = "body", bg = "#EFEFEF") %>%
      #width(j = 1, width=1.25) %>%
      #width(j = 2:ncol(lit_review_alt), width=0.25) %>%
      flextable::fontsize(size = 7, part = "all") %>%
      flextable::rotate(i=2, rotation="tbrl",part="header") %>%
      #flextable::set_header_labels( values = list(x1 = "", x2 = "")) %>%
      flextable::align(align = "center", part = "body") %>%
      flextable::align(align = "center", part = "header")   %>%

      flextable::colformat_char(
          j = 1:ncol(lit_review_alt),
          na_str = "",
          prefix = "",
          suffix = ""
      ) %>%

      hline(i=c(1), j=3:ncol(lit_review_alt),  border = NULL, part = "header") %>%
      hline(i=c(2,3,7,10,15, 19, 27), border = NULL, part = "body") %>% #,10,14, 20,27,37, n

      #set_table_properties(layout="autofit")  %>%
      vline( i = 1:2, j = c(1,2,3,7)+2, border = NULL, part = "header") %>%
      vline( i = 1:(n), j = 1:2, border = NULL, part = "body")  %>%
      vline( i = 1:(n), j = c(1,2,3,7)+2, border = NULL, part = "body") 
  
      #autofit()
      #fit_to_width(max_width=12) #This is crazy slow
      #flextable::autofit() 
      #set_table_properties(width = 1, layout = "autofit")

#https://cran.r-project.org/web/packages/ftExtra/vignettes/format_columns.html

litreview_ft <- ft %>% 
  flextable::width( j = 3, width=2) %>% 
  flextable::width( j = 4, width=1.5) %>% 
  flextable::width( j = (3+2):ncol(lit_review_alt), width=0.33) %>%
  flextable::line_spacing( space = 0.5, part = "body") %>% #i=1:nrow(lit_review_alt),
  flextable::padding(padding = 0, part = "body") %>%
  #merge_v( j = 1,  part = "body", combine = T) %>%
  #merge_v( j = 2,  part = "body", combine = T) %>%
  #merge_h( i = 1:2,  part = "body") %>%
  
  merge_at(i = 4:7, j = 1:2, part = "body") %>%
  merge_at(i = 8:10, j = 1:2, part = "body") %>%
  merge_at(i = 11:15, j = 1:2, part = "body") %>%
  merge_at(i = 16:19, j = 1:2, part = "body") %>%
  
  merge_at(i = 20:n, j = 1, part = "body") %>%
  merge_at(i = 20:28, j = 2, part = "body") %>%
  merge_at(i = 29:n, j = 2, part = "body") %>%
  
  #merge_v( j = 1,  part = "body", combine = T) %>%
  
  #merge_at(i = NULL, j = NULL, part = "body") %>%
  #merge_at(i = NULL, j = NULL, part = "body") %>%
  
  flextable::rotate(j=1, rotation="tbrl",part="all") %>%
  flextable::rotate(j=2, rotation="tbrl",part="all") %>%
  flextable::width( j = 1:2, width=0.1)  %>%
  flextable::width( j = 3, width=2.5)  %>%
  flextable::width( j = 4, width=1.5)  %>%
  flextable::width( j = 5:12, width=0.25)  %>%
  ftExtra::colformat_md(j = 4, part="body")   #Make sure this goes last or it'll get overwritten by the colformat above
      

litreview_ft  %>% saveRDS(paste0(here::here(), '/replication_paper/tables/litreview_ft.Rds'))

litreview_ft

```

## PNAS Version

```{r, echo=FALSE, results='asis', include=T, cache=F, ft.arraystretch=0.75}

#https://davidgohel.github.io/flextable/reference/knit_print.flextable.html#chunk-options
# NOTE: If one of the citations is degenerate this will throw an error when knitting that is annoying to track down. You have to remove cite by cite to see which one it is.
set_flextable_defaults(fonts_ignore=TRUE)

lit_review_alt <- lit_review_pull%>% 
                  mutate(Literature =   paste0("[",Literature %>% str_replace("; {0,}$","") ,"]")) %>%
                  mutate(Concept= Concept %>% paste0(Literature)) %>%
                  mutate(Concept = ifelse(Concept=="N[NA]", "N", Concept) ) %>%
                  dplyr::select(-Codebook, -`Cameo Codes`, -`ICB Codes`, -Literature, -`ICB Corpus`) 
                  #dplyr::filter(is.na(group))


n=nrow(lit_review_alt)
ft <- NULL
ft <- lit_review_alt %>%
      flextable::as_flextable() %>%
      add_header( 
                  #"ICB Corpus"="Corpus",
                  "ICBe (ours)"="Events Datasets",
                  "Cameo"="Events Datasets",
                  "MIDs Incidents"="Events Datasets",
                  "UCDP-GED"="Events Datasets",
                  "ICB"="Episodes Datasets",
                  "COW"="Episodes Datasets",
                  "MIDs"="Episodes Datasets",
                  top = TRUE ) %>%

      set_header_labels(
        values = list("...1" = "" , "...2" = "" ) 
        ) %>%
      merge_h(part = "header") %>%
  
      #bg( i=1:(n) , j = condition, part = "body", bg = "#EFEFEF") %>%
      #bg( i=2 , j = condition, part = "header", bg = "#EFEFEF") %>%
      bg( i = which( 1:nrow(lit_review_alt) %% 2 == 1)  , j=3:ncol(lit_review_alt), part = "body", bg = "#EFEFEF") %>%
      #width(j = 1, width=1.25) %>%
      #width(j = 2:ncol(lit_review_alt), width=0.25) %>%
      flextable::fontsize(size = 7, part = "all") %>%
      flextable::rotate(i=2, rotation="tbrl",part="header") %>%
      #flextable::set_header_labels( values = list(x1 = "", x2 = "")) %>%
      flextable::align(align = "center", part = "body") %>%
      flextable::align(align = "center", part = "header")   %>%

      flextable::colformat_char(
          j = 1:ncol(lit_review_alt),
          na_str = "",
          prefix = "",
          suffix = ""
      ) %>%

      #hline(i=c(1), j=3:ncol(lit_review_alt),  border = NULL, part = "header") %>%
      hline(i=c(2,3,7,10,15, 19, 27), border = NULL, part = "body") %>% #,10,14, 20,27,37, n

      #set_table_properties(layout="autofit")  %>%
      vline( i = 1:2, j = c(3,7,10), border = NULL, part = "header") %>%
      vline( i = 1:(n), j = 1:2, border = NULL, part = "body")  %>%
      vline( i = 1:(n), j = c(3,7,10), border = NULL, part = "body") 
  
      #autofit()
      #fit_to_width(max_width=12) #This is crazy slow
      #flextable::autofit() 
      #set_table_properties(width = 1, layout = "autofit")

#https://cran.r-project.org/web/packages/ftExtra/vignettes/format_columns.html

litreview_ft_pnas <- ft %>% 
  flextable::width( j = 3, width=4) %>% 
  flextable::width( j = (4):ncol(lit_review_alt), width=0.25) %>%
  flextable::line_spacing( space = 0.5, part = "body") %>% #i=1:nrow(lit_review_alt),
  flextable::padding(padding = 0, part = "body") %>%
  #merge_v( j = 1,  part = "body", combine = T) %>%
  #merge_v( j = 2,  part = "body", combine = T) %>%
  #merge_h( i = 1:2,  part = "body") %>%
  
  merge_at(i = 4:7, j = 1:2, part = "body") %>%
  merge_at(i = 8:10, j = 1:2, part = "body") %>%
  merge_at(i = 11:15, j = 1:2, part = "body") %>%
  merge_at(i = 16:19, j = 1:2, part = "body") %>%
  
  merge_at(i = 20:n, j = 1, part = "body") %>%
  merge_at(i = 20:28, j = 2, part = "body") %>%
  merge_at(i = 29:n, j = 2, part = "body") %>%
  
  #hline(i=c(27), border = NULL, part = "body")  %>% #After the merge we have to put this hline back in  on second thought that doesn't put it back either

  #merge_v( j = 1,  part = "body", combine = T) %>%
  
  #merge_at(i = NULL, j = NULL, part = "body") %>%
  #merge_at(i = NULL, j = NULL, part = "body") %>%
  
  flextable::rotate(j=1, rotation="tbrl",part="all") %>%
  flextable::rotate(j=2, rotation="tbrl",part="all") %>%
  flextable::width( j = 1:2, width=0.1)  %>%
  ftExtra::colformat_md(j = 3, part="body")   #Make sure this goes last or it'll get overwritten by the colformat above
      

litreview_ft_pnas  %>% saveRDS(paste0(here::here(), '/replication_paper/tables/litreview_ft_pnas.Rds'))

litreview_ft_pnas

```


```{r, eval=F}

#For the website I think
n=nrow(lit_review_alt)
ft <- NULL
temp <- lit_review_alt[,-c(4,5)]
ft <- temp %>% 
      flextable::as_flextable() %>%

      bg( i = which( 1:nrow(temp) %% 2 == 1)  , j=3:ncol(temp), part = "body", bg = "#EFEFEF") %>%
      flextable::fontsize(size = 7, part = "all") %>%
      flextable::align(align = "center", part = "body") %>%
      flextable::align(align = "center", part = "header")   %>%

      flextable::colformat_char(
          j = 1:ncol(temp),
          na_str = "",
          prefix = "",
          suffix = ""
      ) %>%
        set_header_labels(
        values = list("...1" = "" , "...2" = "" ) 
        ) %>%
      merge_h(part = "header") %>%
  

      hline(i=c(1), j=3:ncol(temp),  border = NULL, part = "header") %>%
      hline(i=c(2,3,7,10,15, 19, 27), border = NULL, part = "body") %>% 
      vline( i = 1:(n), j = 1:2, border = NULL, part = "body")  %>%
      vline( i = 1:(n), j = c(0,4)+3, border = NULL, part = "body") %>%
      flextable::width( j = 3, width=3) %>%
      flextable::line_spacing( space = 0.75, part = "body") %>% 
      flextable::padding(padding = 0, part = "body") %>%

      merge_at(i = 4:7, j = 1:2, part = "body") %>%
      merge_at(i = 8:10, j = 1:2, part = "body") %>%
      merge_at(i = 11:15, j = 1:2, part = "body") %>%
      merge_at(i = 16:19, j = 1:2, part = "body") %>%
      
      merge_at(i = 20:n, j = 1, part = "body") %>%
      merge_at(i = 20:28, j = 2, part = "body") %>%
      merge_at(i = 29:n, j = 2, part = "body") %>%
      flextable::rotate(j=1, rotation="tbrl",part="all") %>%
      flextable::rotate(j=2, rotation="tbrl",part="all") %>%
      flextable::width( j = 1:2, width=0.1)  %>%
      flextable::width( j = 3, width=4)  %>%
      flextable::width( j = 4:ncol(temp), width=0.25) 
  




```
