---
title: "CaseStudy426.Rmd"
output: html_document
---

```{r, echo=F, results='asis', message=F, warning=F, eval=T , cache=F}

library(pacman)
p_load(flextable)
p_load(ftExtra)
p_load(googlesheets4)
library(googlesheets4)

```

```{r, echo=F, results='asis', message=F, warning=F, eval=T , cache=F}

CaseStudy426 <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1lnFqrnCwjWWd_rdWLVHGkxSEcFpw-5XrV7MiQ6rA7KY/edit?usp=sharing", sheet="CaseStudy426")

```


```{r, echo=FALSE, results='asis', include=T, cache=F, ft.arraystretch=0.75}

#https://davidgohel.github.io/flextable/reference/knit_print.flextable.html#chunk-options
# NOTE: If one of the citations is degenerate this will thow an error when knitting that is annoying to track down. You have to remove cite by cite to see which one it is.
set_flextable_defaults(fonts_ignore=TRUE)

n=nrow(CaseStudy426)
CaseStudy426_ft <- NULL
CaseStudy426_ft <- CaseStudy426 %>%
      flextable::as_flextable() %>%
      add_header( 
                  "Actor(s)"="Ground Truth",
                  "Event"="Ground Truth",
                  "Date"="Ground Truth",
                  "ICBe (us)"="Events",
                  "Phoenix"="Events",
                  "Terrier"="Events",
                  "ICEWS"="Events",
                  "MIDs Incidents"="Events",
                  "MIDs"="Episodes",
                  "ICB Dyadic"="Episodes",
                  top = TRUE ) %>%

      #set_header_labels(
      #  values = list("...1" = "" , "...2" = "" ) 
      #  ) %>%
      merge_h(part = "header") %>%
  
      #bg( i=1:(n) , j = condition, part = "body", bg = "#EFEFEF") %>%
      #bg( i=2 , j = condition, part = "header", bg = "#EFEFEF") %>%
      bg( i = which( 1:nrow(CaseStudy426) %% 2 == 1)  , j=1:ncol(CaseStudy426), part = "body", bg = "#EFEFEF") %>%
      #width(j = 1, width=1.25) %>%
      #width(j = 2:ncol(lit_review_alt), width=0.25) %>%
      flextable::fontsize(size = 7, part = "all") %>%
      #flextable::rotate(i=2, rotation="tbrl",part="header") %>%
      #flextable::set_header_labels( values = list(x1 = "", x2 = "")) %>%
      flextable::align(align = "center", part = "body") %>%
      flextable::align(align = "center", part = "header")   %>%

      flextable::colformat_char(
          j = 1:ncol(CaseStudy426),
          na_str = "",
          prefix = "",
          suffix = ""
      ) %>%

      #hline(i=c(1), j=3:ncol(lit_review_alt),  border = NULL, part = "header") %>%
      #hline(i=c(2,3,7,10,15, 19, 27), border = NULL, part = "body") %>% #,10,14, 20,27,37, n

      #set_table_properties(layout="autofit")  %>%
      #vline( i = 1:2, j = c(1,2,3,7)+2, border = NULL, part = "header") %>%
      vline( i = 1:2, j = c(3,8), border = NULL, part = "header")  %>%
      vline( i = 1:(n), j = c(3,8), border = NULL, part = "body")
      
      #autofit()
      #fit_to_width(max_width=12) #This is crazy slow
      #flextable::autofit() 
      #set_table_properties(width = 1, layout = "autofit")

#https://cran.r-project.org/web/packages/ftExtra/vignettes/format_columns.html

CaseStudy426_ft  %>% saveRDS(paste0(here::here(), '/paper/tables/CaseStudy426_ft.Rds'))

CaseStudy426_ft 

```
