---
title: "Example Sentence Coding"
output: html_document
---


```{r, echo=F, results='asis', message=F, warning=F, eval=T , cache=F}
library(pacman)
p_load(igraph)
p_load(tidyverse)
p_load(flextable)
p_load(ftExtra)
p_load(googlesheets4)
library(googlesheets4)

```



```{r, echo=F, results='asis', message=F, warning=F, eval=T , cache=F}
sentence_example_sheet <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/10tZGzjYgmvrbgQTV3oadVEV8m1LxLEDJEq9pzqq90Fc/edit?usp=sharing",
                                                    sheet="Sentence Tree Example Table")

```

```{r, echo=FALSE, results='asis', include=T, cache=F, ft.arraystretch=1}

sentence="'A crisis began for the Soviet Union, when the United States threatened to invade Cuba unless nuclear weapons were removed from its soil.'"

set_flextable_defaults(fonts_ignore=TRUE)

full_tree_ft <- sentence_example_sheet %>%
      flextable::flextable() %>%
      add_header( "x1"=sentence,
                  "x2"=sentence,
                  "x3"=sentence,
                  #"x7"=sentence,
                  #"x8"=sentence,
                  #"x9"=sentence,
                  #"x10"=sentence,
                  top = TRUE ) %>%
      merge_h(part = "header") %>%
      flextable::width( j = 1, width=1) %>%
      flextable::fontsize(size = 7, part = "body") %>%
      merge_v( j = 1,  part = "body", combine = T) %>%
      #flextable::width( j = 1, width=.11) %>%
      flextable::width( j = 2, width=1.5) %>%
      flextable::width( j = 3, width=4) %>%
      valign(j = 1, valign = "top", part = "body") %>%
      flextable::line_spacing( space = 1, part = "body") #%>% #i=1:nrow(lit_review_alt),
      #flextable::padding(padding = 0, part = "body") 
  
full_tree_ft


```
