---
title: 'Appendix 1: ICB Crises and Summary Information'
site: bookdown::bookdown_site
bibliography: ../ICBintro.bib
output: 
  rticles::arxiv_article:
    keep_tex: true
header-includes:
  - \usepackage[utf8]{inputenc}
  - \usepackage{pifont}
  - \usepackage{newunicodechar}
  - \newunicodechar{✓}{\ding{51}}
  - \newunicodechar{✗}{\ding{55}}
  - \usepackage{array}
  - \usepackage{ctable} # added for demo
  - \usepackage{natbib} #added for latex citation within huxtable
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{makecell}
  - \usepackage{titlesec}
  - \usepackage[parfill]{parskip}
  - \usepackage{makecell}
  - \usepackage{graphicx}
  - \usepackage{caption}
  - \usepackage[capposition=top]{floatrow}
  - \titleformat{\subsubsection}{\normalfont\normalsize\itshape}{\thesubsubsection}{1em}{}
  - \titlespacing*{\subsubsection}{0pt}{3.25ex plus 1ex minus .2ex}{0ex plus .2ex}
  - \DeclareUnicodeCharacter{00A0}{ }
  - \usepackage{setspace}
  - \usepackage{cellspace}
  - \setlength\cellspacetoplimit{0.8ex}
  - \renewcommand{\arraystretch}{0.8}
  - \AtBeginEnvironment{tabular}{\singlespacing}
  - \AtBeginEnvironment{lltable}{\singlespacing}
---


```{r, echo=F, results='asis', message=F, warning=F, eval=T , cache=F}
library(pacman)

library(flextable)
library(ftExtra)
library(tidyverse)

knitr::opts_chunk$set(echo=F, cache=TRUE, messages=F, results='hide', warnings=F, include=FALSE) #fig.width = 8, fig.height = 8, message=F, warning=F, , results=F


```

```{r}
#Load original icb data

icb_crises <- read_csv(file=paste0(here::here(), "/replication_paper/data/in/icb1v14.csv")) %>% janitor::clean_names() #somehow break of all things is a broken name
icb_actors <- read_csv(file=paste0(here::here(), "/replication_paper/data/in/icb2v14.csv"))

```


```{r}

#Select and recode our questions and answer

icb_recodes <- data.frame(
  stringsAsFactors = FALSE,
                              var = c("BREAK","BREAK","BREAK","BREAK","BREAK",
                                      "BREAK","BREAK","BREAK","BREAK",
                                      "BREAK","CENVIOSY","CENVIOSY","CENVIOSY",
                                      "CENVIOSY","CENVIOSY","CENVIOSY",
                                      "CHACTS","CHACTS","CHACTS","CHACTS","CHACTS",
                                      "CHACTS","CHACTS","CHALL","CHALL",
                                      "CHALL","CHALL","CHALL","CHALL","CHALL",
                                      "CRISMG","CRISMG","CRISMG","CRISMG",
                                      "CRISMG","CRISMG","CRISMG","CRISMG",
                                      "CRISMG","CRISMG","ETHCONF","ETHCONF",
                                      "ETHCONF","ETHCONF","ETHCONF","ETHCONF",
                                      "ETHNIC","ETHNIC","ETHNIC","ETHNIC",
                                      "ETHNIC","EXSAT","EXSAT","EXSAT","EXSAT",
                                      "EXSAT","EXSAT","EXSAT","EXSAT",
                                      "EXSAT","FOROUT","FOROUT","FOROUT","FOROUT",
                                      "FOROUT","FOROUT","FOROUT","FOROUT",
                                      "FOROUT","GLOBACTM","GLOBACTM",
                                      "GLOBACTM","GLOBACTM","GLOBACTM","GLOBACTM",
                                      "GLOBACTM","GLOBACTM","GLOBACTM",
                                      "GLOBACTM","GLOBACTM","GLOBACTM","GLOBACTM",
                                      "GLOBACTM","GLOBACTM","GLOBACTM",
                                      "GLOBEFCT","GLOBEFCT","GLOBEFCT","GLOBEFCT",
                                      "GLOBEFCT","GLOBEFCT","GLOBEFCT",
                                      "GLOBEFCT","GLOBEFCT","GLOBORG","GLOBORG",
                                      "GLOBORG","GLOBORG","GLOBORG","GLOBORG",
                                      "GLOBORG","GLOBORG","GRAVCR","GRAVCR",
                                      "GRAVCR","GRAVCR","GRAVCR","GRAVCR",
                                      "GRAVCR","GRAVCR","GRAVCR","GRAVCR",
                                      "HETERO","HETERO","HETERO","HETERO","HETERO",
                                      "HETERO","HETERO","ISSUES","ISSUES",
                                      "ISSUES","ISSUES","ISSUES","ISSUES",
                                      "ISSUES","MEDIATE","MEDIATE","MEDIATE",
                                      "MEDIATE","MEDIATE","MEDIATE","OUTESR",
                                      "OUTESR","OUTESR","OUTESR","OUTESR",
                                      "POWCH","POWCH","POWCH","POWCH","POWCH",
                                      "POWCH","POWCH","REGACTMB","REGACTMB",
                                      "REGACTMB","REGACTMB","REGACTMB",
                                      "REGACTMB","REGACTMB","REGACTMB","REGACTMB",
                                      "REGACTMB","REGACTMB","REGACTMB",
                                      "REGACTMB","REGACTMB","REGACTMB","REGACTMB",
                                      "REGORG","REGORG","REGORG","REGORG",
                                      "REGORG","REGORG","REGORG","REGORG",
                                      "REGORG","REGORG","REGORG","REGORG",
                                      "REGORG","REGORG","ROEFCT","ROEFCT","ROEFCT",
                                      "ROEFCT","ROEFCT","ROEFCT","ROEFCT",
                                      "ROEFCT","ROEFCT","RUGACH","RUGACH",
                                      "RUGACH","RUGACH","RUGACH","RUGACH",
                                      "RUGACH","SEVVIOSY","SEVVIOSY","SEVVIOSY",
                                      "SEVVIOSY","SEVVIOSY","SEVVIOSY",
                                      "SOGLACT","SOGLACT","SOGLACT","SOGLACT",
                                      "SOGLACT","SOGLACT","SOGLACT","SOGLACT",
                                      "SOGLACT","SOGLACT","SORACT","SORACT",
                                      "SORACT","SORACT","SORACT","SORACT",
                                      "SORACT","SORACT","SORACT","SORACT",
                                      "SOURDT","SOURDT","SOURDT","SOURDT","SOURDT",
                                      "SOURDT","SOURDT","SOURDT","SOURDT",
                                      "SUBOUT","SUBOUT","SUBOUT","SUBOUT",
                                      "SUEFAC","SUEFAC","SUEFAC","SUEFAC",
                                      "SUEFAC","SUEFAC","SUEFAC","SUEFCT",
                                      "SUEFCT","SUEFCT","SUEFCT","SUEFCT","SUEFCT",
                                      "SUEFCT","SUEFCT","SUINV","SUINV",
                                      "SUINV","SUINV","SUINV","SUINV","SUPACE",
                                      "SUPACE","SUPACE","SUPACE","SUPACE",
                                      "SUPACE","USEFAC","USEFAC","USEFAC",
                                      "USEFAC","USEFAC","USEFAC","USEFAC",
                                      "USEFCT","USEFCT","USEFCT","USEFCT",
                                      "USEFCT","USEFCT","USEFCT","USEFCT","USINV",
                                      "USINV","USINV","USINV","USINV",
                                      "USINV","USPACE","USPACE","USPACE","USPACE",
                                      "USPACE","USPACE","VIOL","VIOL",
                                      "VIOL","VIOL","VIOL","VIOL","TIMVIO",
                                      "TIMVIO","TIMVIO","TIMVIO","TIMVIO"),
                      description = c("BREAK: BREAKPOINT (TRIGGER) TO INTERNATIONAL CRISIS",
                                      "BREAK: BREAKPOINT (TRIGGER) TO INTERNATIONAL CRISIS",
                                      "BREAK: BREAKPOINT (TRIGGER) TO INTERNATIONAL CRISIS",
                                      "BREAK: BREAKPOINT (TRIGGER) TO INTERNATIONAL CRISIS",
                                      "BREAK: BREAKPOINT (TRIGGER) TO INTERNATIONAL CRISIS",
                                      "BREAK: BREAKPOINT (TRIGGER) TO INTERNATIONAL CRISIS",
                                      "BREAK: BREAKPOINT (TRIGGER) TO INTERNATIONAL CRISIS",
                                      "BREAK: BREAKPOINT (TRIGGER) TO INTERNATIONAL CRISIS",
                                      "BREAK: BREAKPOINT (TRIGGER) TO INTERNATIONAL CRISIS",
                                      "BREAK: BREAKPOINT (TRIGGER) TO INTERNATIONAL CRISIS","CENVIOSY: CENTRALITY OF VIOLENCE",
                                      "CENVIOSY: CENTRALITY OF VIOLENCE",
                                      "CENVIOSY: CENTRALITY OF VIOLENCE",
                                      "CENVIOSY: CENTRALITY OF VIOLENCE",
                                      "CENVIOSY: CENTRALITY OF VIOLENCE",
                                      "CENVIOSY: CENTRALITY OF VIOLENCE","CHACTS: CHANGE IN ACTORS",
                                      "CHACTS: CHANGE IN ACTORS",
                                      "CHACTS: CHANGE IN ACTORS","CHACTS: CHANGE IN ACTORS",
                                      "CHACTS: CHANGE IN ACTORS",
                                      "CHACTS: CHANGE IN ACTORS","CHACTS: CHANGE IN ACTORS",
                                      "CHALL: CHANGE IN ALLIANCE CONFIGURATION",
                                      "CHALL: CHANGE IN ALLIANCE CONFIGURATION",
                                      "CHALL: CHANGE IN ALLIANCE CONFIGURATION",
                                      "CHALL: CHANGE IN ALLIANCE CONFIGURATION",
                                      "CHALL: CHANGE IN ALLIANCE CONFIGURATION",
                                      "CHALL: CHANGE IN ALLIANCE CONFIGURATION",
                                      "CHALL: CHANGE IN ALLIANCE CONFIGURATION",
                                      "CRISMG: CRISIS MANAGEMENT TECHNIQUE",
                                      "CRISMG: CRISIS MANAGEMENT TECHNIQUE",
                                      "CRISMG: CRISIS MANAGEMENT TECHNIQUE",
                                      "CRISMG: CRISIS MANAGEMENT TECHNIQUE",
                                      "CRISMG: CRISIS MANAGEMENT TECHNIQUE",
                                      "CRISMG: CRISIS MANAGEMENT TECHNIQUE",
                                      "CRISMG: CRISIS MANAGEMENT TECHNIQUE",
                                      "CRISMG: CRISIS MANAGEMENT TECHNIQUE",
                                      "CRISMG: CRISIS MANAGEMENT TECHNIQUE",
                                      "CRISMG: CRISIS MANAGEMENT TECHNIQUE","ETHCONF: ETHNIC CONFLICT",
                                      "ETHCONF: ETHNIC CONFLICT",
                                      "ETHCONF: ETHNIC CONFLICT","ETHCONF: ETHNIC CONFLICT",
                                      "ETHCONF: ETHNIC CONFLICT",
                                      "ETHCONF: ETHNIC CONFLICT","ETHNIC: ETHNICITY",
                                      "ETHNIC: ETHNICITY","ETHNIC: ETHNICITY",
                                      "ETHNIC: ETHNICITY","ETHNIC: ETHNICITY",
                                      "EXSAT: EXTENT OF SATISFACTION ABOUT OUTCOME",
                                      "EXSAT: EXTENT OF SATISFACTION ABOUT OUTCOME",
                                      "EXSAT: EXTENT OF SATISFACTION ABOUT OUTCOME",
                                      "EXSAT: EXTENT OF SATISFACTION ABOUT OUTCOME",
                                      "EXSAT: EXTENT OF SATISFACTION ABOUT OUTCOME",
                                      "EXSAT: EXTENT OF SATISFACTION ABOUT OUTCOME",
                                      "EXSAT: EXTENT OF SATISFACTION ABOUT OUTCOME",
                                      "EXSAT: EXTENT OF SATISFACTION ABOUT OUTCOME",
                                      "EXSAT: EXTENT OF SATISFACTION ABOUT OUTCOME",
                                      "FOROUT: FORM OF OUTCOME",
                                      "FOROUT: FORM OF OUTCOME","FOROUT: FORM OF OUTCOME",
                                      "FOROUT: FORM OF OUTCOME",
                                      "FOROUT: FORM OF OUTCOME","FOROUT: FORM OF OUTCOME",
                                      "FOROUT: FORM OF OUTCOME","FOROUT: FORM OF OUTCOME",
                                      "FOROUT: FORM OF OUTCOME",
                                      "GLOBACTM: CONTENT OF GLOBAL ORGANIZATION INVOLVEMENT",
                                      "GLOBACTM: CONTENT OF GLOBAL ORGANIZATION INVOLVEMENT",
                                      "GLOBACTM: CONTENT OF GLOBAL ORGANIZATION INVOLVEMENT",
                                      "GLOBACTM: CONTENT OF GLOBAL ORGANIZATION INVOLVEMENT",
                                      "GLOBACTM: CONTENT OF GLOBAL ORGANIZATION INVOLVEMENT",
                                      "GLOBACTM: CONTENT OF GLOBAL ORGANIZATION INVOLVEMENT",
                                      "GLOBACTM: CONTENT OF GLOBAL ORGANIZATION INVOLVEMENT",
                                      "GLOBACTM: CONTENT OF GLOBAL ORGANIZATION INVOLVEMENT",
                                      "GLOBACTM: CONTENT OF GLOBAL ORGANIZATION INVOLVEMENT",
                                      "GLOBACTM: CONTENT OF GLOBAL ORGANIZATION INVOLVEMENT",
                                      "GLOBACTM: CONTENT OF GLOBAL ORGANIZATION INVOLVEMENT",
                                      "GLOBACTM: CONTENT OF GLOBAL ORGANIZATION INVOLVEMENT",
                                      "GLOBACTM: CONTENT OF GLOBAL ORGANIZATION INVOLVEMENT",
                                      "GLOBACTM: CONTENT OF GLOBAL ORGANIZATION INVOLVEMENT",
                                      "GLOBACTM: CONTENT OF GLOBAL ORGANIZATION INVOLVEMENT",
                                      "GLOBACTM: CONTENT OF GLOBAL ORGANIZATION INVOLVEMENT",
                                      "GLOBEFAC: MOST EFFECTIVE GLOBAL ORGANIZATION INVOLVEMENT",
                                      "GLOBEFAC: MOST EFFECTIVE GLOBAL ORGANIZATION INVOLVEMENT",
                                      "GLOBEFAC: MOST EFFECTIVE GLOBAL ORGANIZATION INVOLVEMENT",
                                      "GLOBEFAC: MOST EFFECTIVE GLOBAL ORGANIZATION INVOLVEMENT",
                                      "GLOBEFAC: MOST EFFECTIVE GLOBAL ORGANIZATION INVOLVEMENT",
                                      "GLOBEFAC: MOST EFFECTIVE GLOBAL ORGANIZATION INVOLVEMENT",
                                      "GLOBEFAC: MOST EFFECTIVE GLOBAL ORGANIZATION INVOLVEMENT",
                                      "GLOBEFAC: MOST EFFECTIVE GLOBAL ORGANIZATION INVOLVEMENT",
                                      "GLOBEFAC: MOST EFFECTIVE GLOBAL ORGANIZATION INVOLVEMENT",
                                      "GLOBORG: GLOBAL ORGANIZATION ORGAN MOST ACTIVE IN CRISIS",
                                      "GLOBORG: GLOBAL ORGANIZATION ORGAN MOST ACTIVE IN CRISIS",
                                      "GLOBORG: GLOBAL ORGANIZATION ORGAN MOST ACTIVE IN CRISIS",
                                      "GLOBORG: GLOBAL ORGANIZATION ORGAN MOST ACTIVE IN CRISIS",
                                      "GLOBORG: GLOBAL ORGANIZATION ORGAN MOST ACTIVE IN CRISIS",
                                      "GLOBORG: GLOBAL ORGANIZATION ORGAN MOST ACTIVE IN CRISIS",
                                      "GLOBORG: GLOBAL ORGANIZATION ORGAN MOST ACTIVE IN CRISIS",
                                      "GLOBORG: GLOBAL ORGANIZATION ORGAN MOST ACTIVE IN CRISIS",
                                      "GRAVCR: GRAVITY OF VALUE THREATENED",
                                      "GRAVCR: GRAVITY OF VALUE THREATENED",
                                      "GRAVCR: GRAVITY OF VALUE THREATENED","GRAVCR: GRAVITY OF VALUE THREATENED",
                                      "GRAVCR: GRAVITY OF VALUE THREATENED",
                                      "GRAVCR: GRAVITY OF VALUE THREATENED",
                                      "GRAVCR: GRAVITY OF VALUE THREATENED",
                                      "GRAVCR: GRAVITY OF VALUE THREATENED",
                                      "GRAVCR: GRAVITY OF VALUE THREATENED",
                                      "GRAVCR: GRAVITY OF VALUE THREATENED",
                                      "HETERO: HETEROGENEITY","HETERO: HETEROGENEITY",
                                      "HETERO: HETEROGENEITY","HETERO: HETEROGENEITY",
                                      "HETERO: HETEROGENEITY",
                                      "HETERO: HETEROGENEITY","HETERO: HETEROGENEITY",
                                      "ISSUES: ISSUES","ISSUES: ISSUES","ISSUES: ISSUES",
                                      "ISSUES: ISSUES","ISSUES: ISSUES",
                                      "ISSUES: ISSUES","ISSUES: ISSUES",
                                      "MEDIATE: DID MEDIATION OCCUR",
                                      "MEDIATE: DID MEDIATION OCCUR","MEDIATE: DID MEDIATION OCCUR",
                                      "MEDIATE: DID MEDIATION OCCUR",
                                      "MEDIATE: DID MEDIATION OCCUR",
                                      "MEDIATE: DID MEDIATION OCCUR",
                                      "OUTESR: ESCALATION OR REDUCTION OF TENSION",
                                      "OUTESR: ESCALATION OR REDUCTION OF TENSION",
                                      "OUTESR: ESCALATION OR REDUCTION OF TENSION",
                                      "OUTESR: ESCALATION OR REDUCTION OF TENSION",
                                      "OUTESR: ESCALATION OR REDUCTION OF TENSION",
                                      "POWCH: CHANGE IN DISTRIBUTION OF POWER",
                                      "POWCH: CHANGE IN DISTRIBUTION OF POWER",
                                      "POWCH: CHANGE IN DISTRIBUTION OF POWER",
                                      "POWCH: CHANGE IN DISTRIBUTION OF POWER",
                                      "POWCH: CHANGE IN DISTRIBUTION OF POWER",
                                      "POWCH: CHANGE IN DISTRIBUTION OF POWER",
                                      "POWCH: CHANGE IN DISTRIBUTION OF POWER",
                                      "REGACTMB: CONTENT OF REGIONAL-SECURITY ORGANIZATION INVOLVEMENT",
                                      "REGACTMB: CONTENT OF REGIONAL-SECURITY ORGANIZATION INVOLVEMENT",
                                      "REGACTMB: CONTENT OF REGIONAL-SECURITY ORGANIZATION INVOLVEMENT",
                                      "REGACTMB: CONTENT OF REGIONAL-SECURITY ORGANIZATION INVOLVEMENT",
                                      "REGACTMB: CONTENT OF REGIONAL-SECURITY ORGANIZATION INVOLVEMENT",
                                      "REGACTMB: CONTENT OF REGIONAL-SECURITY ORGANIZATION INVOLVEMENT",
                                      "REGACTMB: CONTENT OF REGIONAL-SECURITY ORGANIZATION INVOLVEMENT",
                                      "REGACTMB: CONTENT OF REGIONAL-SECURITY ORGANIZATION INVOLVEMENT",
                                      "REGACTMB: CONTENT OF REGIONAL-SECURITY ORGANIZATION INVOLVEMENT",
                                      "REGACTMB: CONTENT OF REGIONAL-SECURITY ORGANIZATION INVOLVEMENT",
                                      "REGACTMB: CONTENT OF REGIONAL-SECURITY ORGANIZATION INVOLVEMENT",
                                      "REGACTMB: CONTENT OF REGIONAL-SECURITY ORGANIZATION INVOLVEMENT",
                                      "REGACTMB: CONTENT OF REGIONAL-SECURITY ORGANIZATION INVOLVEMENT",
                                      "REGACTMB: CONTENT OF REGIONAL-SECURITY ORGANIZATION INVOLVEMENT",
                                      "REGACTMB: CONTENT OF REGIONAL-SECURITY ORGANIZATION INVOLVEMENT",
                                      "REGACTMB: CONTENT OF REGIONAL-SECURITY ORGANIZATION INVOLVEMENT",
                                      "REGIONAL-SECURITY ORGANIZATION MOST ACTIVE IN CRISIS",
                                      "REGIONAL-SECURITY ORGANIZATION MOST ACTIVE IN CRISIS",
                                      "REGIONAL-SECURITY ORGANIZATION MOST ACTIVE IN CRISIS",
                                      "REGIONAL-SECURITY ORGANIZATION MOST ACTIVE IN CRISIS",
                                      "REGIONAL-SECURITY ORGANIZATION MOST ACTIVE IN CRISIS",
                                      "REGIONAL-SECURITY ORGANIZATION MOST ACTIVE IN CRISIS",
                                      "REGIONAL-SECURITY ORGANIZATION MOST ACTIVE IN CRISIS",
                                      "REGIONAL-SECURITY ORGANIZATION MOST ACTIVE IN CRISIS",
                                      "REGIONAL-SECURITY ORGANIZATION MOST ACTIVE IN CRISIS",
                                      "REGIONAL-SECURITY ORGANIZATION MOST ACTIVE IN CRISIS",
                                      "REGIONAL-SECURITY ORGANIZATION MOST ACTIVE IN CRISIS",
                                      "REGIONAL-SECURITY ORGANIZATION MOST ACTIVE IN CRISIS",
                                      "REGIONAL-SECURITY ORGANIZATION MOST ACTIVE IN CRISIS",
                                      "REGIONAL-SECURITY ORGANIZATION MOST ACTIVE IN CRISIS",
                                      "ROEFCT: EFFECTIVENESS OF REGIONAL-SECURITY ORGANIZATION INVOLVEMENT",
                                      "ROEFCT: EFFECTIVENESS OF REGIONAL-SECURITY ORGANIZATION INVOLVEMENT",
                                      "ROEFCT: EFFECTIVENESS OF REGIONAL-SECURITY ORGANIZATION INVOLVEMENT",
                                      "ROEFCT: EFFECTIVENESS OF REGIONAL-SECURITY ORGANIZATION INVOLVEMENT",
                                      "ROEFCT: EFFECTIVENESS OF REGIONAL-SECURITY ORGANIZATION INVOLVEMENT",
                                      "ROEFCT: EFFECTIVENESS OF REGIONAL-SECURITY ORGANIZATION INVOLVEMENT",
                                      "ROEFCT: EFFECTIVENESS OF REGIONAL-SECURITY ORGANIZATION INVOLVEMENT",
                                      "ROEFCT: EFFECTIVENESS OF REGIONAL-SECURITY ORGANIZATION INVOLVEMENT",
                                      "ROEFCT: EFFECTIVENESS OF REGIONAL-SECURITY ORGANIZATION INVOLVEMENT",
                                      "RUGACH: CHANGE IN RULES OF THE GAME",
                                      "RUGACH: CHANGE IN RULES OF THE GAME","RUGACH: CHANGE IN RULES OF THE GAME",
                                      "RUGACH: CHANGE IN RULES OF THE GAME",
                                      "RUGACH: CHANGE IN RULES OF THE GAME",
                                      "RUGACH: CHANGE IN RULES OF THE GAME",
                                      "RUGACH: CHANGE IN RULES OF THE GAME",
                                      "SEVVIOSY: INTENSITY OF VIOLENCE",
                                      "SEVVIOSY: INTENSITY OF VIOLENCE",
                                      "SEVVIOSY: INTENSITY OF VIOLENCE","SEVVIOSY: INTENSITY OF VIOLENCE",
                                      "SEVVIOSY: INTENSITY OF VIOLENCE",
                                      "SEVVIOSY: INTENSITY OF VIOLENCE",
                                      "SOGLACT: SOURCE OF GLOBAL ORGANIZATION INVOLVEMENT",
                                      "SOGLACT: SOURCE OF GLOBAL ORGANIZATION INVOLVEMENT",
                                      "SOGLACT: SOURCE OF GLOBAL ORGANIZATION INVOLVEMENT",
                                      "SOGLACT: SOURCE OF GLOBAL ORGANIZATION INVOLVEMENT",
                                      "SOGLACT: SOURCE OF GLOBAL ORGANIZATION INVOLVEMENT",
                                      "SOGLACT: SOURCE OF GLOBAL ORGANIZATION INVOLVEMENT",
                                      "SOGLACT: SOURCE OF GLOBAL ORGANIZATION INVOLVEMENT",
                                      "SOGLACT: SOURCE OF GLOBAL ORGANIZATION INVOLVEMENT",
                                      "SOGLACT: SOURCE OF GLOBAL ORGANIZATION INVOLVEMENT",
                                      "SOGLACT: SOURCE OF GLOBAL ORGANIZATION INVOLVEMENT",
                                      "SORACT: SOURCE OF REGIONAL-SECURITY ORGANIZATION INVOLVEMENT",
                                      "SORACT: SOURCE OF REGIONAL-SECURITY ORGANIZATION INVOLVEMENT",
                                      "SORACT: SOURCE OF REGIONAL-SECURITY ORGANIZATION INVOLVEMENT",
                                      "SORACT: SOURCE OF REGIONAL-SECURITY ORGANIZATION INVOLVEMENT",
                                      "SORACT: SOURCE OF REGIONAL-SECURITY ORGANIZATION INVOLVEMENT",
                                      "SORACT: SOURCE OF REGIONAL-SECURITY ORGANIZATION INVOLVEMENT",
                                      "SORACT: SOURCE OF REGIONAL-SECURITY ORGANIZATION INVOLVEMENT",
                                      "SORACT: SOURCE OF REGIONAL-SECURITY ORGANIZATION INVOLVEMENT",
                                      "SORACT: SOURCE OF REGIONAL-SECURITY ORGANIZATION INVOLVEMENT",
                                      "SORACT: SOURCE OF REGIONAL-SECURITY ORGANIZATION INVOLVEMENT",
                                      "SOURDT: SOURCES USED FOR CODING DATA",
                                      "SOURDT: SOURCES USED FOR CODING DATA",
                                      "SOURDT: SOURCES USED FOR CODING DATA",
                                      "SOURDT: SOURCES USED FOR CODING DATA",
                                      "SOURDT: SOURCES USED FOR CODING DATA",
                                      "SOURDT: SOURCES USED FOR CODING DATA",
                                      "SOURDT: SOURCES USED FOR CODING DATA",
                                      "SOURDT: SOURCES USED FOR CODING DATA",
                                      "SOURDT: SOURCES USED FOR CODING DATA",
                                      "SUBOUT: CONTENT OF OUTCOME","SUBOUT: CONTENT OF OUTCOME",
                                      "SUBOUT: CONTENT OF OUTCOME",
                                      "SUBOUT: CONTENT OF OUTCOME",
                                      "SUEFAC: MOST EFFECTIVE USSR ACTIVITY",
                                      "SUEFAC: MOST EFFECTIVE USSR ACTIVITY",
                                      "SUEFAC: MOST EFFECTIVE USSR ACTIVITY","SUEFAC: MOST EFFECTIVE USSR ACTIVITY",
                                      "SUEFAC: MOST EFFECTIVE USSR ACTIVITY",
                                      "SUEFAC: MOST EFFECTIVE USSR ACTIVITY",
                                      "SUEFAC: MOST EFFECTIVE USSR ACTIVITY",
                                      "SUEFCT: EFFECTIVENESS OF USSR ACTIVITY",
                                      "SUEFCT: EFFECTIVENESS OF USSR ACTIVITY",
                                      "SUEFCT: EFFECTIVENESS OF USSR ACTIVITY",
                                      "SUEFCT: EFFECTIVENESS OF USSR ACTIVITY",
                                      "SUEFCT: EFFECTIVENESS OF USSR ACTIVITY",
                                      "SUEFCT: EFFECTIVENESS OF USSR ACTIVITY",
                                      "SUEFCT: EFFECTIVENESS OF USSR ACTIVITY",
                                      "SUEFCT: EFFECTIVENESS OF USSR ACTIVITY",
                                      "SUINV: CONTENT OF USSR ACTIVITY",
                                      "SUINV: CONTENT OF USSR ACTIVITY",
                                      "SUINV: CONTENT OF USSR ACTIVITY",
                                      "SUINV: CONTENT OF USSR ACTIVITY",
                                      "SUINV: CONTENT OF USSR ACTIVITY","SUINV: CONTENT OF USSR ACTIVITY",
                                      "SUPACE: USSR ACTIVITY AND PACE OF ABATEMENT",
                                      "SUPACE: USSR ACTIVITY AND PACE OF ABATEMENT",
                                      "SUPACE: USSR ACTIVITY AND PACE OF ABATEMENT",
                                      "SUPACE: USSR ACTIVITY AND PACE OF ABATEMENT",
                                      "SUPACE: USSR ACTIVITY AND PACE OF ABATEMENT",
                                      "SUPACE: USSR ACTIVITY AND PACE OF ABATEMENT",
                                      "USEFAC: MOST EFFECTIVE US ACTIVITY",
                                      "USEFAC: MOST EFFECTIVE US ACTIVITY",
                                      "USEFAC: MOST EFFECTIVE US ACTIVITY",
                                      "USEFAC: MOST EFFECTIVE US ACTIVITY",
                                      "USEFAC: MOST EFFECTIVE US ACTIVITY","USEFAC: MOST EFFECTIVE US ACTIVITY",
                                      "USEFAC: MOST EFFECTIVE US ACTIVITY",
                                      "USEFCT: EFFECTIVENESS OF US ACTIVITY",
                                      "USEFCT: EFFECTIVENESS OF US ACTIVITY",
                                      "USEFCT: EFFECTIVENESS OF US ACTIVITY",
                                      "USEFCT: EFFECTIVENESS OF US ACTIVITY",
                                      "USEFCT: EFFECTIVENESS OF US ACTIVITY",
                                      "USEFCT: EFFECTIVENESS OF US ACTIVITY",
                                      "USEFCT: EFFECTIVENESS OF US ACTIVITY",
                                      "USEFCT: EFFECTIVENESS OF US ACTIVITY",
                                      "USINV: CONTENT OF US ACTIVITY",
                                      "USINV: CONTENT OF US ACTIVITY","USINV: CONTENT OF US ACTIVITY",
                                      "USINV: CONTENT OF US ACTIVITY",
                                      "USINV: CONTENT OF US ACTIVITY",
                                      "USINV: CONTENT OF US ACTIVITY",
                                      "USPACE: US ACTIVITY AND PACE OF ABATEMENT",
                                      "USPACE: US ACTIVITY AND PACE OF ABATEMENT",
                                      "USPACE: US ACTIVITY AND PACE OF ABATEMENT",
                                      "USPACE: US ACTIVITY AND PACE OF ABATEMENT",
                                      "USPACE: US ACTIVITY AND PACE OF ABATEMENT",
                                      "USPACE: US ACTIVITY AND PACE OF ABATEMENT",
                                      "VIOL: VIOLENCE","VIOL: VIOLENCE","VIOL: VIOLENCE",
                                      "VIOL: VIOLENCE","VIOL: VIOLENCE",
                                      "VIOL: VIOLENCE","TIMVIO: TIMING OF VIOLENCE",
                                      "TIMVIO: TIMING OF VIOLENCE",
                                      "TIMVIO: TIMING OF VIOLENCE",
                                      "TIMVIO: TIMING OF VIOLENCE","TIMVIO: TIMING OF VIOLENCE"),
                            value = c(1L,2L,3L,4L,5L,6L,7L,8L,9L,99L,1L,
                                      2L,3L,4L,9L,95L,1L,2L,3L,4L,5L,
                                      9L,95L,1L,2L,3L,4L,5L,9L,95L,1L,
                                      2L,3L,4L,5L,6L,7L,8L,9L,95L,1L,
                                      2L,3L,4L,9L,95L,1L,2L,3L,9L,95L,
                                      1L,2L,3L,4L,5L,6L,7L,9L,95L,1L,
                                      2L,3L,4L,5L,6L,7L,9L,95L,0L,1L,
                                      10L,11L,12L,13L,2L,3L,4L,5L,6L,7L,
                                      8L,9L,95L,99L,0L,1L,2L,3L,4L,5L,
                                      6L,9L,95L,0L,1L,2L,3L,4L,5L,9L,
                                      95L,0L,1L,2L,3L,4L,5L,6L,7L,9L,
                                      95L,1L,2L,3L,4L,5L,9L,95L,1L,2L,3L,
                                      4L,5L,9L,95L,1L,2L,3L,4L,9L,95L,
                                      1L,2L,3L,9L,95L,1L,2L,3L,4L,5L,
                                      9L,95L,0L,1L,10L,11L,12L,13L,2L,
                                      3L,4L,5L,6L,7L,8L,9L,95L,99L,0L,
                                      1L,10L,11L,2L,3L,4L,5L,6L,7L,8L,
                                      9L,95L,99L,0L,1L,2L,3L,4L,5L,6L,
                                      9L,95L,1L,2L,3L,4L,5L,9L,95L,1L,
                                      2L,3L,4L,9L,95L,0L,1L,2L,3L,4L,
                                      5L,6L,7L,9L,95L,0L,1L,2L,3L,4L,5L,
                                      6L,7L,9L,95L,1L,2L,3L,4L,5L,6L,
                                      7L,9L,95L,1L,2L,9L,95L,1L,2L,3L,
                                      4L,5L,9L,95L,1L,2L,3L,4L,5L,6L,
                                      9L,95L,1L,2L,3L,4L,9L,95L,1L,2L,
                                      3L,4L,9L,95L,1L,2L,3L,4L,5L,9L,
                                      95L,1L,2L,3L,4L,5L,6L,9L,95L,1L,
                                      2L,3L,4L,9L,95L,1L,2L,3L,4L,9L,
                                      95L,1L,2L,3L,4L,9L,95L,1L,2L,3L,4L,
                                      95L),
                             text = c("VERBAL ACT","POLITICAL ACT",
                                      "ECONOMIC ACT","EXTERNAL CHANGE",
                                      "OTHER NON-VIOLENT ACT","INTERNAL CHALLENGE",
                                      "NON-VIOLENT MILITARY","INDIRECT VIOLENT",
                                      "VIOLENT ACT","MD","NO VIOLENCE AS CMT",
                                      "VIOLENCE MINOR","VIOLENCE IMPORTANT",
                                      "VIOLENCE PREEMINENT","MD",
                                      "Coding pending - see processing note","NO CHANGE",
                                      "CHANGE REG ORIENTATION","CHANGE REGIME TYPE",
                                      "CREATE-ELIM ACTOR","INTERIM CASE","MD",
                                      "Coding pending - see processing note",
                                      "NO CHANGE ALLIANCE","INC-DEC COHESION",
                                      "ENTRY-EXIT ALLIANCE","FORM-ELIM ALLIANCE",
                                      "INTERIM CASE","MD",
                                      "Coding pending - see processing note","NEGOTIATION",
                                      "ADJUD OR ARBITRATION","MEDIATION","MULT NO VIOLENCE",
                                      "NON-MILITARY PRESSURE",
                                      "NON-VIOL MILITARY","MULT INC VIOLENCE","VIOLENCE","MD",
                                      "Coding pending - see processing note",
                                      "SECESSIONIST","IRREDENTIST","OTHER",
                                      "NON-ETHNIC","MD",
                                      "Coding pending - see processing note","SECESSIONIST CONFLICT",
                                      "IRREDENTIST CONFLICT",
                                      "NON-ETHNIC CONFLICT","MD",
                                      "Coding pending - see processing note","ALL SATISFIED",
                                      "MOSTLY SATISFIED","EQUALLY MIXED","MOSTLY DISSATISFIED",
                                      "ALL DISSATISFIED","SINGLE ACTOR CASE",
                                      "NO ADVERSARIAL ACTOR","MD",
                                      "Coding pending - see processing note",
                                      "FORMAL AGREEMENT","SEMI-FORMAL AGREE",
                                      "TACIT UNDRSTND","UNILATERAL ACT","IMPOSED AGREEMENT",
                                      "OTHER","FADED","MD",
                                      "Coding pending - see processing note","GO NOT EXIST",
                                      "NO ACTIVITY","OBSERVER GROUP",
                                      "AUTH MIL FORCE MEMBERS","EMERGENCY MIL FORCE",
                                      "GENERAL-OTHER","DISC NO RESOLUTION",
                                      "FACT-FINDING","GOOD OFFICES","CONDEMNATION",
                                      "CALL FOR ACTION","MEDIATION","ARBITRATION",
                                      "SANCTIONS",
                                      "Coding pending - see processing note","MD","GO NOT EXIST",
                                      "NO GO ACTIVITY","GO ACT ESCALATED",
                                      "GO ACT NOT CONTRIB","GO ACT MARGINAL",
                                      "GO ACT IMPORTANT","GO ACT MOST IMPORT","MD",
                                      "Coding pending - see processing note",
                                      "GO NOT EXIST","NO GO ACTIVITY","GENERAL",
                                      "SECRETARY GENERAL","GENERAL ASSEMBLY",
                                      "SECURITY COUNCIL","MD",
                                      "Coding pending - see processing note","ECONOMIC THREAT",
                                      "LIMITED MIL DAMAGE","POLITICAL THREAT",
                                      "TERRITORIAL THREAT","THREAT TO INFLUENCE",
                                      "THREAT OF GRAVE DAMAGE",
                                      "THREAT TO EXISTENCE","OTHER","MD",
                                      "Coding pending - see processing note","NONE","ONE ATTRIBUTE",
                                      "TWO ATTRIBUTES","THREE ATTRIBUTES",
                                      "ALL 4 ATTRIBUTES","MD",
                                      "Coding pending - see processing note","1 ISS NOT MIL-SEC",
                                      "2 ISS NOT MIL-SEC","ONLY MIL-SEC",
                                      "2 ISS INC MIL-SEC","3 ISSUES","MD",
                                      "Coding pending - see processing note",
                                      "NO MEDIATION","REQUESTED NOT SUPPLIED",
                                      "OFFERED NOT ACCEPTED","MEDIATION OCCURRED","-",
                                      "Coding pending - see processing note",
                                      "ESCALATION OF TENSION",
                                      "REDUCTION OF TENSION","RECENT CASE","MD",
                                      "Coding pending - see processing note","NO CHANGE",
                                      "CHANGE REL POWER","CHANGE RANK",
                                      "CHANGE COMPOSITION","INTERIM CASE","MD",
                                      "Coding pending - see processing note",
                                      "RO NOT EXIST","NO RO ACTIVITY","OBSERVER FORCE",
                                      "EMERGENCY MIL FORCE","MULTIPLE",
                                      "GENERAL-OTHER","DISC NO RESOLUTION",
                                      "FACT-FINDING","GOOD OFFICES","CONDEMNATION",
                                      "CALL FOR ACTION","MEDIATION","ARBITRATION",
                                      "SANCTIONS",
                                      "Coding pending - see processing note","MD","RO NOT EXIST",
                                      "NO RO INVOLVEMENT","OTHER","MULTIPLE","LAS",
                                      "NATO","OAS","OAU","SEATO","WTO","CENTO",
                                      "COUNCIL OF EUROPE",
                                      "Coding pending - see processing note","MD","RO NOT EXIST",
                                      "NO RO ACTIVITY","RO ESCALATED",
                                      "RO NOT CONTRIBUTE","RO MARGINAL","RO IMPORTANT",
                                      "RO MOST IMPORTANT","MD",
                                      "Coding pending - see processing note","NO CHANGE",
                                      "DECLINE IN CONSENSUS","BRKDN IN CONSENSUS",
                                      "CREATE-ELIM RULES","INTERIM CASE",
                                      "MD","Coding pending - see processing note",
                                      "NO VIOLENCE AS CMT","MINOR CLASHES",
                                      "SERIOUS CLASHES","FULL SCALE WAR","MD",
                                      "Coding pending - see processing note",
                                      "GO NOT EXIST","GO NOT APPROACHED",
                                      "CRISIS ACTOR","THIRD PARTY","US","USSR",
                                      "INITIATED BY GO","MULTIPLE","MD",
                                      "Coding pending - see processing note",
                                      "RO NOT EXIST","RO NOT APPROACHED","CRISIS ACTOR",
                                      "THIRD PARTY","US","USSR",
                                      "INITIATED BY RO","MULTIPLE","MD",
                                      "Coding pending - see processing note","COMBINED",
                                      "COMBINED NO DOCS","COMBINED NON MEM",
                                      "COMBINED NO ART","COMG NO DOCS & MEM",
                                      "CHRON ARCHIVES","CHRON ARCH & MEM","MD",
                                      "Coding pending - see processing note",
                                      "AMBIGUOUS OUTCOME","DEFINITIVE OUTCOME","MD",
                                      "Coding pending - see processing note",
                                      "NO INVOLVEMENT","INEFFECTIVE",
                                      "EFF LOW LEVEL ACT","EFF COVERT OR SEMIL",
                                      "EFF MILITARY ACT","MD",
                                      "Coding pending - see processing note","NO INVOLVEMENT",
                                      "INV ESCALATED","INV NOT CONTRIBUTE","MARGINAL",
                                      "IMPORTANT","MOST IMPORTANT","MD",
                                      "Coding pending - see processing note",
                                      "NO INVOLVEMENT","LOW INVOLVEMENT","SEMI MIL-COVERT",
                                      "DIRECT MILITARY INV","MD",
                                      "Coding pending - see processing note",
                                      "NO INVOLVEMENT","DELAY TERMINATION",
                                      "ACT NOT EFFECTIVE","CONTRIBUTED TO TERM","MD",
                                      "Coding pending - see processing note",
                                      "NO INVOLVEMENT","INEFFECTIVE","EFF LOW LEVEL ACT",
                                      "EFF COVERT OR SEMIL",
                                      "EFF MILITARY ACT","MD",
                                      "Coding pending - see processing note","NO INVOLVEMENT","INV ESCALATED",
                                      "INV NOT CONTRIBUTE","MARGINAL",
                                      "IMPORTANT","MOST IMPORTANT","MD",
                                      "Coding pending - see processing note",
                                      "NO INVOLVEMENT","LOW INVOLVEMENT","SEMI MIL-COVERT",
                                      "DIRECT MILITARY INV","MD",
                                      "Coding pending - see processing note","NO INVOLVEMENT",
                                      "DELAY TERMINATION","ACT NOT EFFECTIVE",
                                      "CONTRIBUTED TO TERM","MD",
                                      "Coding pending - see processing note","NO VIOLENCE",
                                      "MINOR CLASHES","SERIOUS CLASHES",
                                      "WAR","MD",
                                      "Coding pending - see processing note","NO VIOLENCE","VIOL PRIOR CRISIS",
                                      "VIOL TRIG CRISIS","VIOL SUBSEQ TRIGGER",
                                      "Coding pending - see processing note")
               )


icb_recodes_clean <- 
    icb_recodes %>% 
      mutate(question=description %>% str_replace(".*: ","") %>% str_to_sentence() %>% paste0("?")) %>%
      mutate(answer=text %>% str_to_sentence() )  %>%
      mutate(var=var %>% tolower()) %>%
      dplyr::select(var, value, question, answer)
      
icb_crises_qa <- icb_crises %>%
                dplyr::select(crisno, crisname, start=yrtrig, end=yrterm, starts_with(icb_recodes_clean$var %>% unique())) %>% #grab all
                pivot_longer(-c(crisno, crisname,start,end), names_to="var") %>% 
                left_join(icb_recodes_clean )

qa_unique <- icb_crises_qa  %>% arrange(var, value) %>% dplyr::select(question, answer) %>% distinct() %>% na.omit()

q_unique <- qa_unique %>% dplyr::select(question) %>% distinct()

icb_crises_qa_wide <- icb_crises_qa %>% 
  filter(var %in% (c("break", 'GRAVCR','CENVIOSY','SEVVIOSY','CHACTS','CHALL','EXSAT','FOROUT') %>% tolower() ) ) %>% 
  dplyr::select(crisno,crisname,start, end, question,answer) %>%
  na.omit() %>%
  pivot_wider(id_cols=c(crisno, crisname,start,end), 
              names_from=question,values_from=answer, values_fn=function(x) paste0(x, collapse=";") )

```


```{r include=F}
# #Load the ICB wide codings
icb_wide_clean <- readRDS(file=paste0(here::here(), "/replication_paper/data/in/icb_wide_clean.Rds"))
n_crisis <- icb_wide_clean %>% dplyr::select(crisno) %>% unique() %>% nrow()
n_sentences <- icb_wide_clean %>% dplyr::select(crisno, sentence_number_int_aligned) %>% unique() %>% nrow()
n_events <- icb_wide_clean %>% dplyr::filter(event_number_int %in% c(1,2,3)) %>% nrow()
n_events_cuba <- icb_wide_clean %>% dplyr::filter(crisno == 196 & event_number_int %in% c(1,2,3)) %>% nrow()
n_coders <- icb_wide_clean %>% dplyr::select(email_id) %>% unique() %>% nrow()

avg_coders_per_crisis <- icb_wide_clean %>% dplyr::filter(crisno != 196) %>% dplyr::mutate(cris_coder = paste(crisno, email_id)) %>% dplyr::select(crisno, email_id) %>% unique() %>% dplyr::count(crisno) %>% dplyr::select(n) %>% lapply(mean)

avg_coders_per_sentence <- icb_wide_clean %>% dplyr::filter(crisno != 196) %>% dplyr::mutate(cris_sent = paste(crisno, sentence_number_int_aligned)) %>% dplyr::select(cris_sent, email_id) %>% unique() %>% dplyr::count(cris_sent) %>% dplyr::select(n) %>% lapply(mean)

avg_events_per_coder_crisis <- icb_wide_clean %>% dplyr::filter(crisno != 196) %>% dplyr::mutate(cris_coder = paste(crisno, email_id)) %>% dplyr::count(cris_coder) %>% dplyr::select(n) %>% lapply(mean)

events_per_sentence <- icb_wide_clean %>%
                        filter(!is.na(sentence_number_int_aligned)) %>%
                        dplyr::select(email_id, crisno,sentence_number_int_aligned,  event_type) %>%  #event_number_int
                        group_by(email_id,crisno,sentence_number_int_aligned) %>%
                        summarise(event_count = sum(!is.na(event_type) ) ) %>%
                        mutate_all(as.numeric) %>%
                        group_by(crisno,sentence_number_int_aligned) %>%
                        summarise(
                          event_count_min=event_count %>% min(),
                          event_count_mean=event_count %>% mean(na.rm=T),
                          event_count_max=event_count %>% max()
                          ) %>%
                        arrange(crisno,sentence_number_int_aligned)

events_per_crisis <- events_per_sentence %>% group_by(crisno) %>% summarise(event_count_mean_sum=sum(event_count_mean))

crisis_text_counts <- icb_wide_clean %>%
  mutate( input_crisis = input_crisis %>% str_replace_all("[^A-Za-z0-9 ]","") ) %>% #Throws a latex error  #inputenc Error: Unicode char \u8: not set up for use with LaTeX
  #https://www.google.com/search?q=R+replace+00A0&oq=R+replace+00A0&aqs=chrome..69i57j0i20i263i512j0i512l2j69i65j69i60l3.1744j0j7&sourceid=chrome&ie=UTF-8
  dplyr::select(crisno, input_crisis, sentence) %>%
  #mutate(input_crisis = input_crisis %>% stringr::str_to_title()) %>%
  mutate(input_crisis = input_crisis %>% stringr::str_replace_all('[0-9]$','')) %>%
  mutate(sentence = sentence %>% stringr::str_to_lower()) %>%
  distinct() %>%
  filter(!is.na(input_crisis)) %>%
  filter(!is.na(sentence)) %>%
  mutate(word_count=str_count(sentence, '\\w+')) %>%
  group_by(crisno, input_crisis) %>%
  summarise(
    sentence_count=n(),
    word_count=sum(word_count)
  )


#Even type

library(sjmisc)
event_type_per_sentence <- icb_wide_clean %>%
                            filter(!is.na(sentence_number_int_aligned)) %>%
                            dplyr::select(email_id, crisno,sentence_number_int_aligned,  event_type)  %>%
                            to_dummy(event_type, suffix = "label") %>%
                            bind_cols( icb_wide_clean %>%
                            filter(!is.na(sentence_number_int_aligned)) %>%
                            dplyr::select(email_id, crisno,sentence_number_int_aligned,  event_type) ) %>%

                            group_by(email_id,crisno,sentence_number_int_aligned) %>%
                            summarise_if( is.numeric, sum ) %>%

                            group_by(crisno,sentence_number_int_aligned) %>%
                            summarise_if( is.numeric, mean, na.rm=T ) %>%
                            arrange(crisno,sentence_number_int_aligned)

event_type_per_sentence_totals <- event_type_per_sentence %>% ungroup() %>% summarise_if( is.numeric, sum, na.rm=T ) %>% dplyr::select(-crisno)
event_type_per_sentence_totals_perc <- event_type_per_sentence_totals/sum(event_type_per_sentence_totals)

```



```{r, eval=T, echo=F, results='markup', include=T, message=F, cache=F, warning=F,  ft.arraystretch=0.75}

p_load(flextable)
p_load(ftExtra)
set_flextable_defaults(fonts_ignore=TRUE)

crisis_text_counts_ft <- 
        crisis_text_counts %>%
        ungroup() %>% 
        left_join(events_per_sentence %>% dplyr::select(crisno, event_count_mean) %>% 
                    group_by(crisno) %>% summarise(event_count_mean_sum=sum(event_count_mean)) %>% distinct() %>%
                    mutate(event_count_mean_sum = event_count_mean_sum %>% round(1)) ) %>%
        left_join(icb_crises_qa_wide %>% 
                    dplyr::select(-crisname)
                  ) %>%
        mutate(input_crisis=input_crisis %>% tolower()) %>%
        dplyr::select(-word_count)  %>%
        dplyr::select(crisno,
                      input_crisis,
                      start,
                      end,
                      sentence_count,
                      event_count_mean_sum,
                      "Breakpoint (trigger) to international crisis?",  
                      "Gravity of value threatened?",
                      "Intensity of violence?",
                      "Form of outcome?",
                      "Extent of satisfaction about outcome?"
                      ) %>%
  
        flextable::as_flextable() %>% 
        
        #bg( j = condition, part = "body", bg = "#EFEFEF") %>%
        #width(j = 1, width=1.25) %>%
        #width(j = 2:ncol(lit_review_clean), width=0.25) %>%
        flextable::fontsize(size = 6, part = "all" ) %>% 
        #rotate(rotation="tbrl",part="header") %>%
        set_header_labels( 
          values = list(crisno = "#", 
                        input_crisis = "Name", 
                        start="Start",
                        end="End",
                        sentence_count="Sent.", 
                        event_count_mean_sum="Events" ,
                        "Breakpoint (trigger) to international crisis?"="Trigger",
                        "Centrality of violence?"="Violence",
                        #"Change in actors?"="Change in Actors",
                        #"Change in alliance configuration?"="Change in Alliance",
                        "Extent of satisfaction about outcome?"="Satisfaction",
                        "Form of outcome?"="Outcome",
                        "Gravity of value threatened?"="Gravity",
                        "Intensity of violence?"="Intensity"
                        )
          ) %>% # , word_count="Words"
        #align(align = "center", part = "body") %>%
        #align(align = "center", part = "header") %>%
        #set_table_properties(layout="autofit") %>%  
        flextable::padding(padding = 0, part = "all") %>%
        flextable::line_spacing(space = 1, part = "body") %>%
        bg( i = which( 1:nrow(crisis_text_counts) %% 2 == 1)  , part = "body", bg = "#EFEFEF") %>%
        flextable::width( j = 1, width=0.2) %>%
        flextable::width( j = 2, width=1) %>%  
        flextable::width( j = 3, width=0.2) %>% colformat_num(j=3, big.mark="", decimal.mark = "",na_str = "") %>%
        flextable::width( j = 4, width=0.2) %>% colformat_num(j=4, big.mark="", decimal.mark = "",na_str = "") %>%
        flextable::width( j = 5, width=0.2) %>% 
        flextable::width( j = 6, width=0.3) %>% 
        flextable::width( j = 7:11, width=0.9)  

#https://cran.r-project.org/web/packages/ftExtra/vignettes/format_columns.html

crisis_text_counts_ft  %>% saveRDS(paste0(here::here(), "/replication_paper/tables/ft_crisis_text_counts.Rds"))

crisis_text_counts_ft
```
