---
title: "InternalMeasurementValidity.Rmd"
output: html_document
---

```{r}
library(flextable)
library(tidyverse)

```

```{r, echo=FALSE}

icb_long_clean <- readRDS(file=paste0(here::here(), "/data/icb_long_clean.Rds"))
icb_wide_clean <- readRDS(file=paste0(here::here(), "/data/icb_wide_clean.Rds"))

```


```{r echo=FALSE, include=T, eval=T}

library(janitor)
#table(icb_wide_clean$email_id )
icb_wide_clean$email_id_expert <- icb_wide_clean$email_id %>% str_detect("grad|postgrad")

#icb_wide_clean$email_id_expert 
#icb_wide_clean$raterconfidence
#icb_wide_clean$raterconfidence_reason

icb_wide_clean %>% 
  tabyl(email_id_expert, raterconfidence, show_na = FALSE) %>%
  adorn_percentages("row") %>% 
  adorn_pct_formatting(digits = 2) %>%
  adorn_ns()

icb_wide_clean  %>%
    mutate(raterconfidence_reason = raterconfidence_reason %>% str_replace_all("other|;","") %>% trimws() ) %>%
    filter(raterconfidence_reason!='')  %>%
    tabyl(raterconfidence_reason, show_na = FALSE) %>%
    arrange(desc(n)) %>%
    head() %>%
    mutate(percent=percent %>% round(2))

icb_long_clean$email_id_expert <- icb_long_clean$email_id %>% str_detect("grad|postgrad")

temp <- icb_long_clean %>%
        dplyr::select(email_id, email_id_expert, crisno, sentence_number_int_aligned, variable, value) %>%
        filter(!variable %in% c('date','say_actor_a','say_actor_b','do_actor_a','do_actor_b','think_actor_a','think_sentence_events','do_timing_reorder','sayintkind_react','do_timing_reorder',
                                'coder_crisis_order','point_in_time','start_time','end_time','earliest_date','preceding_event',
                                'act_cooperative','act_descalate act_escalate', 'act_uncooperative', 'interact_decreasecoop', 'interact_descalate', 'interact_escalate', 'interact_increasecoop',
                                'act_descalate','act_escalate','thinkkind','act_descalate','act_escalate','raterconfidence_reason_survey','raterconfidence_reason') &
                 !variable %>% str_detect("condition|actor|location_other|date|time")
               ) 

var_names <- temp %>% pull(variable) %>% unique()
library(fastDummies)
temp_wide <- temp %>% mutate(variable_value=paste0(variable,";",value)) %>% dplyr::select(-variable,-value) %>% dummy_cols(select_columns='variable_value', remove_selected_columns=T) 
dim(temp_wide)

temp_mean_expert <- temp_wide %>%
                    group_by(email_id_expert,email_id,crisno,sentence_number_int_aligned) %>% #max for that person across all events they found
                    summarise_if(is.numeric, max) %>%
                    dplyr::select(-email_id) %>%
                    group_by(email_id_expert,crisno,sentence_number_int_aligned) %>% #max for that person across all events they found
                    summarise_if(is.numeric, mean) %>%
                    ungroup()

temp_mean_expert_lomg <- temp_mean_expert %>%
                          filter(email_id_expert==T) %>%
                          ungroup() %>%
                          dplyr::select(-email_id_expert) %>% #,-email_id
                          pivot_longer(cols=-c(crisno,sentence_number_int_aligned)) %>%
                          mutate(value= abs(value-0.5)*2) %>% #0 means completely disagree 1 means completely agree
                          group_by(name) %>%
                          summarise(value=mean(value))

#only positives
temp_mean_expert_lomg_onlypos <- temp_mean_expert %>%
                                filter(email_id_expert==T) %>%
                                ungroup() %>%
                                dplyr::select(-email_id_expert) %>%
                                pivot_longer(cols=-c(crisno,sentence_number_int_aligned)) %>%
                                filter(value>0) %>% #only consider agreement when at least one coder uses the tag in that sentence
                                mutate(value= abs(value-0.5)*2) %>% #0 means completely disagree 1 means completely agree
                                rename(agreement=value) %>%
                                separate(name, c("variable", "value"), ";" ) %>%
                                group_by(variable) %>%
                                mutate(agreement_a=mean(agreement)) %>%
                                group_by(variable,value) %>%
                                mutate(agreement_b=mean(agreement)) %>%
                                ungroup() %>%
                                dplyr::select(-crisno, -sentence_number_int_aligned, -agreement) %>%
                                distinct()

#Confidence
temp2_confidence <- icb_long_clean %>%
                      dplyr::select(email_id, email_id_expert, crisno, sentence_number_int_aligned, raterconfidence, variable, value) %>%
                      filter(email_id_expert==T) %>%
                      filter(!variable %in% c('date','say_actor_a','say_actor_b','do_actor_a','do_actor_b','think_actor_a','think_sentence_events','do_timing_reorder','sayintkind_react','do_timing_reorder',
                                              'coder_crisis_order','point_in_time','start_time','end_time','earliest_date','preceding_event',
                                              'act_cooperative','act_descalate act_escalate', 'act_uncooperative', 'interact_decreasecoop', 'interact_descalate', 'interact_escalate', 'interact_increasecoop',
                                              'act_descalate','act_escalate','thinkkind','act_descalate','act_escalate','raterconfidence_reason_survey','raterconfidence_reason') &
                               !variable %>% str_detect("condition|actor|location_other|date|time")
                             ) %>%
                      mutate(raterconfidence=factor(raterconfidence, levels=c('None', 'Low', 'High',  'Complete') )) %>% 
                      group_by(variable) %>%
                      mutate(raterconfidence_a=raterconfidence %>% as.numeric() %>% mean(na.rm=T) %>% round(2)) %>%
                      group_by(variable, value) %>%
                      mutate(raterconfidence_b=raterconfidence %>% as.numeric() %>% mean(na.rm=T) %>% round(2)) %>%
                      ungroup() %>%
                      dplyr::select(-email_id, -email_id_expert, -crisno, -sentence_number_int_aligned, -raterconfidence) %>%
                      distinct()

```

```{r, eval=T, echo=F, results='markup', include=T, message=F, cache=F, ft.arraystretch=0.75}

intercoder_agreement_and_confidence_by_item <- temp_mean_expert_lomg_onlypos %>% 
                                                mutate(variable=variable %>% str_replace_all("variable_value_|clean",""))  %>%
                                                mutate(variable=variable %>% str_replace_all("_",""))  %>%
                                                left_join(temp2_confidence %>% 
                                                                  mutate(variable=variable %>% str_replace_all("variable_value_|clean",""))  %>%
                                                                  mutate(variable=variable %>% str_replace_all("_","")) 
                                                          ) %>%
                                                dplyr::arrange(desc(agreement_a), desc(agreement_b)) %>%
                                                mutate(agreement_a=agreement_a %>% round(3)) %>% 
                                                mutate(agreement_b=agreement_b %>% round(3)) 


temp2 <- 
intercoder_agreement_and_confidence_by_item %>%
  mutate(variable= paste0(variable, ' (', round(agreement_a*100,0),'%)'  )) %>% #round(raterconfidence_a,2)
  mutate(value= paste0(value, ' (', round(agreement_b*100,0),'%)'  )) %>% #,round(raterconfidence_b,2),  
  arrange(agreement_a %>% desc(),agreement_b %>% desc()) %>%
  group_by(agreement_a,variable) %>%
  summarise(value=paste0(value,collapse=", ")) %>%
  arrange(agreement_a %>% desc() ) %>%
  ungroup() %>%
  dplyr::select(-agreement_a) %>%
  mutate(variable=variable %>% str_replace("dointeractkind","Interaction")) %>%
  mutate(variable=variable %>% str_replace("interactdomains","Domain")) %>%
  mutate(variable=variable %>% str_replace("actuncooperative","Act-Uncooperative")) %>%
  mutate(variable=variable %>% str_replace("sayintkind","Speech")) %>%
  mutate(variable=variable %>% str_replace("actcooperative","Act-cooperative")) %>%
  mutate(variable=variable %>% str_replace("dokind","Act")) %>%
  mutate(variable=variable %>% str_replace("consequence","Consequence")) %>%
  mutate(variable=variable %>% str_replace("interactunits","Units")) %>%
  mutate(variable=variable %>% str_replace("interactincreasecoop","Interaction-Cooperative")) %>%
  mutate(variable=variable %>% str_replace("interactlocation","Location")) %>%
  mutate(variable=variable %>% str_replace("interactescalate"    ,"Interaction-Escalate")) %>%
  mutate(variable=variable %>% str_replace("dotiming","Timing")) %>%
  mutate(variable=variable %>% str_replace("interactterritory","Territory")) %>%
  mutate(variable=variable %>% str_replace("interactgeoscope","Geographic Scope")) %>%
  mutate(variable=variable %>% str_replace("interactdecreasecoop","Interaction-Uncooperative")) %>%
  mutate(variable=variable %>% str_replace("interactdescalate","Interaction-Deescalate")) %>%
  mutate(variable=variable %>% str_replace("doduration","Duration")) %>%
  mutate(variable=variable %>% str_replace("actescalate","Act-Escalate")) %>%
  mutate(variable=variable %>% str_replace("interactfatalities","Fatalities")) %>%
  mutate(variable=variable %>% str_replace("interactforces","Forces")) %>%
  mutate(variable=variable %>% str_replace("actdescalate"   ,"Act-Deescalate"))

temp2 %>%
  flextable::flextable() %>%
  flextable::bg( i = which( 1:nrow(temp2) %% 2 == 1), part = "body", bg = "#EFEFEF") %>%
  #merge_v(part = "body") %>% 
  #flextable::width( j = 1, width=7) %>%
  flextable::fontsize(size = 8, part = "body") %>%
  #flextable::line_spacing( space = 0.5, part = "body") %>% #i=1:nrow(lit_review_alt),
  flextable::padding(padding = 0, part = "body")  %>%
  flextable::merge_v(part = "body", combine = FALSE) %>%
  flextable::width( j = 1, width=1)    %>%
  flextable::width( j = 2, width=6)  

# intercoder_agreement_and_confidence_by_item %>%
#                   flextable::flextable() %>%
#                   flextable::bg( i = which( 1:nrow(temp_mean_expert_lomg_onlypos) %% 2 == 1), part = "body", bg = "#EFEFEF") %>%
#                   #merge_v(part = "body") %>% 
#                   #flextable::width( j = 1, width=7) %>%
#                   flextable::fontsize(size = 6, part = "body") %>%
#                   #flextable::line_spacing( space = 0.5, part = "body") %>% #i=1:nrow(lit_review_alt),
#                   flextable::padding(padding = 0, part = "body")  %>%
#                   flextable::merge_v(part = "body", combine = FALSE) 

#Note Average intercoder agreement and self reported confidence look uncorrelated at the item level. I think it's because they're correlated at the sentence level, not the item level.
p_item_confidence_vs_agreement <- 
  intercoder_agreement_and_confidence_by_item %>%
  ggplot(aes(x=raterconfidence_b  ,y=agreement_b )) +
  geom_point() +
  geom_quantile(method = "rqss")

```
