---
title: "ICBEdataset figure Metro Maps"
output: html_document
---

# Metro Maps

```{r}

#devtools::install_github('davidgohel/ggiraph')
library(ggplot2)
library(ggiraph)

library(flextable)
library(ftExtra)
library(tidyverse)
library(googlesheets4)
library(RColorBrewer)
library(tidyverse)
library(ggraph)
#library(edgebundle)
library(igraph)
library(stringr)

rex_paste <- function(x) { x %>% unique() %>% na.omit() %>% sort() %>% paste0(sep=";", collapse=";")}
rex_count <- function(x) { x %>% unique() %>% na.omit() %>% sort() %>% paste0(sep=";", collapse=";")}

```

# Common Preprocessing and Loads

```{r echo=FALSE, include=FALSE, eval=T}

icb_crises <- read.csv(paste0(here::here(), "/replication_paper/data/in/icb1v14.csv")) 
#icb_crises <-readRDS(paste0(here::here(), "/data/icb1v14.Rds") )

icb_long_clean <- readRDS(file=paste0(here::here(), "/replication_paper/data/in/icb_long_clean.Rds")) 

crisno_name_years <- icb_crises %>% dplyr::select(crisno, crisname, yrtrig, yrterm)

target_file <- paste0(here::here(),"/replication_paper/data/in/icb_manual_recoding_master_sheet.xlsx")

dictionary_actors_labels    <- readxl::read_excel(target_file, sheet="actors") %>% dplyr::select(crisno, value_normalized=value_normalized_wikidata_id, value_normalized_label) %>% dplyr::distinct() %>% na.omit()

codings_long <- readRDS( paste0(here::here(), "/replication_paper/data/in/codings_long.Rds")) 
codings_long_agreement <- readRDS( paste0(here::here(), "/replication_paper/data/in/codings_long_agreement.Rds")) 
codings_long_agreed <- readRDS( paste0(here::here(), "/replication_paper/data/in/codings_long_agreed.Rds")) 
codings_wide_agreed <- readRDS( paste0(here::here(), "/replication_paper/data/in/codings_wide_agreed.Rds")) 

#Design specification
#Time flows downward
#Each actor gets a line
#Spacing between lines should be dynamic, to allow for readability between
#We want the name of each actor to be labeled at the start of their line
#Unilateral actions printed above

actor_translator    <- readxl::read_excel(target_file, sheet="actor_translator")

icb_crises$start_simple <- icb_crises$yrtrig+(icb_crises$motrig/12)
icb_crises$end_simple <- icb_crises$yrterm+(icb_crises$moterm/12)



```

# ICBe

## ICBe metro plots

```{r}

#codings_wide_agreed_pruned_labeled %>% dplyr::select(start_time)


icbe_metro_plots <- function(crisis=196, prune_rare=T){

  print(crisis)
  #crisis=426
  plot_title <- crisno_name_years %>% filter(crisno==crisis) %>% mutate(title="Crisis #" %>% paste0(crisno, " ", crisname, " (", yrtrig, "-",yrterm,")")) %>% pull(title)
  save_file <- paste0(here::here(), "/replication_paper/figures/metro_plots/p_metro_plot_", crisis, ".Rds")
  
  codings_wide_agreed_subset <- codings_wide_agreed %>% 
                                 ungroup() %>%
                                 dplyr::filter(crisno==crisis) %>%  #417 196
                                 dplyr::filter(!is.na(think_actor_a) | !is.na(say_actor_a) | !is.na(do_actor_a))  %>%
                                 mutate(point_in_time_year = point_in_time %>% substr(start=1, stop=4) %>% as.numeric() ) %>%
                                 mutate(point_in_time_month = point_in_time %>% substr(start=6, stop=7) %>% as.numeric() ) 
  

  
  codings_wide_agreed_subset_diad <- codings_wide_agreed_subset %>% 
                                    mutate(think_actor_a = strsplit(as.character(think_actor_a), ";")) %>% unnest(think_actor_a) %>%
                                    mutate(say_actor_a = strsplit(as.character(say_actor_a), ";")) %>% unnest(say_actor_a) %>%
                                    mutate(say_actor_b = strsplit(as.character(say_actor_b), ";")) %>% unnest(say_actor_b) %>%
                                    mutate(do_actor_a = strsplit(as.character(do_actor_a), ";")) %>% unnest(do_actor_a) %>%
                                    mutate(do_actor_b = strsplit(as.character(do_actor_b), ";")) %>% unnest(do_actor_b) %>%
                                    dplyr::select(sentence_number_int_aligned, #You have to keep this to remove dupe monads from the same sentence
                                                  sent=final_event_ordering,
                                                  think_actor_a,say_actor_a,say_actor_b,do_actor_a,do_actor_b,leaf_think_original, leaf_say_original, leaf_do_original,
                                                  point_in_time_year, point_in_time_month) %>% distinct() %>%
                                        filter(!duplicated(paste(sentence_number_int_aligned,think_actor_a, say_actor_a, say_actor_b, do_actor_a, do_actor_b, leaf_think_original, leaf_say_original, leaf_do_original))) 
  
  notes=NULL
  if(prune_rare==T){
    actor_sent_counts <- 
      bind_rows(
          codings_wide_agreed_subset %>% dplyr::select(sent=final_event_ordering,actor=think_actor_a),
          codings_wide_agreed_subset %>% dplyr::select(sent=final_event_ordering,actor=say_actor_a),
          codings_wide_agreed_subset %>% dplyr::select(sent=final_event_ordering,actor=say_actor_b),
          codings_wide_agreed_subset %>% dplyr::select(sent=final_event_ordering,actor=do_actor_a),
          codings_wide_agreed_subset %>% dplyr::select(sent=final_event_ordering,actor=do_actor_b)
        ) %>% 
          na.omit() %>%
          mutate(actor = strsplit(as.character(actor), ";")) %>% unnest(actor) %>% distinct() %>% count(actor) %>% arrange(n %>% desc() )
    
      singleton_actors <- actor_sent_counts %>% filter(n==1) %>% pull(actor)
      left_over_count <- nrow(actor_sent_counts) - length(singleton_actors)
      if(left_over_count<=3){
        #Skip pruning if it leaves less than 3 actors
      } else {
      
        actor_map <- dictionary_actors_labels %>% filter(crisno==crisis) %>% distinct() %>% rename(actor=value_normalized) 
        actor_singleton_labels <- actor_map$value_normalized_label
        names(actor_singleton_labels) <- actor_map$actor
        actor_singleton_labels <- actor_singleton_labels[singleton_actors]
        
        notes <- paste("Not shown: ", paste( actor_singleton_labels, collapse="; " ))
        
        #Easiest thing is to just prune the original data
        codings_wide_agreed_subset <- codings_wide_agreed_subset %>%
          filter(!(
                think_actor_a %in% singleton_actors | #This doesn't work for joint ones
                say_actor_a %in% singleton_actors |
                say_actor_b %in% singleton_actors |
                do_actor_a %in% singleton_actors |
                do_actor_b %in% singleton_actors 
          ) )
        
        codings_wide_agreed_subset_diad <- codings_wide_agreed_subset_diad %>%
          filter(!(
                think_actor_a %in% singleton_actors | #This doesn't work for joint ones
                say_actor_a %in% singleton_actors |
                say_actor_b %in% singleton_actors |
                do_actor_a %in% singleton_actors |
                do_actor_b %in% singleton_actors 
          ) )
      }
  }
  
  g <- make_empty_graph(n = 0, directed = TRUE)
    #graph_from_data_frame(vertices=nodes) #relations, directed=TRUE, 
  

  #Order actors by how many interactions they have together
  temp <- bind_rows(
    codings_wide_agreed_subset_diad  %>% 
      dplyr::select(say_actor_a, say_actor_b, sent) %>% na.omit()  %>% dplyr::rename(actor_1=say_actor_a, actor_2=say_actor_b),
    codings_wide_agreed_subset_diad %>% 
      filter(is.na(leaf_say_original)) %>%  dplyr::select(do_actor_a, do_actor_b, sent) %>% na.omit() %>% dplyr::rename(actor_1=do_actor_a, actor_2=do_actor_b)
  )  %>% arrange(actor_1, actor_2) %>% distinct()
  
  

  
  temp2 <- bind_rows(
    temp,
    temp %>% setNames(c("actor_2", "actor_1", "sent"))
  ) %>% count(actor_1, actor_2) %>% arrange(actor_1, actor_2) %>% arrange(n)
  
  temp2_wide <- temp2 %>% tidyr::pivot_wider(id_cols=c(actor_1), names_from=actor_2, values_from=n) %>% mutate_if(is.numeric, tidyr::replace_na, 0) %>% as.data.frame()
  rownames(temp2_wide) <- temp2_wide$actor_1
  temp2_wide$actor_1 <- NULL
  temp2_wide <- temp2_wide %>% as.matrix()
  temp2_wide <- 1 - (temp2_wide/max(temp2_wide))
  temp2_wide <- temp2_wide[sort(rownames(temp2_wide)), sort(colnames(temp2_wide))]
  hc <- hclust(temp2_wide %>% as.dist(), method="single")
  
  temp_list <- list()
  for(i in 1:nrow(temp2_wide)){
    temp_list[[as.character(i)]] <- cutree(hc, k=i)
  }
  
  #ideal_ordering <- bind_rows(temp_list) %>% t() %>% as.data.frame() %>% apply(1, paste, collapse='') %>% sort() %>% names() #this will break with more than 9
  #  arrange(across(starts_with("V")))
  ideal_ordering <- hc$labels[hc$order] #There's a bug here, put all the isolated nodes by themselves first
  
  #####Nodes
  codings_wide_agreed_subset_nodes <- 
            bind_rows(
                      codings_wide_agreed_subset_diad %>% dplyr::select(sent, actor=think_actor_a, point_in_time_year, point_in_time_month) ,
                      codings_wide_agreed_subset_diad %>% dplyr::select(sent, actor=say_actor_a, point_in_time_year, point_in_time_month) ,
                      codings_wide_agreed_subset_diad %>% dplyr::select(sent, actor=say_actor_b, point_in_time_year, point_in_time_month) ,
                      codings_wide_agreed_subset_diad %>% dplyr::select(sent, actor=do_actor_a, point_in_time_year, point_in_time_month) ,
                      codings_wide_agreed_subset_diad %>% dplyr::select(sent, actor=do_actor_b, point_in_time_year, point_in_time_month) 
            )  %>%
            filter(!is.na(actor)) %>%
           distinct()  %>% arrange(actor,sent) %>% mutate(actor_sent= actor %>% paste0("_", str_pad(sent, 2, pad = "0") )) %>% #don't na omit this one
            mutate(x=actor %>% factor(levels=actor %>% unique() %>% setdiff(ideal_ordering) %>% c(ideal_ordering)) %>% as.numeric() *100 ,
                   y=sent*-1 *100)
  
  actors=codings_wide_agreed_subset_nodes$actor %>% unique() %>% as.factor()
  actor_colors = c(brewer.pal(n=11, "Dark2"), brewer.pal(n=11, "Set1"))[1:length(actors)] #ok so pick a bewer pallet with lots of values and then assign it to specific values
  names(actor_colors) = levels(actors)
  
  
  date_sineposts <- codings_wide_agreed_subset_nodes  %>%
                      mutate(x=max(x)+50) %>%
                      dplyr::select(sent, point_in_time_year, point_in_time_month,x,y) %>%
                      na.omit() %>% 
                      distinct() %>%  
                      mutate(sent=as.numeric(sent)) %>% arrange(sent) %>%
                      mutate(year_float=point_in_time_year+(point_in_time_month/12)) %>%
                      group_by(sent) %>%
                       filter(year_float==min(year_float)) %>%
                      ungroup() %>% as.data.frame() %>%
                      filter( row_number()==1 |  ( year_float > lag(year_float)  ) )  %>%
                      filter(!duplicated(year_float ) ) %>%
                      mutate(label=paste0(point_in_time_year,"-",month.abb[point_in_time_month]))
    
    #Units
  units <-   codings_wide_agreed_subset %>% dplyr::select(sent=final_event_ordering, do_actor_a, interact_units) %>% na.omit()  %>% 
              mutate(interact_units = strsplit(as.character(interact_units), ";")) %>% unnest(interact_units) %>%
              mutate(do_actor_a = strsplit(as.character(do_actor_a), ";")) %>% unnest(do_actor_a) %>%
              mutate(IMAGE=paste0(here::here(), '/replication_paper/figures/metro_plots/symbols/',interact_units,'.png')) %>%
              mutate(actor_sent= do_actor_a %>% paste0("_", str_pad(sent, 2, pad = "0") )) %>%
              left_join(codings_wide_agreed_subset_nodes %>% dplyr::select(actor_sent, x, y) ) %>%
              dplyr::select(-sent, -do_actor_a) %>% distinct() %>% 
              arrange(actor_sent, interact_units) %>%
              group_by(actor_sent) %>%
                mutate(units_count=n()) %>%
                mutate(middle=units_count/2) %>%
                mutate(units_number=row_number()) %>%
                mutate(offeset=(middle-units_number)*10)  
    
  fatalities <-   codings_wide_agreed_subset %>% 
        dplyr::select(crisno, sent=final_event_ordering, do_actor_b, interact_fatalities) %>% na.omit() %>% #filter(interact_fatalities!='none') %>%
        mutate(interact_fatalities = strsplit(as.character(interact_fatalities), ";")) %>% unnest(interact_fatalities) %>%
        mutate(do_actor_b = strsplit(as.character(do_actor_b), ";")) %>% unnest(do_actor_b) %>%
        mutate(actor_sent= do_actor_b %>% paste0("_", str_pad(sent, 2, pad = "0") )) %>%
        left_join(codings_wide_agreed_subset_nodes %>% dplyr::select(actor_sent, x, y) ) %>%
        rename(actor=do_actor_b) %>%
        #dplyr::select(-sent, -do_actor_b) %>%
        distinct() %>% 
        mutate(interact_fatalities=interact_fatalities %>% factor(levels=c('none','individuals','tens','hundreds','thousands','tens of thousands','hundreds of thousands')) %>% as.numeric() ) %>%
        arrange(actor_sent, interact_fatalities) %>%
        group_by(actor_sent) %>%
          filter(interact_fatalities==max(interact_fatalities, na.rm=T)) %>%
        ungroup()
    
  
  #table(codings_wide_agreed$interact_fatalities)
  #table(codings_wide_agreed$interact_domains)
  #table(codings_wide_agreed$interact_forces)


  units <-   codings_wide_agreed_subset %>% dplyr::select(sent=final_event_ordering, do_actor_a, interact_units) %>% na.omit()  %>% 
              mutate(interact_units = strsplit(as.character(interact_units), ";")) %>% unnest(interact_units) %>%
              mutate(do_actor_a = strsplit(as.character(do_actor_a), ";")) %>% unnest(do_actor_a) %>%
              mutate(IMAGE=paste0(here::here(), "/replication_paper/figures/metro_plots/symbols/",interact_units,'.png')) %>%
              mutate(actor_sent= do_actor_a %>% paste0("_", str_pad(sent, 2, pad = "0") )) %>%
              left_join(codings_wide_agreed_subset_nodes %>% dplyr::select(actor_sent, x, y) ) %>%
              dplyr::select(-sent, -do_actor_a) %>% distinct() %>% 
              arrange(actor_sent, interact_units) %>%
              group_by(actor_sent) %>%
                mutate(units_count=n()) %>%
                mutate(middle=units_count/2) %>%
                mutate(units_number=row_number()) %>%
                mutate(offeset=(middle-units_number)*5)   


  ####Actor lavels
  codings_wide_agreed_subset_nodes_min <- 
    codings_wide_agreed_subset_nodes %>% group_by(actor) %>% filter(sent==sent %>% min()) %>% ungroup() %>%
    left_join(dictionary_actors_labels %>% filter(crisno==crisis) %>% distinct() %>% rename(actor=value_normalized) ) %>%
    rename(qcode=actor, actor=value_normalized_label) %>%
    rowwise() %>%
    mutate(actor=actor %>% stringi::stri_wrap(width=15) %>% paste0(collapse='\n'))
  
  
  for(i in 1:nrow(codings_wide_agreed_subset_nodes)){
    g <- g %>%  add_vertices(1, name=codings_wide_agreed_subset_nodes$actor_sent[i],
                                actor = codings_wide_agreed_subset_nodes$actor[i], 
                                sent = codings_wide_agreed_subset_nodes$sent[i]  ) #, type = nodes$type[i] #, leaf = nodes$leaf[i]
  }
  
  xy <- cbind(codings_wide_agreed_subset_nodes$x, codings_wide_agreed_subset_nodes$y )
  
  
  #####Time Edges
  codings_wide_agreed_subset_nodes_edges_time <- cbind(codings_wide_agreed_subset_nodes, bind_rows(codings_wide_agreed_subset_nodes[-1,],codings_wide_agreed_subset_nodes[1,] ) ) %>% janitor::clean_names() %>% filter(actor==actor_2 & sent_2>sent) %>% distinct()
  
  g <- g %>% 
       add_edges(codings_wide_agreed_subset_nodes_edges_time[,c('actor_sent','actor_sent_2')] %>% as.matrix() %>% t() %>% as.vector(),
                 actor=codings_wide_agreed_subset_nodes_edges_time$actor, timeedge=T, leaf='', eventedge=F, bundle_count=1)
  
  
  ######Monads
  codings_wide_agreed_subset_monad <- 
            bind_rows(
                      codings_wide_agreed_subset_diad %>% dplyr::select(sentence_number_int_aligned, sent, actor=think_actor_a,leaf=leaf_think_original) ,
                      codings_wide_agreed_subset_diad %>% filter(!is.na(say_actor_a) & is.na(say_actor_b)) %>% dplyr::select(sentence_number_int_aligned, sent,actor=say_actor_a,leaf=leaf_say_original) ,
                      codings_wide_agreed_subset_diad %>% filter(!is.na(do_actor_a) & is.na(do_actor_b)) %>% dplyr::select(sentence_number_int_aligned, sent,actor=do_actor_a,leaf=leaf_do_original) 
            ) %>% 
            na.omit() %>% 
            distinct() %>% 
            filter(!duplicated(paste(sentence_number_int_aligned,actor,leaf))) %>%
            mutate(actor_sent= actor %>% paste0("_", str_pad(sent, 2, pad = "0") )) %>%
            mutate(leaf = strsplit(as.character(leaf), ";")) %>% unnest(leaf) %>%
            distinct() %>% 
            group_by(sent,actor,actor_sent) %>%
              summarise(leaf=paste(leaf, collapse="\n") ) %>%
            left_join( codings_wide_agreed_subset_nodes %>% dplyr::select(actor_sent,x,y))
  
  
  ######Directed
  codings_wide_agreed_subset_directed <- 
            bind_rows(
                      codings_wide_agreed_subset_diad %>% filter(is.na(leaf_do_original)) %>% dplyr::select(sent,actor_1=say_actor_a, actor_2=say_actor_b, leaf=leaf_say_original) ,
                      codings_wide_agreed_subset_diad %>% filter(!is.na(leaf_do_original)) %>% mutate(leaf=paste0(leaf_say_original,"-",leaf_do_original)) %>% dplyr::select(sent,actor_1=say_actor_a, actor_2=say_actor_b, leaf),
                      codings_wide_agreed_subset_diad %>% filter(is.na(leaf_say_original)) %>% dplyr::select(sent,actor_1=do_actor_a, actor_2=do_actor_b, leaf=leaf_do_original) 
            ) %>% 
            na.omit() %>% 
            distinct() %>% 
            mutate(leaf = strsplit(as.character(leaf), ";")) %>% unnest(leaf) %>% distinct() %>% 
            mutate(actor_sent_1= actor_1 %>% paste0("_", str_pad(sent, 2, pad = "0") )) %>%
            mutate(actor_sent_2= actor_2 %>% paste0("_", str_pad(sent, 2, pad = "0") )) %>%
            group_by(sent,actor_1, actor_sent_1,actor_sent_2) %>%
              summarise(leaf=paste(leaf, collapse="\n") ) %>% 
           arrange(sent, actor_sent_1,leaf) %>%
           filter(actor_sent_1!=actor_sent_2) #there's a bug where you get the same node on both sides somehow
            #filter(actor_sent_2 %>% str_detect("Q30") | actor_sent_1 %>% str_detect("Q30"))

  #debug
  codings_wide_agreed_subset_directed <- codings_wide_agreed_subset_directed  %>% 
           group_by(sent, leaf) %>%
               mutate(bundle_count=n()) %>%
               mutate(leaf2=ifelse(bundle_count>1 & row_number()>1,'',leaf)) %>% #kill leaf titles past 1 #paste0(sent,"_",actor_1,"_",actor_sent_2)
            ungroup() #%>% 
            #filter(bundle_count>1)
  
  g <- g %>% add_edges(codings_wide_agreed_subset_directed[,c('actor_sent_1','actor_sent_2')] %>% as.matrix() %>% t() %>% as.vector(),
                       timeedge=F, 
                       leaf=codings_wide_agreed_subset_directed$leaf2, 
                       eventedge=T,
                       actor=codings_wide_agreed_subset_directed$actor_1,
                       bundle_count=codings_wide_agreed_subset_directed$bundle_count
                       ) 
  
  
    #https://www.flaticon.com/free-icons/aircraft-carrier
  #install.packages('ggimage')
  library(ggimage)
  
  #hbundle <- edge_bundle_hammer(g, xy, bw = 0.7, decay = 0.5)
  
  ######Put it all together
  p_metro_map <- g %>%  
          ggraph("manual",x=xy[,1],y=xy[,2]) +  #geom_edge_parallel
    
          #Event edges
          #geom_path(data = hbundle, aes(x, y, group = group), col = "#9d0191", size = 0.05) +
  
          geom_edge_arc(aes(  
                              colour=actor,
                              label=leaf,
                              filter=eventedge==T & bundle_count==1
                              ),
                          vjust = -0.75,
                          lineheight = .75,
                          sep = unit(1, 'mm'), 
                          edge_width=0.25, 
                          show.legend = F,
                          arrow = arrow(length = unit(2, 'mm')),
                          label_size=3,
                          check_overlap=T,
                          start_cap = circle(3, 'mm'),
                          end_cap = circle(3, 'mm'),
                          angle_calc = 'along'
                         ) +
              #Grouped Edges
              geom_edge_parallel(aes(  
                                  colour=actor,
                                  label=leaf,
                                  filter=eventedge==T & bundle_count>1
                                  ),
                              vjust = -0.75,
                              lineheight = .75,
                              sep = unit(5, 'mm'), 
                              edge_width=0.4,  #0.25
                              show.legend = F,
                              arrow = arrow(length = unit(1, 'mm')),
                              label_size=4,
                              check_overlap=T,
                              start_cap = circle(3, 'mm'),
                              end_cap = circle(3, 'mm'),
                              angle_calc = 'along'
                             ) +
  
              #Time edges
              geom_edge_link(aes(
                              edge_colour=actor,
                              filter=timeedge==T
                              ),
                              edge_width=0.1, 
                              show.legend = F,
                              check_overlap=T
                             ) +
              geom_node_point(aes(color=actor),size=1,stroke=0.5) +
              
              geom_text(data=fatalities %>% filter(interact_fatalities>1), aes(x=x+4,y=y, size=interact_fatalities+1), color='black', label='☠', angle=0, check_overlap = T) +
              geom_text(data=codings_wide_agreed_subset_monad, aes(x=x,y=y, label=leaf), nudge_y=40, angle=0, lineheight = .75, size=3, check_overlap = T) +
              geom_text(data=codings_wide_agreed_subset_nodes_min, aes(x=x,y=y, label=actor, color=qcode), nudge_y=150, angle=0, size=4, lineheight = .75, fontface = "bold",
                        check_overlap = T) + #-45
              geom_text(data=date_sineposts, aes(x=x,y=y, label=label), color="grey", nudge_y=0, angle=0, size=4, lineheight = .75, fontface = "bold",check_overlap = T) + #-45
              scale_color_manual(values = actor_colors)  +
              scale_edge_color_manual(values = actor_colors) +
              #theme_bw() + 
              #labs( title = plot_title ) +
              theme_graph() +
              theme(legend.position = "none") +
              ggimage::geom_image(data= units, aes(x=x+offeset,y=y-30, image = IMAGE), size = 0.015)
  
  if(prune_rare==T & !is.null(notes)){
     p_metro_map <- p_metro_map + labs(caption = notes)
  }
  
  p_metro_map$actor_colors <- actor_colors #we have to smuggle the variable containing the colors out in the object 
  p_metro_map$sentence_count <- codings_wide_agreed_subset$final_event_ordering %>% unique() %>% length()
  p_metro_map$codings_wide_agreed_subset <- codings_wide_agreed_subset
  
  
  p_metro_map   %>% saveRDS(save_file)

  return(NULL)
}

c(196, 426) %>% sapply(FUN=function(x) icbe_metro_plots(x))

```

## ICBe Tables

Go ahead an out the sentence tables too here why not

```{r}


icb_sentence_tables <- function(crisis=196){
  print(crisis)
  ft_title <- crisno_name_years %>% filter(crisno==crisis) %>% mutate(title="Crisis #" %>% paste0(crisno, " ", crisname, " (", yrtrig, "-",yrterm,")")) %>% pull(title)
  save_file <- paste0(here::here(), "/replication_paper/tables/sentence_tables/ft_sentence_table_",crisis,".Rds")
  
  temp <- codings_wide_agreed %>% 
          filter(crisno==crisis) %>%
              group_by(crisno, final_event_ordering, crisno_sent, sentence) %>%
                summarize(codings_sentence = paste(codings_sentence, collapse="\n")) %>%
              ungroup() %>%
              dplyr::select(id=crisno_sent, sentence, codings_sentence)
    
  temp_ft <- temp %>%
              as_flextable() %>%
              colformat_md(j=3) %>% #There can be bad unicode characters in the sentence so make sure you only make the coded sentence markdown
              flextable::fontsize(size = 7, part = "all") %>%
              flextable::bg( i = which( 1:nrow(temp) %% 2 == 1)  , j=1:3, part = "body", bg = "#EFEFEF") %>%
              flextable::width(j = 1, width=0.3, unit = "in") %>%
              flextable::width(j = 2, width=4, unit = "in") %>%
              flextable::width(j = 3, width=4, unit = "in")

  temp_ft  %>% saveRDS(save_file)
}

c(196, 426) %>% sapply(FUN=function(x) icb_sentence_tables(x))


```

# Dyadic Mids


## Data Loads

```{r}




mid_df <- data.frame(
  stringsAsFactors = FALSE,
               act = c(1L,2L,3L,4L,5L,6L,7L,8L,
                       9L,10L,11L,12L,13L,14L,15L,16L,17L,18L,19L,
                       20L,21L,22L),
         act_label = c("1. None (1)",
                       "2. Threat to use force (2)","3. Threat to blockade (2)",
                       "4. Threat to occupy terr. (2)","5. Threat to declare war (2)",
                       "6. Threat to join war (2)","7. Show of troops (3)",
                       "8. Show of ships (3)","9. Show of planes (3)","10. Alert (3)",
                       "12. Mobilization (3)","13. Fortify border (3)",
                       "14. Border violation (4)","15. Blockade (4)",
                       "16. Occupation of territory (4)","17. Seizure (4)","18. Clash (4)",
                       "19. Raid (4)","20. Declaration of war (4)",
                       "22. Begin interstate war (5)","23. Join interstate war (5)",
                       "24. Use CBR Weapons (5)")
) %>% mutate(act_label= act_label %>% str_replace('[0-9]{1,2}\\. ','') %>% str_replace('\\([1-9]\\)','') )

mid_df2 <- data.frame(
  stringsAsFactors = FALSE,
                outcome = c(0L, 1L, 2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L),
                outcome_label = c("0. Ongoing MID",
                       "1. Victory for State A","2. Victory for state B",
                       "3. Yield by State A","4. Yield by State B","5. Stalemate",
                       "6. Compromise","7. Released (for seizures)","8. Unclear",
                       "-9 Missing")
) %>% mutate(outcome_label= outcome_label %>% str_replace('[0-9]{1,2}\\. ','') %>% str_replace('\\([1-9]\\)','') )

dyadic_mid <- read_csv(paste0(here::here(), "/replication_paper/data/in/dyadic_mid_4.02.csv"))

dyadic_mid_clean <- dyadic_mid %>% distinct() %>%
                      left_join(actor_translator %>% dplyr::select(statea=COWcode, actor_1=QCode_name, actor_1_qcode=QCode)) %>%
                      left_join(actor_translator %>% dplyr::select(stateb=COWcode, actor_2=QCode_name, actor_2_qcode=QCode)) %>%
                      left_join(mid_df  %>% dplyr::select( mid5hiacta=act , leaf_1=act_label )) %>%
                      left_join(mid_df  %>% dplyr::select( mid5hiactb=act , leaf_2=act_label )) %>%
                      left_join(mid_df2  %>% dplyr::select( outcome=outcome , outcome_label=outcome_label )) 

```

##  Mids plots

```{r}


mids_metro_plots <- function(crisis=196, prune_rare=T){

  print(crisis)
  #crisis=426
  plot_title <- crisno_name_years %>% filter(crisno==crisis) %>% mutate(title="Crisis #" %>% paste0(crisno, " ", crisname, " (", yrtrig, "-",yrterm,")")) %>% pull(title)
  save_mids_file <- paste0(here::here(), "/replication_paper/figures/metro_plots/p_mids_metro_plot_",crisis,".Rds")

  year_start <-icb_crises[icb_crises$crisno==crisis,]$yrtrig
  year_end   <- icb_crises[icb_crises$crisno==crisis,]$yrterm 
  
  start_simple <- icb_crises[icb_crises$crisno==crisis,]$start_simple
  end_simple <- icb_crises[icb_crises$crisno==crisis,]$end_simple

  actor_sent_counts <- 
    bind_rows(
        codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(sent=final_event_ordering,actor=think_actor_a),
        codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(sent=final_event_ordering,actor=say_actor_a),
        codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(sent=final_event_ordering,actor=say_actor_b),
        codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(sent=final_event_ordering,actor=do_actor_a),
        codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(sent=final_event_ordering,actor=do_actor_b)
      ) %>% 
        na.omit() %>%
        mutate(actor = strsplit(as.character(actor), ";")) %>% unnest(actor) %>% distinct() %>% count(actor) %>% arrange(n %>% desc() )
  

  dyadic_mid_clean_subset <- dyadic_mid_clean %>%
                             filter( actor_1_qcode %in% actor_sent_counts$actor & actor_2_qcode %in% actor_sent_counts$actor ) %>%
                             filter(strtyr>=year_start & endyear<=year_end) 
  dim(dyadic_mid_clean_subset) #
  if(nrow(dyadic_mid_clean_subset)==0 | 
     (c(dyadic_mid_clean_subset$namea,dyadic_mid_clean_subset$nameb) %>% na.omit() %>% unique() %>%  length())<2  #Reject if not 2 actors
     ){
    print("No mids events for this crisis")
    return()
  }
    
  dyadic_mid_clean_dyad <- 
    bind_rows(
      dyadic_mid_clean_subset %>% dplyr::select(year=strtyr,month=strtmnth,day=strtday, actor_1,actor_2, leaf=leaf_1) , #
      dyadic_mid_clean_subset %>% dplyr::select(year=endyear,month=endmnth,day=endday, actor_1,actor_2, leaf=outcome_label)
  ) %>% mutate(leaf=ifelse(leaf=="Yield by State A" , "Yield to",leaf)) %>%
    filter(!leaf %in% "Yield by State B") %>%
    mutate(sent= ( year+(month/12)+(day/31/1000) ) %>% rank() %>% round())
  


  g <- make_empty_graph(n = 0, directed = TRUE)
    #graph_from_data_frame(vertices=nodes) #relations, directed=TRUE, 
  
  codings_wide_agreed_subset_diad <- dyadic_mid_clean_dyad %>% dplyr::select(year, month, sent=sent, actor_1=actor_1, actor_2=actor_2 ) %>% distinct()
  #Order actors by how many interactions they have together
  temp <- codings_wide_agreed_subset_diad  %>% dplyr::select(-year, -month) %>% arrange(actor_1, actor_2) %>% distinct()
  
  temp2 <- bind_rows(
    temp,
    temp %>% setNames(c("story_date", "actor_2", "actor_1" ))
  ) %>% count(actor_1, actor_2) %>% arrange(actor_1, actor_2) %>% arrange(n)
  
  temp2_wide <- temp2 %>% pivot_wider(id_cols=c(actor_1), names_from=actor_2, values_from=n) %>% mutate_if(is.numeric, tidyr::replace_na, 0) %>% as.data.frame()
  rownames(temp2_wide) <- temp2_wide$actor_1
  temp2_wide$actor_1 <- NULL
  temp2_wide <- temp2_wide %>% as.matrix()
  temp2_wide <- 1 - (temp2_wide/max(temp2_wide))
  temp2_wide <- temp2_wide[sort(rownames(temp2_wide)), sort(colnames(temp2_wide))]
  hc <- hclust(temp2_wide %>% as.dist(), method="single")
  
  temp_list <- list()
  for(i in 1:nrow(temp2_wide)){
    temp_list[[as.character(i)]] <- cutree(hc, k=i)
  }
  
  #ideal_ordering <- bind_rows(temp_list) %>% t() %>% as.data.frame() %>% apply(1, paste, collapse='') %>% sort() %>% names() #this will break with more than 9
  #  arrange(across(starts_with("V")))
  ideal_ordering <- hc$labels[hc$order] #There's a bug here, put all the isolated nodes by themselves first
  
  #####Nodes
  codings_wide_agreed_subset_nodes <- 
            bind_rows(
                      codings_wide_agreed_subset_diad %>% dplyr::select(year, month, sent=sent, actor=actor_1) ,
                      codings_wide_agreed_subset_diad %>% dplyr::select(year, month, sent=sent, actor=actor_2) 
            ) %>% na.omit() %>% distinct()  %>% arrange(actor,sent) %>% mutate(actor_sent= actor %>% paste0("_", str_pad(sent, 2, pad = "0") )) %>% #don't na omit this one
            mutate(x=actor %>% factor(levels=actor %>% unique() %>% setdiff(ideal_ordering) %>% c(ideal_ordering)) %>% as.numeric() *100 ,
                   y=sent*-1 *100)
  
  actors=codings_wide_agreed_subset_nodes$actor %>% unique() %>% as.factor()
  actor_colors = c(brewer.pal(n=11, "Dark2"), brewer.pal(n=11, "Set1"))[1:length(actors)] #ok so pick a bewer pallet with lots of values and then assign it to specific values
  names(actor_colors) = levels(actors)
  
  

  date_sineposts <- codings_wide_agreed_subset_nodes  %>%
                    mutate(x=max(x)+50) %>%
                    dplyr::select(sent, year, month,x,y) %>%
                    na.omit() %>% 
                    distinct() %>%  
                    mutate(sent=as.numeric(sent)) %>% arrange(sent) %>%
                    mutate(year_float=year+(month/12)) %>%
                    group_by(sent) %>%
                    filter(year_float==min(year_float)) %>%
                    ungroup() %>% as.data.frame() %>%
                    filter( row_number()==1 |  ( year_float > lag(year_float)  ) )  %>%
                    filter(!duplicated(year_float ) ) %>%
                    mutate(label=paste0(year,"-",month.abb[month]))
  
    
  ####Actor lavels
  codings_wide_agreed_subset_nodes_min <- 
    codings_wide_agreed_subset_nodes %>% group_by(actor) %>% filter(sent==sent %>% min()) %>% ungroup() %>%
    #left_join(dictionary_actors_labels %>% filter(crisno==crisis) %>% distinct() %>% rename(actor=value_normalized) ) %>% #only need to do for our q codes
    #rename(qcode=actor, actor=value_normalized_label) %>%
    rowwise() %>%
    mutate(actor=actor %>% stringi::stri_wrap(width=15) %>% paste0(collapse='\n'))
  
  
  for(i in 1:nrow(codings_wide_agreed_subset_nodes)){
    g <- g %>%  add_vertices(1, name=codings_wide_agreed_subset_nodes$actor_sent[i],
                                actor = codings_wide_agreed_subset_nodes$actor[i], 
                                sent = codings_wide_agreed_subset_nodes$sent[i]  ) #, type = nodes$type[i] #, leaf = nodes$leaf[i]
  }
  
  xy <- cbind(codings_wide_agreed_subset_nodes$x, codings_wide_agreed_subset_nodes$y )
  
  
  #####Time Edges
  codings_wide_agreed_subset_nodes_edges_time <- cbind(codings_wide_agreed_subset_nodes, bind_rows(codings_wide_agreed_subset_nodes[-1,],codings_wide_agreed_subset_nodes[1,] ) ) %>% janitor::clean_names() %>% filter(actor==actor_2 & sent_2>sent) %>% distinct()
  
  g <- g %>% 
       add_edges(codings_wide_agreed_subset_nodes_edges_time[,c('actor_sent','actor_sent_2')] %>% as.matrix() %>% t() %>% as.vector(),
                 actor=codings_wide_agreed_subset_nodes_edges_time$actor, timeedge=T, leaf='', eventedge=F)
  
  
  ######Directed
  codings_wide_agreed_subset_directed <- 
            dyadic_mid_clean_dyad %>% 
            dplyr::select(sent=sent, actor_1=actor_1, actor_2=actor_2, leaf ) %>% distinct() %>%
            mutate(actor_sent_1= actor_1 %>% paste0("_", str_pad(sent, 2, pad = "0") )) %>%
            mutate(actor_sent_2= actor_2 %>% paste0("_", str_pad(sent, 2, pad = "0") )) %>%
            group_by(sent,actor_1, actor_sent_1,actor_sent_2) %>%
              summarise(leaf=paste(leaf, collapse="\n") %>% tolower() ) #%>%
            #filter(actor_sent_2 %>% str_detect("Q30") | actor_sent_1 %>% str_detect("Q30"))
  
  g <- g %>% add_edges(codings_wide_agreed_subset_directed[,c('actor_sent_1','actor_sent_2')] %>% as.matrix() %>% t() %>% as.vector(),
                       timeedge=F, 
                       leaf=codings_wide_agreed_subset_directed$leaf, 
                       eventedge=T,
                       actor=codings_wide_agreed_subset_directed$actor_1) 

    p_mids_metro_map <- g %>%  
          ggraph("manual",x=xy[,1],y=xy[,2]) +  #geom_edge_parallel
    
          #Time edges
          geom_edge_link(aes(
                          edge_colour=actor,
                          filter=timeedge==T
                          ),
                          edge_width=0.1, 
                          show.legend = F
                         ) +
          geom_node_point(aes(color=actor),size=1,stroke=0.5) +
    
          #Event edges
          #geom_path(data = hbundle, aes(x, y, group = group), col = "#9d0191", size = 0.05) +
          geom_edge_arc(aes(  
                              colour=actor,
                              label=leaf,
                              filter=eventedge==T #& bundle_count==1
                              ),
                          vjust = -0.75,
                          lineheight = .75,
                          sep = unit(1, 'mm'), 
                          edge_width=0.25, 
                          show.legend = F,
                          arrow = arrow(length = unit(2, 'mm')),
                          label_size=3,
                          check_overlap=T,
                          start_cap = circle(3, 'mm'),
                          end_cap = circle(3, 'mm'),
                          angle_calc = 'along'
                         ) +

              #Not in phoenix
              #geom_text(data=fatalities %>% filter(interact_fatalities>1), aes(x=x+4,y=y, size=interact_fatalities+1), color='black', label='☠', angle=0) + 
              #Not in phoenix
              #geom_text(data=codings_wide_agreed_subset_monad, aes(x=x,y=y, label=leaf), nudge_y=40, angle=0, lineheight = .75, size=3) +
              geom_text(data=date_sineposts, aes(x=x,y=y, label=label), color="grey", nudge_y=0, angle=0, size=4, lineheight = .75, fontface = "bold",check_overlap = T) + #-45
              geom_text(data=codings_wide_agreed_subset_nodes_min, aes(x=x,y=y, label=actor, color=actor), nudge_y=150, angle=0, size=4, lineheight = .75, fontface = "bold") + #-45
              scale_color_manual(values = actor_colors)  +
              scale_edge_color_manual(values = actor_colors) +
              #theme_bw() + 
              #labs( title = plot_title ) +
              theme_graph() +
              theme(legend.position = "none") #+
              #Not in phoenix
              #ggimage::geom_image(data= units, aes(x=x+offeset,y=y-30, image = IMAGE), size = 0.015)
    
    
  p_mids_metro_map$sentence_count <- codings_wide_agreed_subset_nodes$sent %>% unique() %>% length()
  p_mids_metro_map$actor_colors <- actor_colors
  p_mids_metro_map$dyadic_mid_clean <- dyadic_mid_clean
  
  p_mids_metro_map %>% saveRDS(save_mids_file)
}

c(196, 426) %>% sapply(FUN=function(x) mids_metro_plots(x))

  
```

# MIDs Incidents

## Load data

```{r}


mid_df <- data.frame(
  stringsAsFactors = FALSE,
               act = c(1L,2L,3L,4L,5L,6L,7L,8L,
                       9L,10L,11L,12L,13L,14L,15L,16L,17L,18L,19L,
                       20L,21L,22L),
         act_label = c("1. None (1)",
                       "2. Threat to use force (2)","3. Threat to blockade (2)",
                       "4. Threat to occupy terr. (2)","5. Threat to declare war (2)",
                       "6. Threat to join war (2)","7. Show of troops (3)",
                       "8. Show of ships (3)","9. Show of planes (3)","10. Alert (3)",
                       "12. Mobilization (3)","13. Fortify border (3)",
                       "14. Border violation (4)","15. Blockade (4)",
                       "16. Occupation of territory (4)","17. Seizure (4)","18. Clash (4)",
                       "19. Raid (4)","20. Declaration of war (4)",
                       "22. Begin interstate war (5)","23. Join interstate war (5)",
                       "24. Use CBR Weapons (5)") 
) %>% mutate(act_label= act_label %>% str_replace('[0-9]{1,2}\\. ','') %>% str_replace('\\([1-9]\\)','') %>% trimws() )

mid_df2 <- data.frame(
  stringsAsFactors = FALSE,
                outcome = c(0L, 1L, 2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L),
                outcome_label = c("0. Ongoing MID",
                       "1. Victory for State A","2. Victory for state B",
                       "3. Yield by State A","4. Yield by State B","5. Stalemate",
                       "6. Compromise","7. Released (for seizures)","8. Unclear",
                       "-9 Missing")
) %>% mutate(outcome_label= outcome_label %>% str_replace('[0-9]{1,2}\\. ','') %>% str_replace('\\([1-9]\\)','') )

mid_df3 <- data.frame(
  stringsAsFactors = FALSE,
          revtype1 = c(0L, 1L, 2L, 3L, 4L),
    revtype1_label = c("Not applicable","Territory",
                       "Policy","Regime/government","Other")
)

mid_df4 <- data.frame(
  stringsAsFactors = FALSE,
          fatality = c(0L, 1L, 2L, 3L, 4L, 5L, 6L),
    fatality_label = c("None","1-25 deaths",
                       "26-100 deaths","101-250 deaths","251-500 deaths",
                       "501-999 deaths","> 999 deaths")
)


midii <- readRDS(paste0(here::here(), '/replication_paper/data/in/MIDI_5.01.Rds'))
midip <- readRDS(paste0(here::here(), '/replication_paper/data/in/MIDIP_5.01.Rds'))

midip_clean <- midip %>% distinct() %>%
                      left_join(actor_translator %>% dplyr::select(ccode=COWcode, actor=QCode_name, actor_qcode=QCode)) %>%
                      left_join(mid_df  %>% dplyr::select( action=act , act_label=act_label )) %>%
                      left_join(mid_df3  %>% dplyr::select( revtype1=revtype1 , revtype1_label=revtype1_label ))  %>%
                      left_join(mid_df4  %>% dplyr::select( fatality=fatality , fatality_label=fatality_label )) 

#Create a dyadic list
temp1 <- midip_clean %>% 
         mutate(start=styear+((stmon*30)+stday)/365) %>%
         mutate(end=endyear+((endmon*30)+endday)/365) %>%
         dplyr::select(stday, stmon, styear, endday, start, end, incidnum, sidea, actor, actor_qcode,
                       act_label,revtype1_label,fatality_label) %>% arrange(incidnum, sidea, actor_qcode) %>% distinct()
temp2 <- temp1 %>% dplyr::select(stday, stmon, styear, endday, 
                                 start, end,incidnum, sidea_1=sidea, actor_1=actor, actor_1_qcode=actor_qcode,act_1_label=act_label,
                                 revtype1_1_label=revtype1_label,fatality_1_label=fatality_label) %>%
          full_join(temp1 %>% dplyr::select(start, end,incidnum, sidea_2=sidea, actor_2=actor, actor_2_qcode=actor_qcode,act_2_label=act_label,revtype1_2_label=revtype1_label,fatality_2_label=fatality_label
                                            )) %>%
          filter(sidea_1!=sidea_2) %>%
          mutate(actor_12_qcode=paste0(actor_1_qcode, "_", actor_2_qcode))
temp3 <- temp1 %>% dplyr::select(start, end,incidnum, sidea_1=sidea, actor_1=actor, actor_1_qcode=actor_qcode,
                                 act_1_label=act_label,revtype1_1_label=revtype1_label,fatality_1_label=fatality_label) %>%
          full_join(temp1 %>% dplyr::select(start, end,incidnum, sidea_2=sidea, actor_2=actor, actor_2_qcode=actor_qcode,act_2_label=act_label,revtype1_2_label=revtype1_label,fatality_2_label=fatality_label)) %>%
          filter(sidea_1!=sidea_2) %>%
          mutate(actor_12_qcode=paste0(actor_2_qcode, "_", actor_1_qcode))

midip_dyads <- bind_rows(temp2, temp3) 
  
```

## Plot

```{r}

mids_incidents_metro_plots <- function(crisis=196, prune_rare=T){

  print(crisis)
  #crisis=426
  save_mids_incidents_file <- paste0(here::here(), "/replication_paper/figures/metro_plots/p_mids_incidents_metro_plot_",crisis,".Rds")

  year_start <-icb_crises[icb_crises$crisno==crisis,]$yrtrig
  year_end   <- icb_crises[icb_crises$crisno==crisis,]$yrterm 
  
  start_simple <- icb_crises[icb_crises$crisno==crisis,]$start_simple
  end_simple <- icb_crises[icb_crises$crisno==crisis,]$end_simple

  dyad_sent_counts <- 
    bind_rows(
        codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(sent=final_event_ordering,actor_1_qcode=say_actor_a, actor_2_qcode=say_actor_b),
        codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(sent=final_event_ordering,actor_1_qcode=do_actor_a, actor_2_qcode=do_actor_b)
   )   %>% distinct() %>% na.omit()  %>% 
        mutate(actor_1_qcode = strsplit(as.character(actor_1_qcode), ";")) %>% unnest(actor_1_qcode) %>% distinct() %>%
        mutate(actor_2_qcode = strsplit(as.character(actor_2_qcode), ";")) %>% unnest(actor_2_qcode) %>% distinct() %>% 
        count(actor_1_qcode , actor_2_qcode) %>% arrange(desc(n))  %>%
          mutate(actor_12_qcode=paste0(actor_1_qcode, "_", actor_2_qcode))
  
  #What mids involve those dyads?
  relevant_incidnum <- midip_dyads %>% filter(actor_12_qcode %in% dyad_sent_counts$actor_12_qcode) %>% pull(incidnum) %>% unique()
  
  
  actor_sent_counts <- 
    bind_rows(
        codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(sent=final_event_ordering,actor=think_actor_a),
        codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(sent=final_event_ordering,actor=say_actor_a),
        codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(sent=final_event_ordering,actor=say_actor_b),
        codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(sent=final_event_ordering,actor=do_actor_a),
        codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(sent=final_event_ordering,actor=do_actor_b)
      ) %>% 
        na.omit() %>%
        mutate(actor = strsplit(as.character(actor), ";")) %>% unnest(actor) %>% distinct() %>% count(actor) %>% arrange(n %>% desc() )
  
  #Subset incients to be within the time frame and the right incidents and the right actors
  incident_mid_clean_subset <- midip_dyads %>%
                               filter( incidnum %in% relevant_incidnum ) %>% #a dispute with a relvant dyad
                               filter( actor_12_qcode %in% dyad_sent_counts$actor_12_qcode ) %>% #an actor in our data
                               filter(start>=year_start & end<=year_end+1) #allow for an extra year at the end
  
  #Reject if no rows or less than 2 actors
  dim(incident_mid_clean_subset) #
  if(nrow(incident_mid_clean_subset)==0 | 
     (c(incident_mid_clean_subset$actor_1,incident_mid_clean_subset$actor_2) %>% na.omit() %>% unique() %>% length())<2  #Reject if not 2 actors
     ){
    print("No mids events for this crisis")
    return()
  }
    
  #we can do pseudo dyads within incidum numbers

  
  dyadic_mid_clean_dyad <- 
    bind_rows(
      incident_mid_clean_subset %>% 
        mutate(label=
                 paste0( act_1_label %>% replace_na(''),", ", revtype1_2_label %>% replace_na('') ,", ", fatality_1_label %>% replace_na('')) %>% trimws() %>%
                 str_replace_all("None|Not applicable","") %>% trimws() %>% str_replace("^,|,$|","") %>% trimws()
               ) %>%
        dplyr::select(stday, stmon, styear, endday, start,   end, start, actor_1=actor_1,actor_2=actor_2, leaf=label) 
  ) %>%
    mutate(sent= start %>% rank() %>% round())
  
  g <- make_empty_graph(n = 0, directed = TRUE)
    #graph_from_data_frame(vertices=nodes) #relations, directed=TRUE, 
  
  codings_wide_agreed_subset_diad <- dyadic_mid_clean_dyad %>% dplyr::select(styear, stmon, sent=sent, actor_1=actor_1, actor_2=actor_2 ) %>% distinct()
  #Order actors by how many interactions they have together
  temp <- codings_wide_agreed_subset_diad  %>% dplyr::select(-styear, -stmon) %>% arrange(actor_1, actor_2) %>% distinct()
  
  temp2 <- bind_rows(
    temp,
    temp %>% setNames(c("story_date", "actor_2", "actor_1" ))
  ) %>% count(actor_1, actor_2) %>% arrange(actor_1, actor_2) %>% arrange(n)
  
  temp2_wide <- temp2 %>% pivot_wider(id_cols=c(actor_1), names_from=actor_2, values_from=n) %>% mutate_if(is.numeric, tidyr::replace_na, 0) %>% as.data.frame()
  rownames(temp2_wide) <- temp2_wide$actor_1
  temp2_wide$actor_1 <- NULL
  temp2_wide <- temp2_wide %>% as.matrix()
  temp2_wide <- 1 - (temp2_wide/max(temp2_wide))
  temp2_wide <- temp2_wide[sort(rownames(temp2_wide)), sort(colnames(temp2_wide))]
  hc <- hclust(temp2_wide %>% as.dist(), method="single")
  

  #ideal_ordering <- bind_rows(temp_list) %>% t() %>% as.data.frame() %>% apply(1, paste, collapse='') %>% sort() %>% names() #this will break with more than 9
  #  arrange(across(starts_with("V")))
  ideal_ordering <- hc$labels[hc$order] #There's a bug here, put all the isolated nodes by themselves first
  
  #####Nodes
  codings_wide_agreed_subset_nodes <- 
            bind_rows(
                      codings_wide_agreed_subset_diad %>% dplyr::select(styear, stmon, sent=sent, actor=actor_1) ,
                      codings_wide_agreed_subset_diad %>% dplyr::select(styear, stmon, sent=sent, actor=actor_2) 
            ) %>% na.omit() %>% distinct()  %>% arrange(actor,sent) %>% mutate(actor_sent= actor %>% paste0("_", str_pad(sent, 2, pad = "0") )) %>% #don't na omit this one
            mutate(x=actor %>% factor(levels=actor %>% unique() %>% setdiff(ideal_ordering) %>% c(ideal_ordering)) %>% as.numeric() *100 ,
                   y=sent*-1 *100)
  
  actors=codings_wide_agreed_subset_nodes$actor %>% unique() %>% as.factor()
  actor_colors = c(brewer.pal(n=11, "Dark2"), brewer.pal(n=11, "Set1"))[1:length(actors)] #ok so pick a bewer pallet with lots of values and then assign it to specific values
  names(actor_colors) = levels(actors)
  

  date_sineposts <- codings_wide_agreed_subset_nodes  %>%
                    mutate(x=max(x)+50) %>%
                    dplyr::select(sent, point_in_time_year=styear, point_in_time_month=stmon,x,y) %>%
                    na.omit() %>% 
                    distinct() %>%  
                    mutate(sent=as.numeric(sent)) %>% arrange(sent) %>%
                    mutate(year_float=point_in_time_year+(point_in_time_month/12)) %>%
                    group_by(sent) %>%
                    filter(year_float==min(year_float)) %>%
                    ungroup() %>% as.data.frame() %>%
                    filter( row_number()==1 |  ( year_float > lag(year_float)  ) )  %>%
                    filter(!duplicated(year_float ) ) %>%
                    mutate(label=paste0(point_in_time_year,"-",month.abb[point_in_time_month]))
    
    
    
  ####Actor levels
  codings_wide_agreed_subset_nodes_min <- 
    codings_wide_agreed_subset_nodes %>% group_by(actor) %>% filter(sent==sent %>% min()) %>% ungroup() %>%
    #left_join(dictionary_actors_labels %>% filter(crisno==crisis) %>% distinct() %>% rename(actor=value_normalized) ) %>% #only need to do for our q codes
    #rename(qcode=actor, actor=value_normalized_label) %>%
    rowwise() %>%
    mutate(actor=actor %>% stringi::stri_wrap(width=15) %>% paste0(collapse='\n'))
  
  
  for(i in 1:nrow(codings_wide_agreed_subset_nodes)){
    g <- g %>%  add_vertices(1, name=codings_wide_agreed_subset_nodes$actor_sent[i],
                                actor = codings_wide_agreed_subset_nodes$actor[i], 
                                sent = codings_wide_agreed_subset_nodes$sent[i]  ) #, type = nodes$type[i] #, leaf = nodes$leaf[i]
  }
  
  xy <- cbind(codings_wide_agreed_subset_nodes$x, codings_wide_agreed_subset_nodes$y )
  
  
  #####Time Edges
  codings_wide_agreed_subset_nodes_edges_time <- cbind(codings_wide_agreed_subset_nodes, bind_rows(codings_wide_agreed_subset_nodes[-1,],codings_wide_agreed_subset_nodes[1,] ) ) %>% janitor::clean_names() %>% filter(actor==actor_2 & sent_2>sent) %>% distinct()
  
  g <- g %>% 
       add_edges(codings_wide_agreed_subset_nodes_edges_time[,c('actor_sent','actor_sent_2')] %>% as.matrix() %>% t() %>% as.vector(),
                 actor=codings_wide_agreed_subset_nodes_edges_time$actor, timeedge=T, leaf='', eventedge=F)
  
  
  ######Directed
  codings_wide_agreed_subset_directed <- 
            dyadic_mid_clean_dyad %>% 
            dplyr::select(sent=sent, actor_1=actor_1, actor_2=actor_2, leaf ) %>% distinct() %>%
            mutate(actor_sent_1= actor_1 %>% paste0("_", str_pad(sent, 2, pad = "0") )) %>%
            mutate(actor_sent_2= actor_2 %>% paste0("_", str_pad(sent, 2, pad = "0") )) %>%
            group_by(sent,actor_1, actor_sent_1,actor_sent_2) %>%
              summarise(leaf=paste(leaf, collapse="\n") %>% tolower() ) #%>%
            #filter(actor_sent_2 %>% str_detect("Q30") | actor_sent_1 %>% str_detect("Q30"))
  
  g <- g %>% add_edges(codings_wide_agreed_subset_directed[,c('actor_sent_1','actor_sent_2')] %>% as.matrix() %>% t() %>% as.vector(),
                       timeedge=F, 
                       leaf=codings_wide_agreed_subset_directed$leaf, 
                       eventedge=T,
                       actor=codings_wide_agreed_subset_directed$actor_1) 
  
  
  
    p_mids_incident_metro_map <- g %>%  
          ggraph("manual",x=xy[,1],y=xy[,2]) +  #geom_edge_parallel
    
          #Time edges
          geom_edge_link(aes(
                          edge_colour=actor,
                          filter=timeedge==T
                          ),
                          edge_width=0.1, 
                          show.legend = F
                         ) +
          geom_node_point(aes(color=actor),size=1,stroke=0.5) +
    
          #Event edges
          #geom_path(data = hbundle, aes(x, y, group = group), col = "#9d0191", size = 0.05) +
          geom_edge_arc(aes(  
                              colour=actor,
                              label=leaf,
                              filter=eventedge==T #& bundle_count==1
                              ),
                          vjust = -0.75,
                          lineheight = .75,
                          sep = unit(1, 'mm'), 
                          edge_width=0.25, 
                          show.legend = F,
                          arrow = arrow(length = unit(2, 'mm')),
                          label_size=3,
                          check_overlap=T,
                          start_cap = circle(3, 'mm'),
                          end_cap = circle(3, 'mm'),
                          angle_calc = 'along'
                         ) +

              #Not in phoenix
              #geom_text(data=fatalities %>% filter(interact_fatalities>1), aes(x=x+4,y=y, size=interact_fatalities+1), color='black', label='☠', angle=0) + 
              #Not in phoenix
              #geom_text(data=codings_wide_agreed_subset_monad, aes(x=x,y=y, label=leaf), nudge_y=40, angle=0, lineheight = .75, size=3) +
              geom_text(data=date_sineposts, aes(x=x,y=y, label=label), color="grey", nudge_y=0, angle=0, size=4, lineheight = .75, fontface = "bold",check_overlap = T) + #-45

              geom_text(data=codings_wide_agreed_subset_nodes_min, aes(x=x,y=y, label=actor, color=actor), nudge_y=150, angle=0, size=4, lineheight = .75, fontface = "bold") + #-45
              scale_color_manual(values = actor_colors)  +
              scale_edge_color_manual(values = actor_colors) +
              #theme_bw() + 
              #labs( title = plot_title ) +
              theme_graph() +
              theme(legend.position = "none") #+
              #Not in phoenix
              #ggimage::geom_image(data= units, aes(x=x+offeset,y=y-30, image = IMAGE), size = 0.015)
    
    
  p_mids_incident_metro_map$sentence_count <- codings_wide_agreed_subset_nodes$sent %>% unique() %>% length()
  p_mids_incident_metro_map$actor_colors <- actor_colors
  p_mids_incident_metro_map$incident_mid_clean_subset <- incident_mid_clean_subset
  
  p_mids_incident_metro_map %>% saveRDS(save_mids_incidents_file)
}

icb_crises %>% filter(yrtrig>=1990 & crisno %in% c(196, 426)) %>% pull(crisno) %>% unique()  %>% sapply(FUN=function(x) mids_incidents_metro_plots(x))

```


# ICB

## Data Loads

```{r}

#Note yemen 679 doesn't show up in this data
icb_df <- data.frame(
  stringsAsFactors = FALSE,
          icb_name = c("Afghanistan","Albania",
                       "Algeria","Andorra","Angola","Antigua & Barbuda",
                       "Argentina","Armenia","Australia","Austria","Azerbaijan",
                       "Bahamas","Bahrain","Bangladesh","Barbados","Belarus",
                       "Belgium","Belize","Benin (Dahomey)","Bhutan","Bolivia",
                       "Bosnia","Botswana","Brazil","Brunei","Bulgaria",
                       "Burkina Faso (Upper Volta)","Burma (see Myanmar)",
                       "Burundi","Cambodia","Cameroon","Canada","Cape Verde",
                       "Central African Republic","Chad","Chile","China",
                       "China","Colombia","Comoros","Congo Brazzaville",
                       "Congo, Democratic","Costa Rica","Cote D’Ivoire","Croatia",
                       "Cuba","Cyprus","Czech Republic","Czechoslovakia",
                       "Dahomey (see Benin)","Denmark","Djibouti (Somalia Fr.)",
                       "Dominica","Dominican Republic","Ecuador","Egypt (UAR)",
                       "El Salvador","Equatorial Guinea","Eritrea","Estonia",
                       "Ethiopia","Federated States of Micronesia","Fiji",
                       "Finland","Formosa","France","French West Africa",
                       "Gabon","Gambia","Georgia",
                       "German Democratic Republic (East Germany)",
                       "Germany (German Federal Republic, West Germany)","Germany (Prussia)","Ghana",
                       "Great Britain (see United Kingdom)","Greece","Grenada","Guatemala",
                       "Guinea","Guinea Bissau","Guyana","Haiti","Hijaz (Hejaz)",
                       "Honduras","Hungary","Iceland","India","Indonesia",
                       "Iran","Iraq","Ireland (Eire)","Israel","Italy",
                       "Ivory Coast (see Cote D’Ivoire)","Jamaica","Japan",
                       "Jordan","Kazakhstan","Kenya","Korea","Kosovo","Kuwait",
                       "Kyrgyz Republic","Laos","Latvia","Lebanon","Lesotho",
                       "Liberia","Libya","Liechtenstein","Lithuania",
                       "Luxemberg","Macedonia","Madagascar (Malagasy Republic)",
                       "Malawi","Malaysia","Maldives","Mali","Malta",
                       "Marshall Islands","Mauritania","Mauritius","Mexico","Moldova",
                       "Monaco","Mongolia","Morocco","Mozambique",
                       "Myanmar (Burma)","Najd (Nejd)","Namibia (South West Africa)",
                       "Nepal","Netherlands","Nevis","New Zealand",
                       "Nicaragua","Niger","Nigeria",
                       "North Korea (People’s Republic of Korea)","Norway","Oman","Pakistan","Palau","Panama",
                       "Papua and New Guinea","Paraguay","Peru",
                       "Philippines","Poland","Portugal","Principe","Qatar",
                       "Republic of (Congo Kinshasa) (Zaire)","Rhodesia (see Zimbabwe)",
                       "Rumania","Russia (Soviet Union)","Rwanda",
                       "San Marino","Sao Tome","Saudi Arabia","Senegal",
                       "Serbia (see Yugoslavia)","Seychelles","Sierra Leone","Singapore",
                       "Slovakia","Slovenia","Solomons","Somalia",
                       "Somalia Fr. (see Djibouti)","South Africa",
                       "South Korea (Republic of Korea)","South Sudan",
                       "South West Africa (see Namibia)","Spain","Spanish Sahara (see Western Sahara)",
                       "Sri Lanka (Ceylon)","St. Kitts","St. Lucia",
                       "St. Vincent & The Grenadines","Sudan","Surinam","Swaziland",
                       "Sweden","Switzerland","Syria","Taiwan (China",
                       "Tajikistan","Tanzania","Thailand","Tibet","Togo",
                       "Trinidad & Tobago","Tunisia","Turkey","Turkmenistan","Uganda",
                       "Ukraine","United Arab Emirates",
                       "United Kingdom (Great Britain)","Upper Volta (see Burkina Faso)","Uruguay",
                       "USA","USSR (see Russia)","Uzbekistan","Vanuatu",
                       "Venezuela","Vichy France",
                       "Vietnam, Democratic Republic of (North Vietnam)","Vietnam, Republic of (South Vietnam)",
                       "Western Sahara (Spanish Sahara)","Western Samoa",
                       "Yemen (Arab Republic of Yemen, North Yemen)",
                       "Yemen, People’s Republic of (South Yemen)","Yugoslavia (Serbia)",
                       "Zambia","Zanzibar","Zimbabwe (Rhodesia)"),
       icb_letters = c("AFG","ALB","ALG","AND",
                       "ANG","AAB","ARG","ARM","AUL","AUS","AZE","BHM",
                       "BAH","BNG","BAR","BLR","BEL","BLZ","BEN","BHU","BOL",
                       "BOS","BOT","BRA","BRU","BUL","BFO",NA,"BUI",
                       "CAM","CAO","CAN","CAP","CEN","CHA","CHL",NA,"CHN",
                       "COL","COM","CON","DRC","COS","CDI","CRO","CUB",
                       "CYP","CZR","CZE",NA,"DEN","DJI","DMA","DOM",
                       "ECU","EGY","SAL","EQG","ERI","EST","ETH","FSM","FIJ",
                       "FIN","TAW","FRN","FWA","GAB","GAM","GRG","GDR",
                       "GFR","GMY","GHA",NA,"GRC","GRN","GUA","GUI",
                       "GNB","GUY","HAI","HIJ","HON","HUN","ICE","IND",
                       "INS","IRN","IRQ","IRE","ISR","ITA",NA,"JAM","JPN",
                       "JOR","KZK","KEN","KOR","KOS","KUW","KYR","LAO",
                       "LAT","LEB","LES","LBR","LIB","LIE","LIT","LUX",
                       "MAC","MAG","MAW","MAL","MAD","MLI","MLT","MSI",
                       "MAA","MAS","MEX","MLD","MNC","MON","MOR","MZM","MYA",
                       "NAJ","NAM","NEP","NTH","SKN","NEW","NIC","NIR",
                       "NIG","PRK","NOR","OMA","PAK","PAL","PAN","PNG",
                       "PAR","PER","PHI","POL","POR","STP","QAT","DRC",
                       NA,"RUM","RUS","RWA","SNM",NA,"SAU","SEN",NA,
                       "SEY","SIE","SIN","SLO","SLV","SOL","SOM",NA,"SAF",
                       "ROK","SSD",NA,"SPN",NA,"SRI",NA,"SLU","SVG",
                       "SUD","SUR","SWA","SWD","SWZ","SYR",NA,"TAJ","TAZ",
                       "THI","TBT","TOG","TRI","TUN","TUR","TKM","UGA",
                       "UKR","UAE","UKG",NA,"URU","USA",NA,"UZB","VAN",
                       "VEN","VFR","DRV","RVN","SPA","WSM","YEM","YPR",
                       "YUG","ZAM","ZAN","ZIM"),
          icb_code = c("700","339","615","232",
                       "540","058","160","371","900","305","373","031",
                       "692","771","053","370","211","080","434","760","145",
                       "346","571","140","835","355","439",NA,"516",
                       "811","471","020","402","482","483","155",NA,"710",
                       "100","581","484","490","094","437","344","040",
                       "352","316","315",NA,"390","522","054","042",
                       "130","651","092","411","531","366","530","987","950",
                       "375","713","220","480","481","420","372","265",
                       "260","255","452",NA,"350","55","090","438",
                       "404","110","041","671","091","310","395","750","850",
                       "630","645","205","666","325",NA,"051","740",
                       "663","705","501","730","347","690","703","812",
                       "367","660","570","450","620","223","368","212",
                       "343","580","553","820","781","432","338","983","435",
                       "590","070","359","221","712","600","541","775",
                       "672","565","790","210","060","920","093","436",
                       "475","731","385","698","770","986","095","910",
                       "150","135","840","290","235","403","694","490",NA,
                       "360","365","517","331",NA,"670","433",NA,"591",
                       "451","830","317","349","940","520",NA,"560",
                       "732","626",NA,"230",NA,"780",NA,"056","057","625",
                       "115","572","380","225","652",NA,"702","510",
                       "800","711","461","052","616","640","701","500",
                       "369","696","200",NA,"165","002",NA,"704","935",
                       "101","219","816","817","605","990","678","680",
                       "345","551","511","552")
)

df_IWCA <- data.frame(
  stringsAsFactors = FALSE,
              IWCA = c(1L, 2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L, 10L),
        IWCA_label = c("not an intra-war crisis (IWC)",
                       "Entry of a major actor into an ongoing war",
                       "Perceived high probability of a major actor entering a war",
                       "Exit of a major actor",
                       "Perceived high probability of major power exiting a war",
                       "Technological escalation of a war","Major non-technological escalation",
                       "Defeat in a significant battle","Internal deterioration","Other")
)

df_break <- 
data.frame(
  stringsAsFactors = FALSE,
             BREAK = c(1L, 2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L),
       BREAK_label = c("Verbal act","Political act",
                       "Economic act","External change",
                       "Other non-violent act",
                       "Internal verbal or physical challenge to regime or elite","Non-violent military act","Indirect violent act",
                       "Violent act")
)


#icbdy_20 <- read_tsv(here::here(), "/replication_paper/data/in/icbdy_20.dat")
icbdy_20 <- readRDS(paste0(here::here(), '/replication_paper/data/in/icbdy_20.Rds'))

icbdy_20_clean <- icbdy_20 %>%
                  left_join( icb_df %>% dplyr::select(STATEA=icb_code, actor_1=icb_name ) %>% mutate(STATEA=STATEA %>% as.numeric())  ) %>%
                  left_join( icb_df %>% dplyr::select(STATEB=icb_code, actor_2=icb_name ) %>% mutate(STATEB=STATEB %>% as.numeric())  ) %>%
                  left_join(df_IWCA %>% dplyr::select(IWCA=IWCA, IWCA_label=IWCA_label )  ) %>%
                  left_join(df_IWCA %>% dplyr::select(IWCB=IWCA, IWCB_label=IWCA_label )  )  

icb_diadic <- icbdy_20_clean %>% dplyr::select(CRISNO, NAMEA, NAMEB,  STATEA, STATEB, actor_1,actor_2, IWCA_label,IWCB_label) #%>% filter(is.na(actor_1) | is.na(actor_2))


icb2v14 <- read_csv(paste0(here::here(), "/replication_paper/data/in/icb2v14.csv"))


df_trigger <- data.frame(
  stringsAsFactors = FALSE,
            triggr = c(1L, 2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L),
                    triggr_label = c("Verbal act","Political act","Economic act",
                                     "External change","Other non-violent act",
                                     "Internal verbal or physical challenge to regime or elite",
                                     "Non-violent military act","Indirect violent act","Violent act")
              )

df_majres <- data.frame(
  stringsAsFactors = FALSE,
            majres = c(1L, 2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L),
                   majres_label = c("No response-inaction","Verbal act",
                                    "Political act","Economic act",
                                    "Other non-violent act",
                                    "Non-violent military act",
                                    "Multiple including non-violent military act",
                                    "Violent military act",
                                    "Multiple including violent military act")
             )

df_outcome <- 
data.frame(
  stringsAsFactors = FALSE,
            outcom = c(1L, 2L, 3L, 4L, 5L),
      outcom_label = c("Victory", "Compromise", "Stalemate", "Defeat", "Other")
)

df_outfor <- 
data.frame(
  stringsAsFactors = FALSE,
            outfor = c(1L,2L,3L,4L,5L,6L,7L,8L,
                       9L,10L,11L,12L,13L,14L,15L),
      outfor_label = c("Formal agreement - voluntary",
                       "Semi-formal agreement - voluntary",
                       "Tacit understanding","Unilateral - self","Unilateral - ally",
                       "Unilateral - adversary","Compliance","Imposed - imposer",
                       "Imposed - imposee","Spillover",
                       "Other - global organization intervention","Other - ally",
                       "Other - internal or non-state actor","Other - misc.","Faded")
)

icb2v14_clean <- icb2v14 %>% 
                 left_join(icb_df %>% dplyr::select(cracid=icb_code, actor_label=icb_name ) %>% mutate(cracid=cracid %>% as.numeric()) ) %>%  #you can't actually match on the letter codes you have to match on the numbers, uhhhhhg
                 left_join( df_trigger  ) %>% 
                 left_join( df_majres ) %>% 
                 left_join( df_outcome ) %>% 
                 left_join( df_outfor )

icb_monadic <-  
  bind_rows(
   icb2v14_clean%>% mutate(sent= yrtrig + tidyr::replace_na((motrig/12),0) + tidyr::replace_na(datrig/31/12,0) ) %>% mutate(type='start') %>% dplyr::select(year=yrtrig, month=motrig, crisno,type, sent, actor_label, leaf=triggr_label),
   icb2v14_clean %>% mutate(sent= yerres + tidyr::replace_na((monres/12),0) + tidyr::replace_na(dayres/31/12,0) ) %>% mutate(type='mid') %>% dplyr::select(year=yerres, month=monres, crisno,type, sent, actor_label, leaf=majres_label),
   icb2v14_clean %>% mutate(sent= yrterm + tidyr::replace_na((moterm/12),0) + tidyr::replace_na(daterm/31/12,0) ) %>% mutate(type='end') %>% dplyr::select(year=yrterm, month=moterm, crisno,type, sent, actor_label, leaf=outfor_label)
  ) %>% as.data.frame()


```



## ICB Function

```{r}

icb_metro_plots <- function(crisis=196, prune_rare=T){
      
    print(crisis)
    save_icb_file <- paste0(here::here(), "/replication_paper/figures/metro_plots/p_icb_metro_plot_",crisis,".Rds")
  
    icb_diadic_subset <- icb_diadic %>% filter(CRISNO==crisis) #Not all of them are diadic apparently
    icb_monadic_subset <- icb_monadic %>% rename(actor=actor_label) %>% filter(crisno==crisis) %>%
                       mutate(sent=sent %>% rank() %>% round()) %>% mutate(actor_sent= actor %>% paste0("_", str_pad(sent, 2, pad = "0") ))   %>% arrange(sent, actor)

    g <- make_empty_graph(n = 0, directed = TRUE)
      #graph_from_data_frame(vertices=nodes) #relations, directed=TRUE, 
    
    codings_wide_agreed_subset_diad <- bind_rows(
            icb_diadic_subset %>% dplyr::select(actor_1,actor_2) %>% left_join(icb_monadic_subset %>% filter(type=="start") %>% 
                                                                                 mutate(actor_1=actor) %>% dplyr::select(year, month,sent, actor_1,leaf) ) %>% rename(actor_2=actor_1,actor_1=actor_2),
            icb_diadic_subset %>% dplyr::select(actor_1,actor_2) %>% left_join(icb_monadic_subset %>% filter(type=="start") %>%
                                                                                 mutate(actor_2=actor) %>% dplyr::select(year, month,sent, actor_2,leaf) ),
            
            icb_diadic_subset %>% dplyr::select(actor_1,actor_2) %>% left_join(icb_monadic_subset %>% filter(type=="mid") %>%
                                                                                 mutate(actor_1=actor) %>% dplyr::select(year, month,sent, actor_1,leaf) ) %>% rename(actor_2=actor_1,actor_1=actor_2),
            icb_diadic_subset %>% dplyr::select(actor_1,actor_2) %>% left_join(icb_monadic_subset %>% filter(type=="mid") %>% 
                                                                                 mutate(actor_2=actor) %>% dplyr::select(year, month,sent, actor_2,leaf) ),
            
            icb_diadic_subset %>% dplyr::select(actor_1,actor_2) %>% left_join(icb_monadic_subset %>% filter(type=="end") %>% 
                                                                                 mutate(actor_1=actor) %>% dplyr::select(year, month,sent, actor_1,leaf) ) %>% rename(actor_2=actor_1,actor_1=actor_2),
            icb_diadic_subset %>% dplyr::select(actor_1,actor_2) %>% left_join(icb_monadic_subset %>% filter(type=="end") %>% 
                                                                                 mutate(actor_2=actor) %>% dplyr::select(year, month,sent, actor_2,leaf) ),
          
          ) %>% dplyr::select(year, month,sent, actor_1, actor_2, leaf) %>% distinct() %>% na.omit()
    
     if(nrow(codings_wide_agreed_subset_diad)==0){
      print("No dyadic icb rows skipping")
      return()
    }
    
    #Order actors by how many interactions they have together
    temp <- codings_wide_agreed_subset_diad  %>% dplyr::select(-year, -month) %>% arrange(actor_1, actor_2) %>% distinct()
    
    temp2 <- bind_rows(
      temp,
      temp %>% setNames(c("story_date", "actor_2", "actor_1" ))
    ) %>% count(actor_1, actor_2) %>% arrange(actor_1, actor_2) %>% arrange(n)
    
    temp2_wide <- temp2 %>% pivot_wider(id_cols=c(actor_1), names_from=actor_2, values_from=n) %>% mutate_if(is.numeric, tidyr::replace_na, 0) %>% as.data.frame()
    rownames(temp2_wide) <- temp2_wide$actor_1
    temp2_wide$actor_1 <- NULL
    temp2_wide <- temp2_wide %>% as.matrix()
    temp2_wide <- 1 - (temp2_wide/max(temp2_wide))
    temp2_wide <- temp2_wide[sort(rownames(temp2_wide)), sort(colnames(temp2_wide))]
    hc <- hclust(temp2_wide %>% as.dist(), method="single")
    
    temp_list <- list()
    for(i in 1:nrow(temp2_wide)){
      temp_list[[as.character(i)]] <- cutree(hc, k=i)
    }
    
    #ideal_ordering <- bind_rows(temp_list) %>% t() %>% as.data.frame() %>% apply(1, paste, collapse='') %>% sort() %>% names() #this will break with more than 9
    #  arrange(across(starts_with("V")))
    ideal_ordering <- hc$labels[hc$order] #There's a bug here, put all the isolated nodes by themselves first
    
    #####Nodes
    codings_wide_agreed_subset_nodes <- 
              bind_rows(
                        codings_wide_agreed_subset_diad %>% dplyr::select(year, month,sent=sent, actor=actor_1) ,
                        codings_wide_agreed_subset_diad %>% dplyr::select(year, month,sent=sent, actor=actor_2) 
              ) %>% na.omit() %>% distinct()  %>% arrange(actor,sent) %>% mutate(actor_sent= actor %>% paste0("_", str_pad(sent, 2, pad = "0") )) %>% #don't na omit this one
              mutate(x=actor %>% factor(levels=actor %>% unique() %>% setdiff(ideal_ordering) %>% c(ideal_ordering)) %>% as.numeric() *100 ,
                     y=sent*-1 *100)
    
    actors=codings_wide_agreed_subset_nodes$actor %>% unique() %>% as.factor()
    actor_colors = c(brewer.pal(n=11, "Dark2"), brewer.pal(n=11, "Set1"))[1:length(actors)] #ok so pick a bewer pallet with lots of values and then assign it to specific values
    names(actor_colors) = levels(actors)
    
    
    date_sineposts <- codings_wide_agreed_subset_nodes  %>%
                        mutate(x=max(x)+50) %>%
                        dplyr::select(sent, point_in_time_year=year, point_in_time_month=month,x,y) %>%
                        na.omit() %>% 
                        distinct() %>%  
                        mutate(sent=as.numeric(sent)) %>% arrange(sent) %>%
                        mutate(year_float=point_in_time_year+(point_in_time_month/12)) %>%
                        group_by(sent) %>%
                        filter(year_float==min(year_float)) %>%
                        ungroup() %>% as.data.frame() %>%
                        filter( row_number()==1 |  ( year_float > lag(year_float)  ) )  %>%
                        filter(!duplicated(year_float ) ) %>%
                        mutate(label=paste0(point_in_time_year,"-",month.abb[point_in_time_month]))
    
    ####Actor levels
    codings_wide_agreed_subset_nodes_min <- 
                  codings_wide_agreed_subset_nodes %>% group_by(actor) %>% filter(sent==sent %>% min()) %>% ungroup() %>%
                  #left_join(dictionary_actors_labels %>% filter(crisno==crisis) %>% distinct() %>% rename(actor=value_normalized) ) %>% #only need to do for our q codes
                  #rename(qcode=actor, actor=value_normalized_label) %>%
                  rowwise() %>%
                  mutate(actor=actor %>% stringi::stri_wrap(width=15) %>% paste0(collapse='\n'))
    
    
    for(i in 1:nrow(codings_wide_agreed_subset_nodes)){
      g <- g %>%  add_vertices(1, name=codings_wide_agreed_subset_nodes$actor_sent[i],
                                  actor = codings_wide_agreed_subset_nodes$actor[i], 
                                  sent = codings_wide_agreed_subset_nodes$sent[i]  ) #, type = nodes$type[i] #, leaf = nodes$leaf[i]
    }
    
    xy <- cbind(codings_wide_agreed_subset_nodes$x, codings_wide_agreed_subset_nodes$y )
    
    
    #####Time Edges
    codings_wide_agreed_subset_nodes_edges_time <- cbind(codings_wide_agreed_subset_nodes, bind_rows(codings_wide_agreed_subset_nodes[-1,],codings_wide_agreed_subset_nodes[1,] ) ) %>% janitor::clean_names() %>% filter(actor==actor_2 & sent_2>sent) %>% distinct()
    
    g <- g %>% 
         add_edges(codings_wide_agreed_subset_nodes_edges_time[,c('actor_sent','actor_sent_2')] %>% as.matrix() %>% t() %>% as.vector(),
                   actor=codings_wide_agreed_subset_nodes_edges_time$actor, timeedge=T, leaf='', eventedge=F)
    
    
    ######Directed
    codings_wide_agreed_subset_directed <- 
              codings_wide_agreed_subset_diad %>% 
              dplyr::select(sent=sent, actor_1=actor_1, actor_2=actor_2, leaf ) %>% distinct() %>%
              mutate(actor_sent_1= actor_1 %>% paste0("_", str_pad(sent, 2, pad = "0") )) %>%
              mutate(actor_sent_2= actor_2 %>% paste0("_", str_pad(sent, 2, pad = "0") )) %>%
              group_by(sent,actor_1, actor_sent_1,actor_sent_2) %>%
                summarise(leaf=paste(leaf, collapse="\n") %>% tolower() ) #%>%
              #filter(actor_sent_2 %>% str_detect("Q30") | actor_sent_1 %>% str_detect("Q30"))
    
    g <- g %>% add_edges(codings_wide_agreed_subset_directed[,c('actor_sent_1','actor_sent_2')] %>% as.matrix() %>% t() %>% as.vector(),
                         timeedge=F, 
                         leaf=codings_wide_agreed_subset_directed$leaf, 
                         eventedge=T,
                         actor=codings_wide_agreed_subset_directed$actor_1) 


    p_icb_metro_map <- g %>%  
          ggraph("manual",x=xy[,1],y=xy[,2]) +  #geom_edge_parallel
    
          #Time edges
          geom_edge_link(aes(
                          edge_colour=actor,
                          filter=timeedge==T
                          ),
                          edge_width=0.1, 
                          show.legend = F
                         ) +
          geom_node_point(aes(color=actor),size=1,stroke=0.5) +
    
          #Event edges
          #geom_path(data = hbundle, aes(x, y, group = group), col = "#9d0191", size = 0.05) +
          geom_edge_arc(aes(  
                              colour=actor,
                              label=leaf,
                              filter=eventedge==T #& bundle_count==1
                              ),
                          vjust = -0.75,
                          lineheight = .75,
                          sep = unit(1, 'mm'), 
                          edge_width=0.25, 
                          show.legend = F,
                          arrow = arrow(length = unit(2, 'mm')),
                          label_size=3,
                          check_overlap=T,
                          start_cap = circle(3, 'mm'),
                          end_cap = circle(3, 'mm'),
                          angle_calc = 'along'
                         ) +

              #Not in phoenix
              #geom_text(data=fatalities %>% filter(interact_fatalities>1), aes(x=x+4,y=y, size=interact_fatalities+1), color='black', label='☠', angle=0) + 
              #Not in phoenix
              #geom_text(data=codings_wide_agreed_subset_monad, aes(x=x,y=y, label=leaf), nudge_y=40, angle=0, lineheight = .75, size=3) +
              geom_text(data=date_sineposts, aes(x=x,y=y, label=label), color="grey", nudge_y=0, angle=0, size=4, lineheight = .75, fontface = "bold",check_overlap = T) + #-45
              geom_text(data=codings_wide_agreed_subset_nodes_min, aes(x=x,y=y, label=actor, color=actor), nudge_y=150, angle=0, size=4, lineheight = .75, fontface = "bold") + #-45
              scale_color_manual(values = actor_colors)  +
              scale_edge_color_manual(values = actor_colors) +
              #theme_bw() + 
              #labs( title = plot_title ) +
              theme_graph() +
              theme(legend.position = "none") #+
              #Not in phoenix
              #ggimage::geom_image(data= units, aes(x=x+offeset,y=y-30, image = IMAGE), size = 0.015)
    
        
      p_icb_metro_map$sentence_count <- codings_wide_agreed_subset_nodes$sent %>% unique() %>% length()
      p_icb_metro_map$actor_colors <- actor_colors
      p_icb_metro_map$icb_monadic_subset <- icb_monadic_subset
      
      p_icb_metro_map %>% saveRDS(save_icb_file)
      
}

c(196, 426) %>% sapply(FUN=function(x) icb_metro_plots(x))


```


# GED

## Data Loads

```{r}

df1 <- data.frame(
        stringsAsFactors = FALSE,
        type_of_violence = c(1L, 2L, 3L),
                               type_of_violence_label = c("state-based conflict","non-state conflict","one-sided violence")
)

ged211 <- read_csv(paste0(here::here(), "/replication_paper/data/ignore/ged/ged211.csv"))

target_file <- paste0(here::here(),"/replication_paper/data/in/icb_manual_recoding_master_sheet.xlsx")
actor_translator    <- readxl::read_excel(target_file, sheet="actor_translator")

ged211_clean <- ged211 %>%
                left_join(actor_translator %>% dplyr::select(side_a_new_id=UCDPcode,actor_1=QCode_name, actor_1_qcode=QCode) ) %>%
                left_join(actor_translator %>% dplyr::select(side_b_new_id=UCDPcode,actor_2=QCode_name, actor_2_qcode=QCode) ) %>%
                filter(!is.na(actor_1_qcode) & !is.na(actor_2_qcode)) %>%
                mutate(actor_12_qcode=paste0(actor_1_qcode,"_",actor_2_qcode)) %>%
                dplyr::select(-source_office, -source_date, -source_headline, -source_original)

#There's only 11 that overlap
#Q1009_Q1033   Q148_Q668   Q424_Q869   Q668_Q843   Q736_Q419   Q794_Q801   Q796_Q817    Q804_Q30  Q958_Q1049   Q977_Q986   Q986_Q115 
#          9           2          24        1049          26          67          80           2          27           2          34 
          
```

## Ged Plots

```{r}

ucdp_ged_metro_plots <- function(crisis=466, prune_rare=T){

    print(crisis)
    #crisis=426
    save_ucdp_incidents_file <- paste0(here::here(), "/replication_paper/figures/metro_plots/p_ucdp_metro_plot_",crisis,".Rds")
  
    year_start <-icb_crises[icb_crises$crisno==crisis,]$yrtrig
    year_end   <- icb_crises[icb_crises$crisno==crisis,]$yrterm 
    
    start_simple <- icb_crises[icb_crises$crisno==crisis,]$start_simple
    end_simple <- icb_crises[icb_crises$crisno==crisis,]$end_simple
  
    dyad_sent_counts <- 
      bind_rows(
          codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(sent=final_event_ordering,actor_1_qcode=say_actor_a, actor_2_qcode=say_actor_b),
          codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(sent=final_event_ordering,actor_1_qcode=do_actor_a, actor_2_qcode=do_actor_b)
     )   %>% distinct() %>% na.omit()  %>% 
          mutate(actor_1_qcode = strsplit(as.character(actor_1_qcode), ";")) %>% unnest(actor_1_qcode) %>% distinct() %>%
          mutate(actor_2_qcode = strsplit(as.character(actor_2_qcode), ";")) %>% unnest(actor_2_qcode) %>% distinct() %>% 
          count(actor_1_qcode , actor_2_qcode) %>% arrange(desc(n))  %>%
            mutate(actor_12_qcode=paste0(actor_1_qcode, "_", actor_2_qcode))
  
    actor_sent_counts <- 
      bind_rows(
          codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(sent=final_event_ordering,actor=think_actor_a),
          codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(sent=final_event_ordering,actor=say_actor_a),
          codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(sent=final_event_ordering,actor=say_actor_b),
          codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(sent=final_event_ordering,actor=do_actor_a),
          codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(sent=final_event_ordering,actor=do_actor_b)
        ) %>% 
          na.omit() %>%
          mutate(actor = strsplit(as.character(actor), ";")) %>% unnest(actor) %>% distinct() %>% count(actor) %>% arrange(n %>% desc() )
    
    #Subset incients to be within the time frame and the right incidents and the right actors
    incident_ucdp_clean_subset <- ged211_clean %>%
                                   filter( actor_12_qcode %in% dyad_sent_counts$actor_12_qcode ) %>% #an actor in our data
                                   filter(year>=year_start & year<=year_end) #allow for an extra year at the end

  #Reject if no rows or less than 2 actors
  dim(incident_ucdp_clean_subset) #
  if(nrow(incident_ucdp_clean_subset)==0 | 
     (c(incident_ucdp_clean_subset$actor_1,incident_ucdp_clean_subset$actor_2) %>% na.omit() %>% unique() %>% length())<2  #Reject if not 2 actors
     ){
    print("No mids events for this crisis")
    return()
  }
    
  #we can do pseudo dyads within incidum numbers
  dyadic_ucdp_clean_dyad <- 
    bind_rows(
      
      #A killed B
      incident_ucdp_clean_subset %>% 
        filter(gwnob==country_id) %>% #happened in B
        mutate(label= paste0( best, " deaths"  ) %>% trimws()  ) %>% dplyr::select(date_start, actor_1=actor_1,actor_2=actor_2, leaf=label),
      #B killed A
      incident_ucdp_clean_subset %>% 
        filter(gwnoa==country_id) %>% #happened in A
        mutate(label= paste0( best, " deaths"  ) %>% trimws()  ) %>% dplyr::select(date_start, actor_1=actor_2,actor_2=actor_1, leaf=label) 
      
  ) %>% distinct() %>%
    mutate(sent= date_start %>% rank() %>% round())
  
  g <- make_empty_graph(n = 0, directed = TRUE)
    #graph_from_data_frame(vertices=nodes) #relations, directed=TRUE, 
  
  codings_wide_agreed_subset_diad <- dyadic_ucdp_clean_dyad %>% dplyr::select(sent=sent, actor_1=actor_1, actor_2=actor_2 ) %>% distinct()
  #Order actors by how many interactions they have together
  temp <- codings_wide_agreed_subset_diad  %>% arrange(actor_1, actor_2) %>% distinct()
  
  temp2 <- bind_rows(
    temp,
    temp %>% setNames(c("story_date", "actor_2", "actor_1" ))
  ) %>% count(actor_1, actor_2) %>% arrange(actor_1, actor_2) %>% arrange(n)
  
  temp2_wide <- temp2 %>% pivot_wider(id_cols=c(actor_1), names_from=actor_2, values_from=n) %>% mutate_if(is.numeric, tidyr::replace_na, 0) %>% as.data.frame()
  rownames(temp2_wide) <- temp2_wide$actor_1
  temp2_wide$actor_1 <- NULL
  temp2_wide <- temp2_wide %>% as.matrix()
  temp2_wide <- 1 - (temp2_wide/max(temp2_wide))
  temp2_wide <- temp2_wide[sort(rownames(temp2_wide)), sort(colnames(temp2_wide))]
  hc <- hclust(temp2_wide %>% as.dist(), method="single")
  

  #ideal_ordering <- bind_rows(temp_list) %>% t() %>% as.data.frame() %>% apply(1, paste, collapse='') %>% sort() %>% names() #this will break with more than 9
  #  arrange(across(starts_with("V")))
  ideal_ordering <- hc$labels[hc$order] #There's a bug here, put all the isolated nodes by themselves first
  
  #####Nodes
  codings_wide_agreed_subset_nodes <- 
            bind_rows(
                      codings_wide_agreed_subset_diad %>% dplyr::select(sent=sent, actor=actor_1) ,
                      codings_wide_agreed_subset_diad %>% dplyr::select(sent=sent, actor=actor_2) 
            ) %>% na.omit() %>% distinct()  %>% arrange(actor,sent) %>% mutate(actor_sent= actor %>% paste0("_", str_pad(sent, 2, pad = "0") )) %>% #don't na omit this one
            mutate(x=actor %>% factor(levels=actor %>% unique() %>% setdiff(ideal_ordering) %>% c(ideal_ordering)) %>% as.numeric() *100 ,
                   y=sent*-1 *100)
  
  actors=codings_wide_agreed_subset_nodes$actor %>% unique() %>% as.factor()
  actor_colors = c(brewer.pal(n=11, "Dark2"), brewer.pal(n=11, "Set1"))[1:length(actors)] #ok so pick a bewer pallet with lots of values and then assign it to specific values
  names(actor_colors) = levels(actors)
  

  ####Actor levels
  codings_wide_agreed_subset_nodes_min <- 
    codings_wide_agreed_subset_nodes %>% group_by(actor) %>% filter(sent==sent %>% min()) %>% ungroup() %>%
    #left_join(dictionary_actors_labels %>% filter(crisno==crisis) %>% distinct() %>% rename(actor=value_normalized) ) %>% #only need to do for our q codes
    #rename(qcode=actor, actor=value_normalized_label) %>%
    rowwise() %>%
    mutate(actor=actor %>% stringi::stri_wrap(width=15) %>% paste0(collapse='\n'))
  
  
  for(i in 1:nrow(codings_wide_agreed_subset_nodes)){
    g <- g %>%  add_vertices(1, name=codings_wide_agreed_subset_nodes$actor_sent[i],
                                actor = codings_wide_agreed_subset_nodes$actor[i], 
                                sent = codings_wide_agreed_subset_nodes$sent[i]  ) #, type = nodes$type[i] #, leaf = nodes$leaf[i]
  }
  
  xy <- cbind(codings_wide_agreed_subset_nodes$x, codings_wide_agreed_subset_nodes$y )
  
  
  #####Time Edges
  codings_wide_agreed_subset_nodes_edges_time <- cbind(codings_wide_agreed_subset_nodes, bind_rows(codings_wide_agreed_subset_nodes[-1,],codings_wide_agreed_subset_nodes[1,] ) ) %>% janitor::clean_names() %>% filter(actor==actor_2 & sent_2>sent) %>% distinct()
  
  g <- g %>% 
       add_edges(codings_wide_agreed_subset_nodes_edges_time[,c('actor_sent','actor_sent_2')] %>% as.matrix() %>% t() %>% as.vector(),
                 actor=codings_wide_agreed_subset_nodes_edges_time$actor, timeedge=T, leaf='', eventedge=F)
  
  
  ######Directed
  codings_wide_agreed_subset_directed <- 
            dyadic_ucdp_clean_dyad %>% 
            dplyr::select(sent=sent, actor_1=actor_1, actor_2=actor_2, leaf ) %>% distinct() %>%
            mutate(actor_sent_1= actor_1 %>% paste0("_", str_pad(sent, 2, pad = "0") )) %>%
            mutate(actor_sent_2= actor_2 %>% paste0("_", str_pad(sent, 2, pad = "0") )) %>%
            group_by(sent,actor_1, actor_sent_1,actor_sent_2) %>%
              summarise(leaf=paste(leaf, collapse="\n") %>% tolower() ) #%>%
            #filter(actor_sent_2 %>% str_detect("Q30") | actor_sent_1 %>% str_detect("Q30"))
  
  g <- g %>% add_edges(codings_wide_agreed_subset_directed[,c('actor_sent_1','actor_sent_2')] %>% as.matrix() %>% t() %>% as.vector(),
                       timeedge=F, 
                       leaf=codings_wide_agreed_subset_directed$leaf, 
                       eventedge=T,
                       actor=codings_wide_agreed_subset_directed$actor_1) 
  
  
  
    p_ucdp_metro_map <- g %>%  
          ggraph("manual",x=xy[,1],y=xy[,2]) +  #geom_edge_parallel
    
          #Time edges
          geom_edge_link(aes(
                          edge_colour=actor,
                          filter=timeedge==T
                          ),
                          edge_width=0.1, 
                          show.legend = F
                         ) +
          geom_node_point(aes(color=actor),size=1,stroke=0.5) +
    
          #Event edges
          #geom_path(data = hbundle, aes(x, y, group = group), col = "#9d0191", size = 0.05) +
          geom_edge_arc(aes(  
                              colour=actor,
                              label=leaf,
                              filter=eventedge==T #& bundle_count==1
                              ),
                          vjust = -0.75,
                          lineheight = .75,
                          sep = unit(1, 'mm'), 
                          edge_width=0.25, 
                          show.legend = F,
                          arrow = arrow(length = unit(2, 'mm')),
                          label_size=3,
                          check_overlap=T,
                          start_cap = circle(3, 'mm'),
                          end_cap = circle(3, 'mm'),
                          angle_calc = 'along'
                         ) +

              #Not in phoenix
              #geom_text(data=fatalities %>% filter(interact_fatalities>1), aes(x=x+4,y=y, size=interact_fatalities+1), color='black', label='☠', angle=0) + 
              #Not in phoenix
              #geom_text(data=codings_wide_agreed_subset_monad, aes(x=x,y=y, label=leaf), nudge_y=40, angle=0, lineheight = .75, size=3) +
              geom_text(data=codings_wide_agreed_subset_nodes_min, aes(x=x,y=y, label=actor, color=actor), nudge_y=150, angle=0, size=4, lineheight = .75, fontface = "bold") + #-45
              scale_color_manual(values = actor_colors)  +
              scale_edge_color_manual(values = actor_colors) +
              #theme_bw() + 
              #labs( title = plot_title ) +
              theme_graph() +
              theme(legend.position = "none") #+
              #Not in phoenix
              #ggimage::geom_image(data= units, aes(x=x+offeset,y=y-30, image = IMAGE), size = 0.015)
    
    
  p_ucdp_metro_map$sentence_count <- codings_wide_agreed_subset_nodes$sent %>% unique() %>% length()
  p_ucdp_metro_map$actor_colors <- actor_colors
  p_ucdp_metro_map$incident_ucdp_clean_subset <- incident_ucdp_clean_subset
  
  p_ucdp_metro_map %>% saveRDS(save_ucdp_incidents_file)
}

icb_crises %>% filter(yrtrig>=1989 & crisno %in% c(196, 426) ) %>% pull(crisno) %>% unique()  %>% sapply(FUN=function(x) ucdp_ged_metro_plots(x))


```




# Cameo Systems

```{r}

CAMEO_eventcodes <- read_tsv(paste0(here::here(), "/replication_paper/data/in/CAMEO.eventcodes.txt"), col_types='cc') %>% janitor::clean_names()


cameo_code_rejects <- c('Make statement, not specified below', 'Consult, not specified below','Praise or endorse','Accuse, not specified below',
                        'Make statement, not specified below','Meet at a third location','Consult, not specified below')


#Comment to not reject
role_rejects <- c(
  "Agriculture-focused actors",
  "Business (NOT MNCs)",
  "Civilians",
  "Criminal actors",
  "Development-focused actors" ,
  "Education-focused actors",
  "Elites, celebrities",
  "Environment-focused actors",
  #"Government",
  "Health-focused actors",
  "Human rights-focused actors",
  #"Intelligence agencies",
  "Judicial actors",
  "Labor-focused actors",
  "Law enforcement agencies",
  "Legislative bodies/actors",
  "Media-related actors/organizations",
  #"Military",
  #"Opposition groups (often parliamentary)" ,
  #"Political party",
  #"Radical/extremist/fundamentalist",
  #"Rebels/insurgents",
  "Refugee-focused actors" #,
  #"Unaffiliated armed forces"  
)


cameo_role_codes <- data.frame(
       stringsAsFactors = FALSE,
                   role_code = c("GOV","SPY","OPP",
                            "MIL","PTY","REB","EDU","COP","JUD","CRM",
                            "BUS","MED","CVL","UAF","AGR","ELI","DEV","ENV",
                            "HLH","HRI","LAB","LEG","REF","MOD","RAD"),
  role_code_label = c("Government",
                            "Intelligence agencies",
                            "Opposition groups (often parliamentary)",
                            "Military",
                            "Political party",
                            "Rebels/insurgents",
                            "Education-focused actors",
                            "Law enforcement agencies",
                            "Judicial actors",
                            "Criminal actors",
                            "Business (NOT MNCs)",
                            "Media-related actors/organizations",
                            "Civilians",
                            "Unaffiliated armed forces",
                            "Agriculture-focused actors",
                            "Elites, celebrities",
                            "Development-focused actors",
                            "Environment-focused actors",
                            "Health-focused actors",
                            "Human rights-focused actors",
                            "Labor-focused actors",
                            "Legislative bodies/actors",
                            "Refugee-focused actors",
                            "Moderate/mainstream group",
                            "Radical/extremist/fundamentalist")
) %>% janitor::clean_names()





  subject_rejects <- c(
  "ACTIVISM,1" , "ACTIVISM,2" , "AGRICULTURE,1" , "AGRICULTURE,2" , "AGRICULTURE,3" , "AGRICULTURE,4" , 
  "BAILOUT,1" , "BANKRUPTCY,1" , 
   "BLACK_MARKET,1" , "CHECKPOINT,1" , 
   "CIVIL_SOCIETY,1" , "CLIMATE_CHANGE,1" , "COAL,1" , "COAL,2" , "COAL,3" , "COMMON_ROBBERY,1" , "CORRUPTION,1" , "CORRUPTION,2"     , 
    "DISCRIMINATION,1" , "DISEASE,1" , "DISEASE,2" , "DISEASE,3" , "DISEASE,4" , 
    "DRUG_CARTELS,1" , "DRUG_TRADE,1" , "DRUGS,1" , "DRUGS,2" , "DRUGS,3" , 
    "EXCHANGE_RATE,1" , "FOOD_SECURITY,1" , 
       "HOUSING_PRICES,1" , 
          "ELECTRICITY_OUTAGE,1" , 
          "INT_FINANCIAL_INST,1" , "INT_FINANCIAL_INST,2" , "INTEREST_RATES,1" , "INTEREST_RATES,2" , "LABOR_STRIKE,1" , 
   "LABOR_UNIONS,1" , "LABOR_UNIONS,2" , "LABOR_UNIONS,4" , "LANDMINE,1" , "LGBT,1" , "LITERACY,1" , "MEDIA_CENSORSHIP,1" , "MONOPOLY,1" , 
   "MONOPOLY,2" , 
    "ORGANIZED_CRIME,1" , 
    "POSTSECONDARY_EDUCATION,1" , "POSTSECONDARY_EDUCATION,2" , "POSTSECONDARY_EDUCATION,3" , "POVERTY,1" , "PRIVATIZATION,1" , "PRIVATIZATION,2" , 
   "PUBLIC_TRANSIT,1" , "PUBLIC_TRANSIT,2" , "PUBLIC_TRANSIT,3" , "RAPE,1" , "REFUGEES,1" , "REFUGEES,2" , "REFUGEES,3" , "RENEWABLE_ENERGY,1" , 
   "SCHOOLS,1" , "SCHOOLS,2" , "SCHOOLS,3" , 
   "SEXTRANS_DISEASE,1" , "SHORTAGE,1" , "SOCIAL_MOVEMENT,1" , "STUDENTS,1" , "STUDENTS,2" , "STUDENTS,3" , "SUBSIDIES,1" , 
   "TEACHERS,1" , "TEACHERS,2" , 
    "UNEMPLOYMENT,1" , "VACCINATION,1" , 
   "VACCINATION,2" , "YOUTH_MOVEMENT,1" 
  )
  
  # "AIRSTRIKE,1"                 "AIRSTRIKE,2"                
  # "ASSASSINATION,1"                      "BIOLOGICAL_WEAPONS,1"                  "CHEMICAL_WEAPONS,1"          "CHEMICAL_WEAPONS,2"         
  # "COUP_DISCUSSION,1"           "CYBER_SECURITY,1"               "DRONE,1"                    
  # "EARLY_CHILDHOOD_EDUCATION,1" "ECONOMIC_MOVEMENT,1"         "ELECTION,1"                 
  # "ELECTION,2"                    "EUROPEAN_UNION,1"            "EUROPEAN_UNION,2"              "FOREIGN_AID,1"                    
  # "HUMAN_RIGHTS,1"              "HUMAN_RIGHTS,2"              "HUMAN_RIGHTS,3"              "ID_ARMS_DEAL,1"              "ID_ATROCITY,1"               "ID_ATROCITY,2"               "ID_DEMOCRACY,1"              "ID_DEMOCRACY,2"            
  # "ID_EXTREMISM,1"              "ID_EXTREMISM,2"              "ID_IMMIGRATION,1"            "ID_IMMIGRATION,2"            "ID_JIHAD,1"                  "ID_JIHAD,2"                  "ID_JIHAD,3"                  "ID_PROLIFERATION,1"        
  # "ID_SMUGGLING,1"              "ID_TORTURE,1"                "IED,1"                            "NAMED_TERROR_GROUP,1"        "NAMED_TERROR_GROUP,2"        "NATIONAL_MOVEMENT,1"         "NATURAL_DISASTER,1"          "NATURAL_DISASTER,2"   # "NATURAL_GAS,1"               "NEW_CONSTRUCTION,1"         
  # "NUCLEAR_ENERGY,1"            "NUCLEAR_ENERGY,2"            "NUCLEAR_WEAPONS,1"           "NUCLEAR_WEAPONS,2"           "NUCLEAR_WEAPONS,3"           "OIL,1"                            "PEACEKEEPERS,1"             
  # "POLITICAL_PRISONER,1"        "POLITICAL_PRISONER,2"                 
  # "RETALIATION,1"               "SANCTIONS,1"                 "SANCTIONS,2"                      "SECURITY_SERVICES,1"         "SECURITY_SERVICES,2"        
  # "SUICIDE_ATTACK,1"           
  # "TERROR,1"                    "TERROR,2"                    "TOURISM,1"                   "TOURISM,2"                               "VIOLENT_UNREST,1"            "WATER_SECURITY,1"            "WMD,1"                       
  
  
  
#CAMEO_eventcodes <- read_tsv(paste0(here::here(), "/replication_paper/data/in/CAMEO.eventcodes.txt")) %>% janitor::clean_names()


```



## ICEWS

### Data Loads

```{r}

kill_sectors <- c(
  'Police,Government',
'Social,Media',
'Government,Judicial',
'Media,Social',
'Judicial,Government',
'Dissident,Criminals / Gangs',
'Criminals / Gangs,Dissident',
'Social,Legal',
'Legal,Social',
'Social,Business',
'Business,Social',
'Social,Education',
'Education,Social',
'Social,Labor',
'Labor,Social',
'Local,Provincial,Government',
'Social,National Religious',
'National Religious,Social',
'Local,Government,Provincial',
'Government,Finance / Economy / Commerce / Trade Ministry,Executive',
'Executive,Interior / Home Ministry,Government',
'Medical / Health NGOs,Nongovernmental Organizations / Activists',
'Government,Interior / Home Ministry,Executive',
'Social,Media,News',
'Social,Agricultural',
'Social,News,Media',
'News,Media,Social',
'Media,News,Social',
'Social,Medical / Health',
'Medical / Health,Social',
'Ideological,Center Left,Executive,Parties,(National) Major Party,Executive Office,Government',
'Social,Refugees / Displaced',
'Agricultural,Social',
'Ideological,Center Left,Parties,(National) Major Party',
'Dissident,Nongovernmental Organization (International),Parties,(National) Major Party',
'Parties,(National) Major Party,Center Left,Ideological',
'Refugees / Displaced,Social',
'Dissident,Exiles',
'Party',
'Parties',
"General Population",
"^Elite$"
)
kill_sectors_regex <- paste0(kill_sectors, collapse="|")

files <- list.files(path = paste0(here::here(), "/replication_paper/data/ignore/icews_dataverse/dataverse_files/"), full.names = T)
icews <- bind_rows(lapply(files, FUN=function(x) read_tsv(x) )  ) %>% janitor::clean_names()

dim(icews)

CAMEO_eventcodes <- read_tsv(paste0(here::here(),"/replication_paper/data/in/CAMEO.eventcodes.txt"), col_types='cc') %>% janitor::clean_names()

codes_used <-icews %>% count(cameo_code)


target_file <- paste0(here::here(),"/replication_paper/data/in/icb_manual_recoding_master_sheet.xlsx")
actor_translator    <- readxl::read_excel(target_file, sheet="actor_translator") 

#Rex start here tomorrow, figure out how to do this join correctly
actor_translator_icews <- actor_translator %>%  dplyr::select(ICEWS_Actor.Name, ICEWS_Country, QCode, QCode_name)
#%>% mutate(icews=ifelse(ICEWS_Country=="International Government Organizations", ICEWS_Actor.Name, ICEWS_Country))

#Going to heavily filter on source sectors and source name
#c(icews$source_sectors,icews$source_name) %>% table()

#This doesn't totally work because India has 3 copies. The lower thing gets a different q code than the higher thing, so we first have to try to match on the lower, and if that fails match on the higher kinda
#Indian Administered Kashmir		India

dim(icews) #15,751,586
icews_clean <- icews %>% 
               left_join(CAMEO_eventcodes %>% mutate(cameo_code=cameo_code) # %>%  #You have 
                           # dplyr::select(cameo_code=cameoeventcode, cameo_label= eventdescription)  
                         )  %>%
                filter(source_country %in% na.omit(actor_translator$ICEWS_Country) | source_name %in% na.omit(actor_translator$ICEWS_Actor.Name)) %>%
                filter(target_country %in% na.omit(actor_translator$ICEWS_Country) | target_name %in% na.omit(actor_translator$ICEWS_Actor.Name) ) %>%
                filter(!source_sectors %>% str_detect(kill_sectors_regex)) %>%
                filter(!target_sectors %>% str_detect(kill_sectors_regex)) %>%
                #Just apply the wikidata actor labels
                #mutate(source=ifelse(is.na(source_country) , source_name, source_country)) %>%
                #mutate(target=ifelse(is.na(target_country) ,target_name , target_country)) %>%
                left_join( actor_translator_icews %>% dplyr::select(source_name=ICEWS_Actor.Name,  source_q_code_actor=QCode, source_q_label_actor=QCode_name) %>% distinct() %>% na.omit() ) %>%
                left_join( actor_translator_icews %>% filter(is.na(ICEWS_Actor.Name)) %>% dplyr::select(source_country=ICEWS_Country,  source_q_code_country=QCode, source_q_label_country=QCode_name) %>% distinct() %>% na.omit() ) %>%
                mutate(source_q_code=ifelse(!is.na(source_q_code_actor) , source_q_code_actor, source_q_code_country)) %>%
                mutate(source_label=ifelse(!is.na(source_q_code_actor) , source_q_label_actor, source_q_label_country)) %>%
  
                left_join( actor_translator_icews %>% dplyr::select(target_name=ICEWS_Actor.Name,  target_q_code_actor=QCode, target_q_label_actor=QCode_name) %>% distinct() %>% na.omit() ) %>%
                left_join( actor_translator_icews %>% filter(is.na(ICEWS_Actor.Name)) %>% dplyr::select(target_country=ICEWS_Country,  target_q_code_country=QCode, target_q_label_country=QCode_name) %>% distinct() %>% na.omit() ) %>%
                mutate(target_q_code=ifelse(!is.na(target_q_code_actor) , target_q_code_actor, target_q_code_country)) %>%
                mutate(target_label=ifelse(!is.na(target_q_code_actor) , target_q_label_actor, target_q_label_country)) %>%
  
                left_join( actor_translator_icews %>% filter(is.na(ICEWS_Actor.Name)) %>% dplyr::select(country=ICEWS_Country,  country_q_code=QCode) %>% distinct() %>% na.omit() ) 
  
dim(icews_clean) #1,965,573 it's still too many but it's just close enough now #1,965,573

#source_sectors_n <- icews_clean %>% count(source_sectors) %>% arrange(desc(n)) #there are 243k unique sectors, they're nested so you can blacklist larger ones with a regex and it'll catch lower
#source_sectors_n %>% write_csv(paste0(here::here(), "/data_out/icews_sectors.csv"))

```

### Plots

```{r}



icews_metro_plots <- function(crisis=426, topactor=F, exclude='', savefile=NULL){

  print(crisis)
  #crisis=426
  #exclude = c('Chad', 'Southern African Development Community','United States','European Union','South Africa','Zambia','Namibia', 'Angola','United Nations','Zimbabwe')
  #save_icews_file = paste0(here::here(), "/replication_paper/figures/p_icews_metro_plot_",crisis,"_paper.Rds")
  plot_title <- crisno_name_years %>% filter(crisno==crisis) %>% mutate(title="Crisis #" %>% paste0(crisno, " ", crisname, " (", yrtrig, "-",yrterm,")")) %>% pull(title)
  if(is.null(savefile)){
    savefile <- paste0(here::here(), "/replication_paper/figures/metro_plots/p_icews_metro_plot_",crisis,".Rds")
  }
    
  date_start <- lubridate::as_date(paste0(icb_crises[icb_crises$crisno==crisis,]$yrtrig , "-", icb_crises[icb_crises$crisno==crisis,]$motrig, "-01"))
  date_end <- lubridate::as_date(paste0(icb_crises[icb_crises$crisno==crisis,]$yrterm , "-", icb_crises[icb_crises$crisno==crisis,]$moterm, "-31"))
  
  year_start <-icb_crises[icb_crises$crisno==crisis,]$yrtrig
  year_end   <- icb_crises[icb_crises$crisno==crisis,]$yrterm 
  
  start_simple <- icb_crises[icb_crises$crisno==crisis,]$start_simple
  end_simple <- icb_crises[icb_crises$crisno==crisis,]$end_simple


  actor_sent_counts <- 
    bind_rows(
        codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(sent=final_event_ordering,actor=think_actor_a),
        codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(sent=final_event_ordering,actor=say_actor_a),
        codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(sent=final_event_ordering,actor=say_actor_b),
        codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(sent=final_event_ordering,actor=do_actor_a),
        codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(sent=final_event_ordering,actor=do_actor_b)
      ) %>% 
        na.omit() %>%
        mutate(actor = strsplit(as.character(actor), ";")) %>% unnest(actor) %>% distinct() %>% count(actor) %>% arrange(n %>% desc() )
  
  #Only consider diads that appear in our data
  qcodes <- codings_long_agreement %>% dplyr::filter(crisno==crisis & variable_normalized %>% str_detect('actor') & value_normalized!='') %>% pull(value_normalized) %>% unique() %>% na.omit()
  actors_translator <- actor_translator %>% filter(QCode %in% qcodes ) %>% janitor::clean_names() %>%
                       mutate(icews_actor = ifelse(icews_country %in% "International Government Organizations", icews_actor_name,icews_country))

  if(nrow(actors_translator)<2 ){
    print("Not enough actors")
    return()
  }
  
  diads_qcodes <- bind_rows(
                codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% 
                  dplyr::select(think_actor_a, say_actor_a, say_actor_b, do_actor_a, do_actor_b) %>% dplyr::select(actor_a=say_actor_a, actor_b= say_actor_b),
                codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% 
                  dplyr::select(think_actor_a, say_actor_a, say_actor_b, do_actor_a, do_actor_b) %>% filter(is.na(say_actor_a)) %>% 
                  dplyr::select(actor_a=do_actor_a, actor_b=do_actor_b)
                ) %>% 
                mutate(actor_a = strsplit(as.character(actor_a), ";")) %>%  unnest(actor_a) %>%
                mutate(actor_b = strsplit(as.character(actor_b), ";")) %>%  unnest(actor_b) %>%
                na.omit() %>% 
                distinct() %>%
                left_join(actors_translator %>% dplyr::select(actor_a=q_code, source_label=q_code_name) ) %>% #source_sectors
                left_join(actors_translator %>% dplyr::select(actor_b=q_code, target_label=q_code_name) )  %>%  #target_sectors
                mutate(source_target_actor=paste0(actor_a, "_", actor_b) ) %>%
    
                filter(actor_a!=actor_b) #Decide to exclude when the target is the same as the source


      
  #phoenix_clean$joined_issues %>% unique()
  #install.packages('parsedate')
  library(parsedate)
  
  #Ok the IOs are just NA
  #icews_clean_actors_source <- icews_clean %>% dplyr::select(source_name, source_sectors, source_country) %>% count(source_name, source_sectors, source_country)
  #icews_clean_actors_target <- icews_clean %>% dplyr::select(target_name, target_sectors, target_country) %>% count(target_name, target_sectors, target_country)
  
  icews_clean_subset <- icews_clean %>% 
                        
                        mutate(source_target_actor=paste0(source_q_code, "_", target_q_code) ) %>%
                       filter(
                              event_date>=date_start & #Require it to be between the dates of the crisis
                              event_date<=date_end  &
                              source_target_actor %in% diads_qcodes$source_target_actor #require it to be between actors in ICBe  
                              ) %>%
                        mutate(country_valid = is.na(country_q_code) | (country_q_code %in% c(diads_qcodes$actor_a, diads_qcodes$actor_b) ) )  %>%
                        filter(country_valid==T) %>%
                        filter(! cameo_label %in%  cameo_code_rejects) %>% #reject thost common but worthless event types
                       #
                       dplyr::select(event_date,
                                     source_target_actor,
                                     source_label,
                                     target_label,
                                     
                                     source_name,
                                     source_sectors,
                                     source_country,
                                     source_q_code,
                                     
                                     target_name,
                                     target_sectors,
                                     target_country,
                                     target_q_code,
                                     #same_target_source,
                                     #code, root_code, 
                                     cameo_label, 
                                     country,
                                     country_q_code
                                     #cameo_event_root_label,
                                     #joined_issues,placename, countryname, joined_issues, process
                                     ) %>%
                       distinct() %>%
                       mutate(year = event_date %>% lubridate::year()  )  %>%
                       mutate(month = event_date %>% lubridate::month()  )  %>%
                       mutate(day = event_date %>% lubridate::day()  ) %>%
                       arrange(year,month, day) %>%
                       mutate(sent= year*10000+month*100+day   )  %>% 
                       mutate(sent= as.factor(sent - min(sent, na.rm=T) + 1) %>% as.numeric()  )  %>%
                       filter(!source_label %in% exclude) %>%
                       filter(!target_label %in% exclude) 
    


  
  
  #For crises with too many events we subset it to just dyadic events with
  notes <- NULL
  if(topactor & nrow(icews_clean_subset)>100){
    diads_qcodes <- diads_qcodes %>% filter(actor_a== actor_sent_counts$actor[1] | actor_b==actor_sent_counts$actor[1]) #
    icews_clean_subset <- icews_clean_subset %>% filter( source_target_actor %in% diads_qcodes$source_target_actor )
    notes <- "Note: Showing only dyadic events with top actor"
  }
  
  #This has to come after
  #dim(icews_clean_subset) #11,092
  if(nrow(icews_clean_subset)==0 | 
     (c(icews_clean_subset$source_label,icews_clean_subset$target_label) %>% na.omit() %>% unique() %>% length())<2  #Reject if not 2 actors
     ){
    print("No ICEWs events for this crisis")
    return()
  }
  
  library(ggraph)
  library(RColorBrewer)
  
  g <- make_empty_graph(n = 0, directed = TRUE)
    #graph_from_data_frame(vertices=nodes) #relations, directed=TRUE, 
  

  
  codings_wide_agreed_subset_diad <- icews_clean_subset %>% 
                                     dplyr::select(year, month, sent=sent, actor_1=source_label, actor_2=target_label, cameo_event_label=cameo_label ) %>% distinct() %>%
                                     mutate(cameo_event_label=cameo_event_label %>% str_replace(', not specified below','') %>% tolower() )  
  #Order actors by how many interactions they have together
  temp <- codings_wide_agreed_subset_diad  %>% dplyr::select(-cameo_event_label, -year, -month) %>% arrange(actor_1, actor_2) %>% distinct()
  
  temp2 <- bind_rows(
    temp,
    temp %>% setNames(c("story_date", "actor_2", "actor_1" ))
  ) %>% count(actor_1, actor_2) %>% arrange(actor_1, actor_2) %>% arrange(n)
  
  temp2_wide <- temp2 %>% pivot_wider(id_cols=c(actor_1), names_from=actor_2, values_from=n) %>% mutate_if(is.numeric, tidyr::replace_na, 0) %>% as.data.frame()
  rownames(temp2_wide) <- temp2_wide$actor_1
  temp2_wide$actor_1 <- NULL
  temp2_wide <- temp2_wide %>% as.matrix()
  temp2_wide <- 1 - (temp2_wide/max(temp2_wide))
  temp2_wide <- temp2_wide[sort(rownames(temp2_wide)), sort(colnames(temp2_wide))]
  hc <- hclust(temp2_wide %>% as.dist(), method="single")
  
  #ideal_ordering <- bind_rows(temp_list) %>% t() %>% as.data.frame() %>% apply(1, paste, collapse='') %>% sort() %>% names() #this will break with more than 9
  #  arrange(across(starts_with("V")))
  ideal_ordering <- hc$labels[hc$order] #There's a bug here, put all the isolated nodes by themselves first
  
  #If we're down to one actor we're going to put it in the center and then put other nearby
  if(topactor & nrow(icews_clean_subset)>100){
    ideal_ordering <- c(codings_wide_agreed_subset_diad$actor_1, codings_wide_agreed_subset_diad$actor_2) %>% table() %>% sort() %>% names() %>% rev()
    ideal_ordering <- c(ideal_ordering[c(F,T)] %>% rev(), ideal_ordering[c(T,F)])
  }
  
  
  #####Nodes
  codings_wide_agreed_subset_nodes <- 
            bind_rows(
                      codings_wide_agreed_subset_diad %>% dplyr::select(year, month,sent=sent, actor=actor_1) ,
                      codings_wide_agreed_subset_diad %>% dplyr::select(year, month,sent=sent, actor=actor_2) 
            ) %>% na.omit() %>% distinct()  %>% arrange(actor,sent) %>% mutate(actor_sent= actor %>% paste0("_", str_pad(sent, 2, pad = "0") )) %>% #don't na omit this one
            mutate(x=actor %>% factor(levels=actor %>% unique() %>% setdiff(ideal_ordering) %>% c(ideal_ordering)) %>% as.numeric() *100 ,
                   y=sent*-1 *100)
  
  actors=codings_wide_agreed_subset_nodes$actor %>% unique() %>% as.factor()
  actor_colors = c(brewer.pal(n=11, "Dark2"), brewer.pal(n=11, "Set1"))[1:length(actors)] #ok so pick a bewer pallet with lots of values and then assign it to specific values
  names(actor_colors) = levels(actors)
  
  date_sineposts <- codings_wide_agreed_subset_nodes  %>%
                    mutate(x=max(x)+50) %>%
                    dplyr::select(sent, point_in_time_year=year, point_in_time_month=month,x,y) %>%
                    na.omit() %>% 
                    distinct() %>%  
                    mutate(sent=as.numeric(sent)) %>% arrange(sent) %>%
                    mutate(year_float=point_in_time_year+(point_in_time_month/12)) %>%
                    group_by(sent) %>%
                    filter(year_float==min(year_float)) %>%
                    ungroup() %>% as.data.frame() %>%
                    filter( row_number()==1 |  ( year_float > lag(year_float)  ) )  %>%
                    filter(!duplicated(year_float ) ) %>%
                    mutate(label=paste0(point_in_time_year,"-",month.abb[point_in_time_month]))

  
  ####Actor lavels
  codings_wide_agreed_subset_nodes_min <- 
    codings_wide_agreed_subset_nodes %>% group_by(actor) %>% filter(sent==sent %>% min()) %>% ungroup() %>%
    #left_join(dictionary_actors_labels %>% filter(crisno==crisis) %>% distinct() %>% rename(actor=value_normalized) ) %>% #only need to do for our q codes
    #rename(qcode=actor, actor=value_normalized_label) %>%
    rowwise() %>%
    mutate(actor=actor %>% stringi::stri_wrap(width=15) %>% paste0(collapse='\n'))
  
  
  for(i in 1:nrow(codings_wide_agreed_subset_nodes)){
    g <- g %>%  add_vertices(1, name=codings_wide_agreed_subset_nodes$actor_sent[i],
                                actor = codings_wide_agreed_subset_nodes$actor[i], 
                                sent = codings_wide_agreed_subset_nodes$sent[i]  ) #, type = nodes$type[i] #, leaf = nodes$leaf[i]
  }
  
  xy <- cbind(codings_wide_agreed_subset_nodes$x, codings_wide_agreed_subset_nodes$y )
  
  
  #####Time Edges
  codings_wide_agreed_subset_nodes_edges_time <- cbind(codings_wide_agreed_subset_nodes, bind_rows(codings_wide_agreed_subset_nodes[-1,],codings_wide_agreed_subset_nodes[1,] ) ) %>% janitor::clean_names() %>% filter(actor==actor_2 & sent_2>sent) %>% distinct()
  
  g <- g %>% 
       add_edges(codings_wide_agreed_subset_nodes_edges_time[,c('actor_sent','actor_sent_2')] %>% as.matrix() %>% t() %>% as.vector(),
                 actor=codings_wide_agreed_subset_nodes_edges_time$actor, timeedge=T, leaf='', eventedge=F,
                 bundle_count=1)
  
  
  ######Directed
  codings_wide_agreed_subset_directed <- 
            icews_clean_subset %>% 
            dplyr::select(sent=sent, actor_1=source_label, actor_2=target_label, cameo_event_label=cameo_label ) %>% distinct() %>%
            mutate(cameo_event_label=cameo_event_label %>% str_replace(', not specified below',''))  %>% na.omit()  %>% distinct() %>% 
            mutate(leaf = cameo_event_label %>% tolower() )  %>% 
            mutate(actor_sent_1= actor_1 %>% paste0("_", str_pad(sent, 2, pad = "0") )) %>%
            mutate(actor_sent_2= actor_2 %>% paste0("_", str_pad(sent, 2, pad = "0") )) %>%
            mutate(actor1_actor2= actor_1 %>% paste0("_", actor_2)) %>%
            arrange(actor1_actor2, sent) %>%
    
            group_by(sent,actor1_actor2, actor_1, actor_2, actor_sent_1,actor_sent_2) %>%
              summarise(leaf=paste(leaf, collapse="\n") %>% tolower() ) %>%
            arrange(actor1_actor2,sent) %>%
            group_by(actor1_actor2) %>%
              mutate(leaf_dupe=leaf==lag(leaf)) %>%
              mutate(sent_gap= sent - lag(sent)  ) %>%
            ungroup()
            #filter(actor_sent_2 %>% str_detect("Q30") | actor_sent_1 %>% str_detect("Q30"))
  
  codings_wide_agreed_subset_directed <- codings_wide_agreed_subset_directed  %>% 
                                         filter(!( leaf_dupe %in% T & !is.na(sent_gap) & sent_gap<=31)) %>% #reject the same kind of event within a directed diad that occures again within 31 days back to back
                                         group_by(sent, leaf) %>%
                                             mutate(bundle_count=n()) %>%
                                             mutate(leaf2=ifelse(bundle_count>1 & row_number()>1,'',leaf)) %>% #kill leaf titles past 1 #paste0(sent,"_",actor_1,"_",actor_sent_2)
                                          ungroup() #%>% 
          #filter(bundle_count>1)
  #dim(codings_wide_agreed_subset_directed) #1826 bundled
  
  g <- g %>% add_edges(codings_wide_agreed_subset_directed[,c('actor_sent_1','actor_sent_2')] %>% as.matrix() %>% t() %>% as.vector(),
                       timeedge=F, 
                       leaf=codings_wide_agreed_subset_directed$leaf2, 
                       eventedge=T,
                       actor=codings_wide_agreed_subset_directed$actor_1,
                       bundle_count=codings_wide_agreed_subset_directed$bundle_count
                       ) 
  
  ######Put it all together
  p_icews_metro_map <- g %>%  
          ggraph("manual",x=xy[,1],y=xy[,2]) +  #geom_edge_parallel
    
          #Time edges
          geom_edge_link(aes(
                          edge_colour=actor,
                          filter=timeedge==T
                          ),
                          edge_width=0.1, 
                          show.legend = F
                         ) +
          geom_node_point(aes(color=actor),size=1,stroke=0.5) +
    
          #Event edges
          #geom_path(data = hbundle, aes(x, y, group = group), col = "#9d0191", size = 0.05) +
          geom_edge_arc(aes(  
                              colour=actor,
                              label=leaf,
                              filter=eventedge==T & bundle_count==1
                              ),
                          vjust = -0.75,
                          lineheight = .75,
                          sep = unit(1, 'mm'), 
                          edge_width=0.25, 
                          show.legend = F,
                          arrow = arrow(length = unit(2, 'mm')),
                          label_size=3,
                          check_overlap=T,
                          start_cap = circle(3, 'mm'),
                          end_cap = circle(3, 'mm'),
                          angle_calc = 'along'
                         ) +
              #Grouped Edges
              geom_edge_parallel(aes(  
                                  colour=actor,
                                  label=leaf,
                                  filter=eventedge==T & bundle_count>1
                                  ),
                              vjust = -0.75,
                              lineheight = .75,
                              sep = unit(5, 'mm'), 
                              edge_width=0.4,  #0.25
                              show.legend = F,
                              arrow = arrow(length = unit(1, 'mm')),
                              label_size=4,
                              check_overlap=T,
                              start_cap = circle(3, 'mm'),
                              end_cap = circle(3, 'mm'),
                              angle_calc = 'along'
                             ) +
  

              
              #Not in phoenix
              #geom_text(data=fatalities %>% filter(interact_fatalities>1), aes(x=x+4,y=y, size=interact_fatalities+1), color='black', label='☠', angle=0) + 
              #Not in phoenix
              #geom_text(data=codings_wide_agreed_subset_monad, aes(x=x,y=y, label=leaf), nudge_y=40, angle=0, lineheight = .75, size=3) +
              geom_text(data=date_sineposts, aes(x=x,y=y, label=label), color="grey", nudge_y=0, angle=0, size=4, lineheight = .75, fontface = "bold",check_overlap = T) + #-45
              geom_text(data=codings_wide_agreed_subset_nodes_min, aes(x=x,y=y, label=actor, color=actor), nudge_y=150, angle=0, size=4, lineheight = .75, fontface = "bold") + #-45
              scale_color_manual(values = actor_colors)  +
              scale_edge_color_manual(values = actor_colors) +
              #theme_bw() + 
              #labs( title = plot_title ) +
              theme_graph() +
              theme(legend.position = "none") #+
              #Not in phoenix
              #ggimage::geom_image(data= units, aes(x=x+offeset,y=y-30, image = IMAGE), size = 0.015)
    
  if(!is.null(notes)){
     p_icews_metro_map <- p_icews_metro_map + labs(caption = notes)
  }
    
  p_icews_metro_map$sentence_count <- codings_wide_agreed_subset_nodes$sent %>% unique() %>% length()
  p_icews_metro_map$actor_colors <- actor_colors
  p_icews_metro_map$icews_clean_subset <- icews_clean_subset
  
  p_icews_metro_map  %>% saveRDS(savefile)

}

icb_crises %>% filter(yrtrig>=1995  & crisno %in% c(196, 426)) %>% pull(crisno) %>% unique()  %>% sapply(FUN=function(x) icews_metro_plots(x))

```


## Phoenix

### Data Loads

```{r}


library(tidyverse)
library(countrycode)
library(igraph)
library(ggraph)

a <- readRDS(paste0(here::here(), '/replication_paper/data/in/PhoenixBLN-NYT_1980-2018.Rds'))
b <- dplyr::bind_rows(
  readRDS(paste0(here::here(), '/replication_paper/data/in/PhoenixBLN-SWB_1979-2019a.Rds')),
  readRDS(paste0(here::here(), '/replication_paper/data/in/PhoenixBLN-SWB_1979-2019b.Rds')),          
  readRDS(paste0(here::here(), '/replication_paper/data/in/PhoenixBLN-SWB_1979-2019c.Rds')))
c <- readRDS(paste0(here::here(), '/replication_paper/data/in/PhoenixFBIS_1995-2004.Rds'))
d <- readRDS(paste0(here::here(), '/replication_paper/data/in/PhoenixNYT_1945-2005.Rds'))
e <- readRDS(paste0(here::here(), '/replication_paper/data/in/PhoenixWSJ_1945-2006.Rds'))

phoenix <- bind_rows(a %>% mutate_all(as.character),
                     b %>% mutate_all(as.character),
                     c %>% mutate_all(as.character),
                     d %>% mutate_all(as.character) ,
                     e %>% mutate_all(as.character)
                     )

target_file <- paste0(here::here(),"/replication_paper/data/in/icb_manual_recoding_master_sheet.xlsx")
actor_translator    <- readxl::read_excel(target_file, sheet="actor_translator") 

#8,491,556
library(stringr)
phoenix_clean <- phoenix %>% 
                 filter(source_root!='' & target_root!='') %>%
                 mutate(same_target_source=source_root==target_root) %>%
                 mutate(date_simple=as.numeric(year) + (as.numeric(month)/12) ) %>%
  
                 #mutate(code=code %>% str_pad(4, pad = "0") %>% str_replace("0{1,3}","0")) %>%
                 #mutate(root_code=root_code %>% str_pad(2, pad = "0") %>% str_replace("0{1,3}","0")) %>%
  
                 left_join(CAMEO_eventcodes %>% dplyr::select(code=cameo_code     , cameo_event_label=cameo_label) ) %>%
  
                 left_join(CAMEO_eventcodes %>% dplyr::select(root_code=cameo_code, cameo_event_root_label=cameo_label) %>% filter(nchar(root_code)==2)) %>%
  
                 mutate(joined_issues=ifelse( joined_issues=='',";", joined_issues)  ) %>% #Apparently unnesting an empty string just gets dropped
                 mutate(joined_issues = strsplit(as.character(joined_issues), ";") ) %>%  unnest(joined_issues)  %>% #This drops if the row is missing, I did not know that was it

                 left_join(cameo_role_codes %>% dplyr::select(source_agent=role_code, source_agent_label=role_code_label) %>% distinct() %>% na.omit() ) %>%
                 left_join(cameo_role_codes %>% dplyr::select(target_agent=role_code, target_agent_label=role_code_label) %>% distinct() %>% na.omit() ) %>%
                 left_join(cameo_role_codes %>% dplyr::select(source_others=role_code, source_others_label=role_code_label) %>% distinct() %>% na.omit() ) %>%
                 left_join(cameo_role_codes %>% dplyr::select(target_others=role_code, target_others_label=role_code_label) %>% distinct() %>% na.omit() )  %>% 
                   distinct() %>%
                   filter(
                     !source_others_label %in% role_rejects &
                     !target_others_label %in% role_rejects &
                     !source_agent_label %in% role_rejects &
                     !target_agent_label %in% role_rejects 
                     ) %>%
                 #Just apply the actor labels
                 left_join(actor_translator %>% dplyr::select(source_root=phoenix_2020, source_root_label=QCode_name, source_root_qcode=QCode) %>% distinct() %>% na.omit() ) %>%
                 left_join(actor_translator %>% dplyr::select(target_root=phoenix_2020, target_root_label=QCode_name, target_root_qcode=QCode) %>% distinct() %>% na.omit() )

dim(phoenix_clean) #2,813,748 #2912035 #3,508,495 #4,854,787
  
```


### Plot

[@althausClineCenterHistorical2020a]


```{r, eval=T, echo=F, results='hide', include=T, message=F, cache=F, warning=F,  ft.arraystretch=0.75, fig.width=6, fig.height=6}


phoenix_metro_plots <- function(crisis=196, topactor=F){

  print(crisis)
  #crisis=426
  plot_title <- crisno_name_years %>% filter(crisno==crisis) %>% mutate(title="Crisis #" %>% paste0(crisno, " ", crisname, " (", yrtrig, "-",yrterm,")")) %>% pull(title)
  save_phoenix_file <- paste0(here::here(), "/replication_paper/figures/metro_plots/p_phoenix_metro_plot_",crisis,".Rds")
  
  date_start <- lubridate::as_date(paste0(icb_crises[icb_crises$crisno==crisis,]$yrtrig , "-", icb_crises[icb_crises$crisno==crisis,]$motrig, "-01"))
  date_end <- lubridate::as_date(paste0(icb_crises[icb_crises$crisno==crisis,]$yrterm , "-", icb_crises[icb_crises$crisno==crisis,]$moterm, "-31"))
  
  year_start <-icb_crises[icb_crises$crisno==crisis,]$yrtrig
  year_end   <- icb_crises[icb_crises$crisno==crisis,]$yrterm 
  
  start_simple <- icb_crises[icb_crises$crisno==crisis,]$start_simple
  end_simple <- icb_crises[icb_crises$crisno==crisis,]$end_simple

  actor_sent_counts <- 
        bind_rows(
            #codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(sent=final_event_ordering,actor=think_actor_a),
            #codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(sent=final_event_ordering,actor=say_actor_a),
            #codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(sent=final_event_ordering,actor=say_actor_b),
            codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(sent=final_event_ordering,actor=do_actor_a), #Going to organize around actions
            codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(sent=final_event_ordering,actor=do_actor_b)
          ) %>% 
            na.omit() %>%
            mutate(actor = strsplit(as.character(actor), ";")) %>% unnest(actor) %>% distinct() %>% count(actor) %>% arrange(n %>% desc() )
    
  #Only consider diads that appear in our data
  qcodes <- codings_long_agreement %>% dplyr::filter(crisno==crisis & variable_normalized %>% str_detect('actor') & value_normalized!='') %>% pull(value_normalized) %>% unique() %>% na.omit()
  diads_qcodes <- bind_rows(
                    codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(think_actor_a, say_actor_a, say_actor_b, do_actor_a, do_actor_b) %>%
                      dplyr::select(actor_a=say_actor_a, actor_b= say_actor_b),
                    codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(think_actor_a, say_actor_a, say_actor_b, do_actor_a, do_actor_b) %>%
                      filter(is.na(say_actor_a)) %>% dplyr::select(actor_a=do_actor_a, actor_b=do_actor_b)
                  ) %>% 
                  mutate(actor_a = strsplit(as.character(actor_a), ";")) %>%  unnest(actor_a) %>%
                  mutate(actor_b = strsplit(as.character(actor_b), ";")) %>%  unnest(actor_b) %>%
                  na.omit() %>% distinct() 
  
  actors_translator <- actor_translator %>% filter(QCode %in% qcodes ) %>% janitor::clean_names()

  diads_qcodes <- bind_rows(
                  codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(think_actor_a, say_actor_a, say_actor_b, do_actor_a, do_actor_b) %>% 
                    dplyr::select(actor_a=say_actor_a, actor_b= say_actor_b),
                  codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% 
                    dplyr::select(think_actor_a, say_actor_a, say_actor_b, do_actor_a, do_actor_b) %>% filter(is.na(say_actor_a)) %>% 
                    dplyr::select(actor_a=do_actor_a, actor_b=do_actor_b)
                  ) %>% 
                  mutate(actor_a = strsplit(as.character(actor_a), ";")) %>%  unnest(actor_a) %>%
                  mutate(actor_b = strsplit(as.character(actor_b), ";")) %>%  unnest(actor_b) %>%
                  na.omit() %>% 
                  distinct() %>%
                  left_join(actors_translator %>% dplyr::select(actor_a=q_code, phoenix_2020_a=phoenix_2020) ) %>%
                  left_join(actors_translator %>% dplyr::select(actor_b=q_code, phoenix_2020_b=phoenix_2020) )  %>% 
                  mutate(source_root_target=paste0(actor_a, "_", actor_b) ) %>%
      
                  filter(actor_a!=actor_b) #Decide to exclude when the target is the same as the source

  #phoenix_clean$joined_issues %>% unique()
  #install.packages('parsedate')
  library(parsedate)
  phoenix_clean_subset <- phoenix_clean %>% 
                           mutate(source_root_target=paste0(source_root_qcode, "_", target_root_qcode) ) %>%
        
                           filter(
                                  source_root_target %in% diads_qcodes$source_root_target & 
                                  #target_root %in% na.omit(actors_translator_subset$phoenix_2020) & 
                                  #source_root %in% na.omit(actors_translator_subset$phoenix_2020) &
                                  year>=year_start &
                                  year<=year_end   
                                  #date_simple>=start_simple & 
                                  #date_simple<=end_simple 
                                  ) %>%
                           filter( countryname %in%  na.omit(c('',actors_translator$terrier, actors_translator$icb_letters, actors_translator$phoenix_2020))  ) %>% #also reject anything geotagged not in an actor
                           mutate(crisis_dates= (date_simple>=start_simple & date_simple<=end_simple ) %>% as.numeric()) %>%
                           #Just apply the actor labels
                           distinct()   %>%

                           #
                           dplyr::select(crisis_dates,
                                         story_date, year, month, day, 
                                         source_root_target,
                                         source_root_qcode,
                                         target_root_qcode,
                                         source, source_root, source_agent, source_others,
                                         target, target_root, target_agent, target_others,
                                         source_root_label, source_agent_label, source_others_label,
                                         target_root_label, target_agent_label, target_others_label,
                                         same_target_source,
                                         code, root_code, 
                                         cameo_event_label, 
                                         cameo_event_root_label,
                                         joined_issues,placename, countryname, joined_issues, process) %>%
        
                           dplyr::select(-process) %>%
                           distinct() %>%
        
    
                           #Reject sub actors that we don't think are relevant
                           filter(
                             !source_agent_label %in% role_rejects &
                             !target_agent_label %in% role_rejects &
                             !source_others_label %in% role_rejects &
                             !target_others_label %in% role_rejects
                           ) %>% 
        
                           #Reject subjects we don't think are relevant
                           filter(!joined_issues %in% subject_rejects) %>%
        
                           filter(crisis_dates==T) %>% #limit to just the crisis dates
    
                           filter(!cameo_event_label %in% cameo_code_rejects) %>%
  
                           #Restrict to NYT or max source
                           #group_by(process) %>%
                           #  mutate(process_n=n()) %>%
                           # ungroup() %>%
                           #filter(process_n==max(process_n)) %>% #Always pick the source with the most events #process=="NYT_Pre0101991_V1"
                           arrange(year,month, day) %>%
                           mutate(sent= as.numeric(year)*10000+as.numeric(month)*100+as.numeric(day)   )  %>% 
                           mutate(sent= as.factor(sent - min(sent, na.rm=T) + 1) %>% as.numeric()  ) %>%
                          mutate(cameo_event_label=cameo_event_label %>% str_replace(', not specified below|,  not specified below',''))

    
    
  #For crises with too many events we subset it to just dyadic events with
  notes <- NULL
  if(topactor & nrow(phoenix_clean_subset)>100){
    diads_qcodes <- diads_qcodes %>% filter(actor_a == actor_sent_counts$actor[1] | actor_b == actor_sent_counts$actor[1]) #
    phoenix_clean_subset <- phoenix_clean_subset %>% filter( source_root_target %in% diads_qcodes$source_root_target )
    notes <- "Note: Showing only dyadic events with top actor"
  }
  
    
  dim(phoenix_clean_subset) #
  if(nrow(phoenix_clean_subset)==0 | 
     (c(phoenix_clean_subset$source_root_label,phoenix_clean_subset$target_root_label) %>% na.omit() %>% unique() %>% length())<2  #Reject if not 2 actors
     ){
    print("No Phoenix events for this crisis")
    return()
  }

  library(ggraph)
  library(RColorBrewer)
  
  g <- make_empty_graph(n = 0, directed = TRUE)
    #graph_from_data_frame(vertices=nodes) #relations, directed=TRUE, 
  
  #phoenix_clean$year <- phoenix_clean$story_date %>% lubridate::year()
  #phoenix_clean$month <- phoenix_clean$story_date %>% lubridate::month()
  
  codings_wide_agreed_subset_diad <- phoenix_clean_subset %>% 
                                     dplyr::select(year, month, sent=sent, actor_1=source_root_label, actor_2=target_root_label, cameo_event_label ) %>% distinct() %>%
                                     mutate(cameo_event_label=cameo_event_label %>% str_replace(', not specified below','') %>% tolower() ) 
  #Order actors by how many interactions they have together
  temp <- codings_wide_agreed_subset_diad  %>% dplyr::select(-year, -month, -cameo_event_label) %>% arrange(actor_1, actor_2) %>% distinct()
  
  temp2 <- bind_rows(
    temp,
    temp %>% setNames(c("story_date", "actor_2", "actor_1" ))
  ) %>% count(actor_1, actor_2) %>% arrange(actor_1, actor_2) %>% arrange(n)
  
  temp2_wide <- temp2 %>% pivot_wider(id_cols=c(actor_1), names_from=actor_2, values_from=n) %>% mutate_if(is.numeric, tidyr::replace_na, 0) %>% as.data.frame()
  rownames(temp2_wide) <- temp2_wide$actor_1
  temp2_wide$actor_1 <- NULL
  temp2_wide <- temp2_wide %>% as.matrix()
  temp2_wide <- 1 - (temp2_wide/max(temp2_wide))
  temp2_wide <- temp2_wide[sort(rownames(temp2_wide)), sort(colnames(temp2_wide))]
  hc <- hclust(temp2_wide %>% as.dist(), method="single")
  
  temp_list <- list()
  for(i in 1:nrow(temp2_wide)){
    temp_list[[as.character(i)]] <- cutree(hc, k=i)
  }
  
  #ideal_ordering <- bind_rows(temp_list) %>% t() %>% as.data.frame() %>% apply(1, paste, collapse='') %>% sort() %>% names() #this will break with more than 9
  #  arrange(across(starts_with("V")))
  ideal_ordering <- hc$labels[hc$order] #There's a bug here, put all the isolated nodes by themselves first
  
  #If we're down to one actor we're going to put it in the center and then put other nearby
  if(topactor & nrow(phoenix_clean_subset)>100){
    ideal_ordering <- c(codings_wide_agreed_subset_diad$actor_1, codings_wide_agreed_subset_diad$actor_2) %>% table() %>% sort() %>% names() %>% rev()
    ideal_ordering <- c(ideal_ordering[c(F,T)] %>% rev(), ideal_ordering[c(T,F)])
  }
  
  #####Nodes
  codings_wide_agreed_subset_nodes <- 
            bind_rows(
                      codings_wide_agreed_subset_diad %>% dplyr::select(year, month, sent=sent, actor=actor_1) ,
                      codings_wide_agreed_subset_diad %>% dplyr::select(year, month, sent=sent, actor=actor_2) 
            ) %>% na.omit() %>% distinct()  %>% arrange(actor,sent) %>% mutate(actor_sent= actor %>% paste0("_", str_pad(sent, 2, pad = "0") )) %>% #don't na omit this one
            mutate(x=actor %>% factor(levels=actor %>% unique() %>% setdiff(ideal_ordering) %>% c(ideal_ordering)) %>% as.numeric() *100 ,
                   y=sent*-1 *100)
  
  actors=codings_wide_agreed_subset_nodes$actor %>% unique() %>% as.factor()
  actor_colors = c(brewer.pal(n=11, "Dark2"), brewer.pal(n=11, "Set1"))[1:length(actors)] #ok so pick a bewer pallet with lots of values and then assign it to specific values
  names(actor_colors) = levels(actors)
  
  date_sineposts <- codings_wide_agreed_subset_nodes  %>%
                    mutate(x=max(x)+50) %>%
                    mutate(year=year %>% as.numeric() ) %>%
                    mutate(month=month %>% as.numeric() ) %>%
                    dplyr::select(sent, point_in_time_year=year, point_in_time_month=month,x,y) %>%
                    na.omit() %>% 
                    distinct() %>%  
                    mutate(sent=as.numeric(sent)) %>% arrange(sent) %>%
                    mutate(year_float=point_in_time_year+(point_in_time_month/12)) %>%
                    group_by(sent) %>%
                    filter(year_float==min(year_float)) %>%
                    ungroup() %>% as.data.frame() %>%
                    filter( row_number()==1 |  ( year_float > lag(year_float)  ) )  %>%
                    filter(!duplicated(year_float ) ) %>%
                    mutate(label=paste0(point_in_time_year,"-",month.abb[point_in_time_month]))

  
  ####Actor lavels
  codings_wide_agreed_subset_nodes_min <- 
    codings_wide_agreed_subset_nodes %>% group_by(actor) %>% filter(sent==sent %>% min()) %>% ungroup() %>%
    #left_join(dictionary_actors_labels %>% filter(crisno==crisis) %>% distinct() %>% rename(actor=value_normalized) ) %>% #only need to do for our q codes
    #rename(qcode=actor, actor=value_normalized_label) %>%
    rowwise() %>%
    mutate(actor=actor %>% stringi::stri_wrap(width=15) %>% paste0(collapse='\n'))
  
  
  for(i in 1:nrow(codings_wide_agreed_subset_nodes)){
    g <- g %>%  add_vertices(1, name=codings_wide_agreed_subset_nodes$actor_sent[i],
                                actor = codings_wide_agreed_subset_nodes$actor[i], 
                                sent = codings_wide_agreed_subset_nodes$sent[i]  ) #, type = nodes$type[i] #, leaf = nodes$leaf[i]
  }
  
  xy <- cbind(codings_wide_agreed_subset_nodes$x, codings_wide_agreed_subset_nodes$y )
  
  
  #####Time Edges
  codings_wide_agreed_subset_nodes_edges_time <- cbind(codings_wide_agreed_subset_nodes, bind_rows(codings_wide_agreed_subset_nodes[-1,],codings_wide_agreed_subset_nodes[1,] ) ) %>% janitor::clean_names() %>% filter(actor==actor_2 & sent_2>sent) %>% distinct()
  
  g <- g %>% 
       add_edges(codings_wide_agreed_subset_nodes_edges_time[,c('actor_sent','actor_sent_2')] %>% as.matrix() %>% t() %>% as.vector(),
                 actor=codings_wide_agreed_subset_nodes_edges_time$actor, timeedge=T, leaf='', eventedge=F,
                 bundle_count=1)
  
  
  ######Directed
  codings_wide_agreed_subset_directed <- 
            phoenix_clean_subset %>% 
            dplyr::select(sent=sent, actor_1=source_root_label, actor_2=target_root_label, cameo_event_label ) %>% distinct() %>%
            mutate(cameo_event_label=cameo_event_label %>% str_replace(', not specified below',''))  %>% na.omit()  %>% distinct() %>% 
            mutate(leaf = cameo_event_label %>% tolower() )  %>% 
            mutate(actor_sent_1= actor_1 %>% paste0("_", str_pad(sent, 2, pad = "0") )) %>%
            mutate(actor_sent_2= actor_2 %>% paste0("_", str_pad(sent, 2, pad = "0") )) %>%
            mutate(actor1_actor2= actor_1 %>% paste0("_", actor_2)) %>%
            arrange(actor1_actor2, sent) %>%
    
            group_by(sent,actor1_actor2, actor_1, actor_2, actor_sent_1,actor_sent_2) %>%
              summarise(leaf=paste(leaf, collapse="\n") %>% tolower() ) %>%
            arrange(actor1_actor2,sent) %>%
            group_by(actor1_actor2) %>%
              mutate(leaf_dupe=leaf==lag(leaf)) %>%
              mutate(sent_gap= sent - lag(sent)  ) %>%
            ungroup()
            #filter(actor_sent_2 %>% str_detect("Q30") | actor_sent_1 %>% str_detect("Q30"))
  
  codings_wide_agreed_subset_directed <- codings_wide_agreed_subset_directed  %>% 
                                         filter(!( leaf_dupe %in% T & !is.na(sent_gap) & sent_gap<=31)) %>% #reject the same kind of event within a directed diad that occures again within 31 days back to back
                                         group_by(sent, leaf) %>%
                                             mutate(bundle_count=n()) %>%
                                             mutate(leaf2=ifelse(bundle_count>1 & row_number()>1,'',leaf)) %>% #kill leaf titles past 1 #paste0(sent,"_",actor_1,"_",actor_sent_2)
                                          ungroup() #%>% 
          #filter(bundle_count>1)
  #dim(codings_wide_agreed_subset_directed) #1826 bundled
  
  g <- g %>% add_edges(codings_wide_agreed_subset_directed[,c('actor_sent_1','actor_sent_2')] %>% as.matrix() %>% t() %>% as.vector(),
                       timeedge=F, 
                       leaf=codings_wide_agreed_subset_directed$leaf2, 
                       eventedge=T,
                       actor=codings_wide_agreed_subset_directed$actor_1,
                       bundle_count=codings_wide_agreed_subset_directed$bundle_count
                       ) 
  
  ######Put it all together
  p_phoenix_metro_map <- g %>%  
          ggraph("manual",x=xy[,1],y=xy[,2]) +  #geom_edge_parallel
    
          #Time edges
          geom_edge_link(aes(
                          edge_colour=actor,
                          filter=timeedge==T
                          ),
                          edge_width=0.1, 
                          show.legend = F
                         ) +
          geom_node_point(aes(color=actor),size=1,stroke=0.5) +
    
          #Event edges
          #geom_path(data = hbundle, aes(x, y, group = group), col = "#9d0191", size = 0.05) +
          geom_edge_arc(aes(  
                              colour=actor,
                              label=leaf,
                              filter=eventedge==T & bundle_count==1
                              ),
                          vjust = -0.75,
                          lineheight = .75,
                          sep = unit(1, 'mm'), 
                          edge_width=0.25, 
                          show.legend = F,
                          arrow = arrow(length = unit(2, 'mm')),
                          label_size=3,
                          check_overlap=T,
                          start_cap = circle(3, 'mm'),
                          end_cap = circle(3, 'mm'),
                          angle_calc = 'along'
                         ) +
              #Grouped Edges
              geom_edge_parallel(aes(  
                                  colour=actor,
                                  label=leaf,
                                  filter=eventedge==T & bundle_count>1
                                  ),
                              vjust = -0.75,
                              lineheight = .75,
                              sep = unit(5, 'mm'), 
                              edge_width=0.4,  #0.25
                              show.legend = F,
                              arrow = arrow(length = unit(1, 'mm')),
                              label_size=4,
                              check_overlap=T,
                              start_cap = circle(3, 'mm'),
                              end_cap = circle(3, 'mm'),
                              angle_calc = 'along'
                             ) +
  

              
              #Not in phoenix
              #geom_text(data=fatalities %>% filter(interact_fatalities>1), aes(x=x+4,y=y, size=interact_fatalities+1), color='black', label='☠', angle=0) + 
              #Not in phoenix
              #geom_text(data=codings_wide_agreed_subset_monad, aes(x=x,y=y, label=leaf), nudge_y=40, angle=0, lineheight = .75, size=3) +
              geom_text(data=date_sineposts, aes(x=x,y=y, label=label), color="grey", nudge_y=0, angle=0, size=4, lineheight = .75, fontface = "bold",check_overlap = T) + #-45
              geom_text(data=codings_wide_agreed_subset_nodes_min, aes(x=x,y=y, label=actor, color=actor), nudge_y=150, angle=0, size=4, lineheight = .75, fontface = "bold") + #-45
              scale_color_manual(values = actor_colors)  +
              scale_edge_color_manual(values = actor_colors) +
              #theme_bw() + 
              #labs( title = plot_title ) +
              theme_graph() +
              theme(legend.position = "none") #+
              #Not in phoenix
              #ggimage::geom_image(data= units, aes(x=x+offeset,y=y-30, image = IMAGE), size = 0.015)
    
  if(!is.null(notes)){
     p_phoenix_metro_map <- p_phoenix_metro_map + labs(caption = notes)
  }
    
  p_phoenix_metro_map$sentence_count <- codings_wide_agreed_subset_nodes$sent %>% unique() %>% length()
  p_phoenix_metro_map$actor_colors <- actor_colors
  p_phoenix_metro_map$phoenix_clean_subset <- phoenix_clean_subset
  
  p_phoenix_metro_map  %>% saveRDS(save_phoenix_file)

}

c(196, 426) %>% sapply(FUN=function(x) phoenix_metro_plots(x))

```






## Terrier

### Data Loads

https://osf.io/4m2u7/

```{r}


df <- data.frame(
       stringsAsFactors = FALSE,
                   agent = c("GOV","SPY","OPP",
                            "MIL","PTY","REB","EDU","COP","JUD","CRM",
                            "BUS","MED","CVL","UAF","AGR","ELI","DEV","ENV",
                            "HLH","HRI","LAB","LEG","REF","MOD","RAD"),
                    agent_label = c("Government",
                            "Intelligence agencies",
                            "Opposition groups (often parliamentary)",
                            "Military",
                            "Political party",
                            "Rebels/insurgents",
                            "Education-focused actors",
                            "Law enforcement agencies",
                            "Judicial actors",
                            "Criminal actors",
                            "Business (NOT MNCs)",
                            "Media-related actors/organizations",
                            "Civilians",
                            "Unaffiliated armed forces",
                            "Agriculture-focused actors",
                            "Elites, celebrities",
                            "Development-focused actors",
                            "Environment-focused actors",
                            "Health-focused actors",
                            "Human rights-focused actors",
                            "Labor-focused actors",
                            "Legislative bodies/actors",
                            "Refugee-focused actors",
                            "Moderate/mainstream group",
                            "Radical/extremist/fundamentalist")
) %>% janitor::clean_names()


files <- list.files(path = paste0(here::here(), "/replication_paper/data/ignore/terrier/largegeolocateddata/"), pattern = ".tsv$", full.names = T)
terrier <- bind_rows(lapply(files, FUN=function(x) read_tsv(x,col_names=F, col_types=paste0(rep('c',50), collapse='')  )  ) ) %>% janitor::clean_names()
dim(terrier) #28,370,448       28

CAMEO_eventcodes <- read_tsv(paste0(here::here(), "/replication_paper/data/in/CAMEO.eventcodes.txt"), col_types='cc' ) %>% janitor::clean_names()
#codes_used <-terrier_clean %>% count(cameo_code)

target_file <- paste0(here::here(),"/replication_paper/data/in/icb_manual_recoding_master_sheet.xlsx")
actor_translator    <- readxl::read_excel(target_file, sheet="actor_translator")

#Maybe it's just ISO3 country codes?
terrier_clean <- terrier %>% 
    dplyr::select(
      cameo_code=x3,
      src_country=x8,
      src_agent=x9,
      src_other_agent=x10,
      
      target_country=x12 ,
      target_agent=x13,
      target_other_agent=x14,
      
      year=x17,
      month=x18,
      day=x19#,
      #random_text=x28
    ) %>% 
    filter(!is.na(src_country) & !is.na(target_country)) %>%
    distinct() %>% 
     mutate(cameo_code=cameo_code %>% as.numeric()) %>% 
     left_join(CAMEO_eventcodes %>% mutate(cameo_code=cameo_code %>% as.numeric()) %>%
                 dplyr::select(cameo_code=cameo_code, cameo_label= cameo_label)  ) %>%
    mutate( cameo_label= cameo_label %>% str_replace(', not specified below','')) %>%
    distinct() %>%

   mutate(src_other_agent=ifelse( src_other_agent=='',";", src_other_agent)  ) %>% #Apparently unnesting an empty string just gets dropped
   mutate(src_other_agent = strsplit(as.character(src_other_agent), ";") ) %>%  unnest(src_other_agent)  %>% #This drops if the row is missing, I did not know that was it

   mutate(target_other_agent=ifelse( target_other_agent=='',";", target_other_agent)  ) %>% #Apparently unnesting an empty string just gets dropped
   mutate(target_other_agent = strsplit(as.character(target_other_agent), ";") ) %>%  unnest(target_other_agent)  %>% #This drops if the row is missing, I did not know that was it
     
   left_join(df %>% dplyr::select(src_other_agent=agent   , src_other_agent_label=agent_label) %>% distinct() %>% na.omit() ) %>%
   left_join(df %>% dplyr::select(target_other_agent=agent, target_other_agent_label=agent_label) %>% distinct() %>% na.omit() ) %>%
  
   left_join(df %>% dplyr::select(src_agent=agent, src_agent_label=agent_label) %>% distinct() %>% na.omit() ) %>%
   left_join(df %>% dplyr::select(target_agent=agent, target_agent_label=agent_label) %>% distinct() %>% na.omit() )  %>% 
   distinct() %>%
   filter(
     !src_other_agent_label %in% role_rejects &
     !target_other_agent_label %in% role_rejects &
     !src_agent_label %in% role_rejects &
     !target_agent_label %in% role_rejects 
     ) %>% 
  left_join(actor_translator %>% dplyr::select(src_country=terrier,actor_1_qcode=QCode,actor_1=QCode_name) ) %>%
  left_join(actor_translator %>% dplyr::select(target_country=terrier,actor_2_qcode=QCode,actor_2=QCode_name) ) %>%
  filter(!is.na(actor_1_qcode) & !is.na(actor_2_qcode) ) %>%
  mutate(source_root_target=paste0(src_country, "_", target_country) ) %>%
  mutate(
  event_date= lubridate::as_date(paste0( year, "-", month,"-",day ))
  )
dim(terrier_clean) #2,049,759

#For now
#IGO 223751 for now we're going to exclue just generic Intergovernmental organization and multiinational corps
#MNC 62721
#terrier_clean %>% dplyr::select(src_country, actor_1) %>% filter(is.na(actor_1)) %>% count(src_country) %>% View()

#terrier_clean %>% 
#  dplyr::select(src_agent_label,  src_other_agent_label, target_agent_label, target_other_agent_label, cameo_label) %>% 
#  count(src_agent_label,  src_other_agent_label, target_agent_label, target_other_agent_label, cameo_label) %>% arrange(desc(n)) %>% View()



```


### Plot


```{r, eval=T, echo=F, results='hide', include=T, message=F, cache=F, warning=F,  ft.arraystretch=0.75, fig.width=6, fig.height=6}


terrier_metro_plots <- function(crisis=196, topactor=F){

  print(crisis)
  #crisis=426
  plot_title <- crisno_name_years %>% filter(crisno==crisis) %>% mutate(title="Crisis #" %>% paste0(crisno, " ", crisname, " (", yrtrig, "-",yrterm,")")) %>% pull(title)
  save_terrier_file <- paste0(here::here(), "/replication_paper/figures/metro_plots/p_terrier_metro_plot_",crisis,".Rds")
  
  date_start <- lubridate::as_date(paste0(icb_crises[icb_crises$crisno==crisis,]$yrtrig , "-", icb_crises[icb_crises$crisno==crisis,]$motrig, "-01"))
  date_end <- lubridate::as_date(paste0(icb_crises[icb_crises$crisno==crisis,]$yrterm , "-", icb_crises[icb_crises$crisno==crisis,]$moterm, "-31"))
  
  year_start <-icb_crises[icb_crises$crisno==crisis,]$yrtrig
  year_end   <- icb_crises[icb_crises$crisno==crisis,]$yrterm 
  
  start_simple <- icb_crises[icb_crises$crisno==crisis,]$start_simple
  end_simple <- icb_crises[icb_crises$crisno==crisis,]$end_simple

  actor_sent_counts <- 
        bind_rows(
            #codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(sent=final_event_ordering,actor=think_actor_a),
            #codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(sent=final_event_ordering,actor=say_actor_a),
            #codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(sent=final_event_ordering,actor=say_actor_b),
            codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(sent=final_event_ordering,actor=do_actor_a), #Going to organize around actions
            codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(sent=final_event_ordering,actor=do_actor_b)
          ) %>% 
            na.omit() %>%
            mutate(actor = strsplit(as.character(actor), ";")) %>% unnest(actor) %>% distinct() %>% count(actor) %>% arrange(n %>% desc() )
    
  #Only consider diads that appear in our data
  qcodes <- codings_long_agreement %>% dplyr::filter(crisno==crisis & variable_normalized %>% str_detect('actor') & value_normalized!='') %>% pull(value_normalized) %>% unique() %>% na.omit()
  actors_translator <- actor_translator %>% filter(QCode %in% qcodes ) %>% janitor::clean_names()

  diads_qcodes <- bind_rows(
                  codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% dplyr::select(think_actor_a, say_actor_a, say_actor_b, do_actor_a, do_actor_b) %>% 
                    dplyr::select(actor_a=say_actor_a, actor_b= say_actor_b),
                  codings_wide_agreed %>% dplyr::filter(crisno==crisis  ) %>% 
                    dplyr::select(think_actor_a, say_actor_a, say_actor_b, do_actor_a, do_actor_b) %>% filter(is.na(say_actor_a)) %>% 
                    dplyr::select(actor_a=do_actor_a, actor_b=do_actor_b)
                  ) %>% 
                  mutate(actor_a = strsplit(as.character(actor_a), ";")) %>%  unnest(actor_a) %>%
                  mutate(actor_b = strsplit(as.character(actor_b), ";")) %>%  unnest(actor_b) %>%
                  na.omit() %>% 
                  distinct() %>%
                  left_join(actors_translator %>% dplyr::select(actor_a=q_code, terrier_a=terrier) ) %>% #I think we can reuse Phoenix or maybe not? no probably not
                  left_join(actors_translator %>% dplyr::select(actor_b=q_code, terrier_b=terrier) )  %>% 
                  mutate(source_root_target=paste0(terrier_a, "_", terrier_b) ) %>%
      
                  filter(terrier_a!=terrier_b) #Decide to exclude when the target is the same as the source

  #phoenix_clean$joined_issues %>% unique()
  #install.packages('parsedate')
  library(parsedate)
  terrier_clean_subset <- terrier_clean %>% 

                           filter(
                                  source_root_target %in% diads_qcodes$source_root_target & 
                                  #target_root %in% na.omit(actors_translator_subset$phoenix_2020) & 
                                  #source_root %in% na.omit(actors_translator_subset$phoenix_2020) &
                                  event_date>=date_start &
                                  event_date<=date_end   
                                  #date_simple>=start_simple & 
                                  #date_simple<=end_simple 
                                  ) %>%

                           #
                           dplyr::select(event_date,year,month,
                                         actor_1, actor_1_qcode,
                                         actor_2, actor_2_qcode,
                                         src_country, src_agent_label, src_other_agent_label, target_country, target_agent_label, target_other_agent_label,
                                         source_root_target,
                                         cameo_label) %>%
        
                           distinct() %>%
                           mutate(year = event_date %>% lubridate::year()  )  %>%
                           mutate(month = event_date %>% lubridate::month()  )  %>%
                           mutate(day = event_date %>% lubridate::day()  ) %>%
                           arrange(year,month, day) %>%
                           mutate(sent= year*10000+month*100+day   )  %>% 
                           mutate(sent= as.factor(sent - min(sent, na.rm=T) + 1) %>% as.numeric()  ) 

  #For crises with too many events we subset it to just dyadic events with
  notes <- NULL
  if(topactor & nrow(terrier_clean_subset)>100){
    diads_qcodes <- diads_qcodes %>% filter(actor_a == actor_sent_counts$actor[1] | actor_b == actor_sent_counts$actor[1]) #
    terrier_clean_subset <- terrier_clean_subset %>% filter( source_root_target %in% diads_qcodes$source_root_target )
    notes <- "Note: Showing only dyadic events with top actor"
  }
  
    
  dim(terrier_clean_subset) #
  if(nrow(terrier_clean_subset)==0 | 
     (c(terrier_clean_subset$actor_1,terrier_clean_subset$actor_2) %>% na.omit() %>% unique() %>% length())<2  #Reject if not 2 actors
     ){
    print("No terrier events for this crisis")
    return()
  }

  library(ggraph)
  library(RColorBrewer)
  
  g <- make_empty_graph(n = 0, directed = TRUE)
    #graph_from_data_frame(vertices=nodes) #relations, directed=TRUE, 
  
  codings_wide_agreed_subset_diad <- terrier_clean_subset %>% 
                                     dplyr::select(year, month, sent=sent, actor_1=actor_1, actor_2=actor_2, cameo_label ) %>% distinct() %>%
                                     mutate(cameo_label=cameo_label %>% str_replace(', not specified below','') %>% tolower() ) 
  #Order actors by how many interactions they have together
  temp <- codings_wide_agreed_subset_diad  %>% dplyr::select(-year, -month , -cameo_label) %>% arrange(actor_1, actor_2) %>% distinct()
  
  temp2 <- bind_rows(
    temp,
    temp %>% setNames(c("story_date", "actor_2", "actor_1" ))
  ) %>% count(actor_1, actor_2) %>% arrange(actor_1, actor_2) %>% arrange(n)
  
  temp2_wide <- temp2 %>% pivot_wider(id_cols=c(actor_1), names_from=actor_2, values_from=n) %>% mutate_if(is.numeric, tidyr::replace_na, 0) %>% as.data.frame()
  rownames(temp2_wide) <- temp2_wide$actor_1
  temp2_wide$actor_1 <- NULL
  temp2_wide <- temp2_wide %>% as.matrix()
  temp2_wide <- 1 - (temp2_wide/max(temp2_wide))
  temp2_wide <- temp2_wide[sort(rownames(temp2_wide)), sort(colnames(temp2_wide))]
  hc <- hclust(temp2_wide %>% as.dist(), method="single")
  
  temp_list <- list()
  for(i in 1:nrow(temp2_wide)){
    temp_list[[as.character(i)]] <- cutree(hc, k=i)
  }
  
  #ideal_ordering <- bind_rows(temp_list) %>% t() %>% as.data.frame() %>% apply(1, paste, collapse='') %>% sort() %>% names() #this will break with more than 9
  #  arrange(across(starts_with("V")))
  ideal_ordering <- hc$labels[hc$order] #There's a bug here, put all the isolated nodes by themselves first
  
  #If we're down to one actor we're going to put it in the center and then put other nearby
  if(topactor & nrow(terrier_clean_subset)>100){
    ideal_ordering <- c(codings_wide_agreed_subset_diad$actor_1, codings_wide_agreed_subset_diad$actor_2) %>% table() %>% sort() %>% names() %>% rev()
    ideal_ordering <- c(ideal_ordering[c(F,T)] %>% rev(), ideal_ordering[c(T,F)])
  }
  
  #####Nodes
  codings_wide_agreed_subset_nodes <- 
            bind_rows(
                      codings_wide_agreed_subset_diad %>% dplyr::select(year, month, sent=sent, actor=actor_1) ,
                      codings_wide_agreed_subset_diad %>% dplyr::select(year, month, sent=sent, actor=actor_2) 
            ) %>% na.omit() %>% distinct()  %>% arrange(actor,sent) %>% mutate(actor_sent= actor %>% paste0("_", str_pad(sent, 2, pad = "0") )) %>% #don't na omit this one
            mutate(x=actor %>% factor(levels=actor %>% unique() %>% setdiff(ideal_ordering) %>% c(ideal_ordering)) %>% as.numeric() *100 ,
                   y=sent*-1 *100)
  
  actors=codings_wide_agreed_subset_nodes$actor %>% unique() %>% as.factor()
  actor_colors = c(brewer.pal(n=11, "Dark2"), brewer.pal(n=11, "Set1"))[1:length(actors)] #ok so pick a bewer pallet with lots of values and then assign it to specific values
  names(actor_colors) = levels(actors)
  
  
  date_sineposts <- codings_wide_agreed_subset_nodes  %>%
                      mutate(x=max(x)+50) %>%
                      mutate(year=year %>% as.numeric()) %>%
                      mutate(month=month %>% as.numeric()) %>%
                      dplyr::select(sent, point_in_time_year=year, point_in_time_month=month,x,y) %>%
                      na.omit() %>% 
                      distinct() %>%  
                      mutate(sent=as.numeric(sent)) %>% arrange(sent) %>%
                      mutate(year_float=point_in_time_year+(point_in_time_month/12)) %>%
                      group_by(sent) %>%
                      filter(year_float==min(year_float)) %>%
                      ungroup() %>% as.data.frame() %>%
                      filter( row_number()==1 |  ( year_float > lag(year_float)  ) )  %>%
                      filter(!duplicated(year_float ) ) %>%
                      mutate(label=paste0(point_in_time_year,"-",month.abb[point_in_time_month]))
                      
  ####Actor lavels
  codings_wide_agreed_subset_nodes_min <- 
    codings_wide_agreed_subset_nodes %>% group_by(actor) %>% filter(sent==sent %>% min()) %>% ungroup() %>%
    #left_join(dictionary_actors_labels %>% filter(crisno==crisis) %>% distinct() %>% rename(actor=value_normalized) ) %>% #only need to do for our q codes
    #rename(qcode=actor, actor=value_normalized_label) %>%
    rowwise() %>%
    mutate(actor=actor %>% stringi::stri_wrap(width=15) %>% paste0(collapse='\n'))
  
  
  for(i in 1:nrow(codings_wide_agreed_subset_nodes)){
    g <- g %>%  add_vertices(1, name=codings_wide_agreed_subset_nodes$actor_sent[i],
                                actor = codings_wide_agreed_subset_nodes$actor[i], 
                                sent = codings_wide_agreed_subset_nodes$sent[i]  ) #, type = nodes$type[i] #, leaf = nodes$leaf[i]
  }
  
  xy <- cbind(codings_wide_agreed_subset_nodes$x, codings_wide_agreed_subset_nodes$y )
  
  
  #####Time Edges
  codings_wide_agreed_subset_nodes_edges_time <- cbind(codings_wide_agreed_subset_nodes, bind_rows(codings_wide_agreed_subset_nodes[-1,],codings_wide_agreed_subset_nodes[1,] ) ) %>% janitor::clean_names() %>% filter(actor==actor_2 & sent_2>sent) %>% distinct()
  
  g <- g %>% 
       add_edges(codings_wide_agreed_subset_nodes_edges_time[,c('actor_sent','actor_sent_2')] %>% as.matrix() %>% t() %>% as.vector(),
                 actor=codings_wide_agreed_subset_nodes_edges_time$actor, timeedge=T, leaf='', eventedge=F,
                 bundle_count=1)
  
  
  ######Directed
  codings_wide_agreed_subset_directed <- 
            terrier_clean_subset %>% 
            dplyr::select(sent=sent, actor_1=actor_1, actor_2=actor_2, cameo_label ) %>% distinct() %>%
            mutate(cameo_label=cameo_label %>% str_replace(', not specified below',''))  %>% na.omit()  %>% distinct() %>% 
            mutate(leaf = cameo_label %>% tolower() )  %>% 
            mutate(actor_sent_1= actor_1 %>% paste0("_", str_pad(sent, 2, pad = "0") )) %>%
            mutate(actor_sent_2= actor_2 %>% paste0("_", str_pad(sent, 2, pad = "0") )) %>%
            mutate(actor1_actor2= actor_1 %>% paste0("_", actor_2)) %>%
            arrange(actor1_actor2, sent) %>%
    
            group_by(sent,actor1_actor2, actor_1, actor_2, actor_sent_1,actor_sent_2) %>%
              summarise(leaf=paste(leaf, collapse="\n") %>% tolower() ) %>%
            arrange(actor1_actor2,sent) %>%
            group_by(actor1_actor2) %>%
              mutate(leaf_dupe=leaf==lag(leaf)) %>%
              mutate(sent_gap= sent - lag(sent)  ) %>%
            ungroup()
            #filter(actor_sent_2 %>% str_detect("Q30") | actor_sent_1 %>% str_detect("Q30"))
  
  codings_wide_agreed_subset_directed <- codings_wide_agreed_subset_directed  %>% 
                                         filter(!( leaf_dupe %in% T & !is.na(sent_gap) & sent_gap<=31)) %>% #reject the same kind of event within a directed diad that occures again within 31 days back to back
                                         group_by(sent, leaf) %>%
                                             mutate(bundle_count=n()) %>%
                                             mutate(leaf2=ifelse(bundle_count>1 & row_number()>1,'',leaf)) %>% #kill leaf titles past 1 #paste0(sent,"_",actor_1,"_",actor_sent_2)
                                          ungroup() #%>% 
          #filter(bundle_count>1)
  #dim(codings_wide_agreed_subset_directed) #1826 bundled
  
  g <- g %>% add_edges(codings_wide_agreed_subset_directed[,c('actor_sent_1','actor_sent_2')] %>% as.matrix() %>% t() %>% as.vector(),
                       timeedge=F, 
                       leaf=codings_wide_agreed_subset_directed$leaf2, 
                       eventedge=T,
                       actor=codings_wide_agreed_subset_directed$actor_1,
                       bundle_count=codings_wide_agreed_subset_directed$bundle_count
                       ) 
  
  ######Put it all together
  p_terrier_metro_map <- g %>%  
          ggraph("manual",x=xy[,1],y=xy[,2]) +  #geom_edge_parallel
    
          #Time edges
          geom_edge_link(aes(
                          edge_colour=actor,
                          filter=timeedge==T
                          ),
                          edge_width=0.1, 
                          show.legend = F
                         ) +
          geom_node_point(aes(color=actor),size=1,stroke=0.5) +
    
          #Event edges
          #geom_path(data = hbundle, aes(x, y, group = group), col = "#9d0191", size = 0.05) +
          geom_edge_arc(aes(  
                              colour=actor,
                              label=leaf,
                              filter=eventedge==T & bundle_count==1
                              ),
                          vjust = -0.75,
                          lineheight = .75,
                          sep = unit(1, 'mm'), 
                          edge_width=0.25, 
                          show.legend = F,
                          arrow = arrow(length = unit(2, 'mm')),
                          label_size=3,
                          check_overlap=T,
                          start_cap = circle(3, 'mm'),
                          end_cap = circle(3, 'mm'),
                          angle_calc = 'along'
                         ) +
              #Grouped Edges
              geom_edge_parallel(aes(  
                                  colour=actor,
                                  label=leaf,
                                  filter=eventedge==T & bundle_count>1
                                  ),
                              vjust = -0.75,
                              lineheight = .75,
                              sep = unit(5, 'mm'), 
                              edge_width=0.4,  #0.25
                              show.legend = F,
                              arrow = arrow(length = unit(1, 'mm')),
                              label_size=4,
                              check_overlap=T,
                              start_cap = circle(3, 'mm'),
                              end_cap = circle(3, 'mm'),
                              angle_calc = 'along'
                             ) +
  

              
              #Not in phoenix
              #geom_text(data=fatalities %>% filter(interact_fatalities>1), aes(x=x+4,y=y, size=interact_fatalities+1), color='black', label='☠', angle=0) + 
              #Not in phoenix
              #geom_text(data=codings_wide_agreed_subset_monad, aes(x=x,y=y, label=leaf), nudge_y=40, angle=0, lineheight = .75, size=3) +
              geom_text(data=date_sineposts, aes(x=x,y=y, label=label), color="grey", nudge_y=0, angle=0, size=4, lineheight = .75, fontface = "bold",check_overlap = T) + #-45
              geom_text(data=codings_wide_agreed_subset_nodes_min, aes(x=x,y=y, label=actor, color=actor), nudge_y=150, angle=0, size=4, lineheight = .75, fontface = "bold") + #-45
              scale_color_manual(values = actor_colors)  +
              scale_edge_color_manual(values = actor_colors) +
              #theme_bw() + 
              #labs( title = plot_title ) +
              theme_graph() +
              theme(legend.position = "none") #+
              #Not in phoenix
              #ggimage::geom_image(data= units, aes(x=x+offeset,y=y-30, image = IMAGE), size = 0.015)
    
  if(!is.null(notes)){
     p_terrier_metro_map <- p_terrier_metro_map + labs(caption = notes)
  }
    
  p_terrier_metro_map$sentence_count <- codings_wide_agreed_subset_nodes$sent %>% unique() %>% length()
  p_terrier_metro_map$actor_colors <- actor_colors
  p_terrier_metro_map$terrier_clean_subset <- terrier_clean_subset
  
  p_terrier_metro_map  %>% saveRDS(save_terrier_file)

}

icb_crises %>% filter(yrtrig>=1977 & crisno %in% c(196, 426)) %>% pull(crisno) %>% unique()  %>% sapply(FUN=function(x) terrier_metro_plots(x))


```



